// Code generated by "stringer -type=CoreType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Any-1]
	_ = x[String-2]
	_ = x[Int-3]
	_ = x[Float-4]
	_ = x[Bool-5]
	_ = x[Nothing-6]
	_ = x[Error-7]
	_ = x[InvalidType-8]
	_ = x[Self-9]
}

const _CoreType_name = "AnyStringIntFloatBoolNothingErrorInvalidSelf"

var _CoreType_index = [...]uint8{0, 3, 9, 12, 17, 21, 28, 33, 40, 44}

func (i CoreType) String() string {
	i -= 1
	if i < 0 || i >= CoreType(len(_CoreType_index)-1) {
		return "CoreType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _CoreType_name[_CoreType_index[i]:_CoreType_index[i+1]]
}
