package reporter

import (
	"fmt"
	"os"
	"strings"
	"testing"

	"github.com/ProCode-Software/klar/internal/cli/ansi"
	"github.com/ProCode-Software/klar/internal/errors"
	"github.com/ProCode-Software/klar/internal/lexer"
	"github.com/ProCode-Software/klar/internal/ranges"
	"github.com/ProCode-Software/klar/pkg/parser"
)

type fileMap map[string][]lexer.Token

type reporterTestCase struct {
	name      string
	files     fileMap
	error     errors.CompileError
	expected  string // Uncolored
	termWidth int
	ascii     bool
}

var expectedFile, gotFile *os.File

func TestReporter(t *testing.T) {
	// Create or replace files for diffing
	createFile(t, "./testdata/expected_output.txt", &expectedFile)
	defer expectedFile.Close()
	createFile(t, "./testdata/got_output.txt", &gotFile)
	defer gotFile.Close()

	t.Run("WithoutDiffs", func(t *testing.T) {
		for _, tc := range testCases {
			t.Run(tc.name, func(t *testing.T) { runTest(t, &tc) })
		}
	})
	t.Run("WithDiffs", func(t *testing.T) {
		for _, tc := range diffTestCases {
			t.Run(tc.name, func(t *testing.T) { runTest(t, &tc) })
		}
	})
}

func createFile(t *testing.T, path string, target **os.File) {
	var err error
	if *target, err = os.Create(path); err != nil {
		t.Fatalf("Failed to create expected file: %v", err)
	}
	fmt.Fprintf(*target, "File generated by ../reporter_test.go. DO NOT EDIT\n\n")
}

func runTest(t *testing.T, tc *reporterTestCase) {
	Width = tc.termWidth
	ansi.DisableColor = true
	var out strings.Builder
	r := &Reporter{
		MaxLines:     3,
		ColorPalette: nil,
		CharacterSet: DefaultCharacterSet(),
		Output:       &out,
	}
	if tc.ascii {
		r.CharacterSet = ASCIICharacterSet()
	}
	for name, tokens := range tc.files {
		r.LoadFile(name, name, tokens)
	}
	if _, err := r.Report(tc.error); err != nil {
		t.Fatalf("Failed to report error: %v", err)
	}

	// Trim leading/trailing space
	got := trimNewline(out.String())
	tc.expected = trimNewline(tc.expected)

	// Write to files for diffing
	fmt.Fprintf(expectedFile, "%s:\n%s\n\n", tc.name, tc.expected)
	fmt.Fprintf(gotFile, "%s:\n%s\n\n", tc.name, got)
	if got != tc.expected {
		t.Errorf("Test %s failed", tc.name)
	}
}

func trimNewline(s string) string {
	s = strings.TrimLeft(s, "\n")
	s = strings.TrimRight(s, "\n")
	return s
}



var testCases = []reporterTestCase{
	{
		name:  "SingleLine",
		files: fileMap{"main.klar": parser.TokenizeString("x := 1")},
		error: &errors.ParseError{
			ErrorCode: errors.ErrColonEqual,
			Range:     ranges.NewRange(1, 3, 1, 5),
			File:      "main.klar",
			Label:     "Use ':=' instead",
		},
		expected: singleLine_expected,
	},
	{
		name:  "SingleLine_1Highlight",
		files: fileMap{"main2.klar": parser.TokenizeString("x := 1")},
		error: &errors.ParseError{
			ErrorCode: errors.ErrColonEqual,
			Range:     ranges.NewRange(1, 3, 1, 5),
			File:      "main2.klar",
			Label:     "Use ':=' instead",
			Highlights: []errors.Highlight{
				{ranges.NewRange(1, 1, 1, 2), "This is 'x'"},
			},
		},
		expected: singleLine1Highlight_expected,
	},
	{
		name:  "SingleLine_2Highlights",
		files: fileMap{"main.klar": parser.TokenizeString("x := 1")},
		error: &errors.ParseError{
			ErrorCode: errors.ErrColonEqual,
			Range:     ranges.NewRange(1, 3, 1, 5),
			File:      "main.klar",
			Label:     "Use ':=' instead",
			Highlights: []errors.Highlight{
				{ranges.NewRange(1, 1, 1, 2), "This is 'x'"},
				{ranges.NewRange(1, 6, 1, 7), "'x' is set to 1"},
			},
		},
		expected: singleLine2Highlights_expected,
	},
	{
		name:  "Multiline_2Highlights",
		files: fileMap{"main.klar": parser.TokenizeString("deleteThisLine()\nx := 1")},
		error: &errors.ParseError{
			ErrorCode: errors.ErrRequiredBraces,
			Range:     ranges.NewRange(2, 3, 2, 5),
			File:      "main.klar",
			Label:     "Something else is better",
			Highlights: []errors.Highlight{
				{ranges.NewRange(2, 6, 2, 7), "'x' is set to 1"},
				{ranges.NewRange(1, 1, 2, 7), "Please delete this"},
			},
		},
		expected: Multiline2Highlights_expected,
	},
}
