package reporter

import (
	"github.com/ProCode-Software/klar/internal/cli/ansi"
	"github.com/ProCode-Software/klar/internal/lexer"
)

type ColorPalette struct {
	TokenColors  map[lexer.TokenType]string
	Type         string // The color of type names
	Function     string // The color of function names
	BuiltinFunc  string // The color of built-in function names
	StringEscape string // The color of string escapes

	Divider   string // The color of error dividers
	Box       string // The color of the container and line numbers
	DetailBox string // The color of the detail box and line numbers
	FileName  string // The color of the file name in the header
	FilePos   string // The color of the line and column numbers in the header

	ErrorColor   string // The color of error highlights
	WarningColor string // The color of warning highlights
	HintColor    string // The color of the hint label and hint highlights
	DetailColor  string // The color of detail messages

	Highlight1, Highlight2, Highlight3 string // The color of secondary highlights

	// Underline/text and background colors for added/deleted segments in diffs
	DiffAdd, DiffAddBackground,
	DiffDelete, DiffDeleteBackground string
}

var defaultColors = makeDefaultTokenColors()

func DefaultColorPalette() *ColorPalette {
	return &ColorPalette{
		TokenColors:  defaultColors,
		Type:         ansi.CodeCyan,
		Function:     ansi.CodeMagenta,
		StringEscape: ansi.CodeCyan,
		BuiltinFunc:  ansi.CodeBlue,

		Divider:   ansi.CodeDim,
		Box:       ansi.CodeBlue,
		DetailBox: ansi.CodeMagenta,
		FileName:  ansi.CodeCyan,
		FilePos:   ansi.CodeYellow,

		ErrorColor:   ansi.CodeBoldBrightRed,
		WarningColor: ansi.CodeBoldBrightYellow,
		HintColor:    ansi.CodeBrightBlue,
		DetailColor:  ansi.CodeBrightMagenta,

		Highlight1: ansi.CodeBrightGreen,
		Highlight2: ansi.CodeBrightMagenta,
		Highlight3: ansi.CodeBrightBlue,

		DiffAddBackground:    ansi.CodeBold, // ansi.BackgroundBit8(22),
		DiffAdd:              ansi.CodeBrightGreen,
		DiffDeleteBackground: ansi.CodeBold, // ansi.BackgroundBit8(52), // 88
		DiffDelete:           ansi.CodeBrightRed,
	}
}

type CharacterSet struct {
	HighlightSingle rune // Single-character underlines
	HighlightMulti  rune // Multi-character underlines
	BoxTL           rune // The top left corner of the box
	// The top border of the box. Also used at the end of multiline highlights
	BoxT rune
	// The left border of the box, after line numbers. Also used for multiline highlights
	BoxL          rune
	HighlightLine rune // The left border of the box on lines with highlights
	// The character in the line number position on collapsed lines
	SkipLine rune
	// The left border of the box on collapsed lines without active highlights
	SkipLineL rune

	HighlightMultilineTL rune // The top left corner of multiline highlights
	HighlightMultilineBL rune // The bottom left corner of multiline highlights
	// The character used to underline the areas of the first line of a
	// multiline highlight before it begins.
	HighlightMultilineOffset rune
	// The left of multiline highlights on lines that are collapsed
	HighlightMultilineCollapsed rune
	CollapsedEllipsis           rune // The ellipsis used on collapsed lines

	ArrowT  rune // The top of underline arrows where the stem begins
	ArrowBL rune // Underline arrow curves

	ErrorDivider rune // Repeated to separate errors

	DetailIcon rune // Displayed to the left of each detail message
}

// DefaultCharacterSet returns a character set that uses default
// characters, which may be Unicode.
func DefaultCharacterSet() *CharacterSet {
	return &CharacterSet{
		HighlightSingle: '^',
		HighlightMulti:  '━', // '─'
		BoxTL:           '┌',
		BoxT:            '─',
		BoxL:            '│',
		HighlightLine:   '·',
		SkipLine:        '-', // ╌
		SkipLineL:       '├',

		HighlightMultilineTL:        '╭',
		HighlightMultilineBL:        '╰',
		HighlightMultilineOffset:    '·',
		HighlightMultilineCollapsed: '├',
		CollapsedEllipsis:           '·',

		ArrowT:  '┯',
		ArrowBL: '╰',

		ErrorDivider: '-',
		DetailIcon:   '▪',
	}
}

// ASCIICharacterSet returns a character set that uses ASCII characters.
func ASCIICharacterSet() *CharacterSet {
	return &CharacterSet{
		HighlightSingle: '^',
		HighlightMulti:  '~',
		BoxTL:           '-',
		BoxT:            '-',
		BoxL:            '|',
		HighlightLine:   '.',
		SkipLine:        '-',
		SkipLineL:       '+',

		HighlightMultilineTL:        'r',
		HighlightMultilineBL:        '\'',
		HighlightMultilineOffset:    '.',
		HighlightMultilineCollapsed: '}',
		CollapsedEllipsis:           '.',

		ArrowT:  ',',
		ArrowBL: '`',

		ErrorDivider: '-',

		DetailIcon: '*',
	}
}

// A TokenColorGenerator generates a map of ANSI color codes for each token
// type, for use in a [ColorPalette]. The map can be generated by calling
// [TokenColorGenerator.Generate].
//
// Each color is an ANSI color code or empty string.
type TokenColorGenerator struct {
	Ident    string
	Keyword  string
	Operator string
	Number   string
	String   string
	Boolean  string
	Comment  string
	Punct    string
	Illegal  string
}

// Generate returns a new map of ANSI color codes for each token type,
// based on the generator's fields. The returned map can be mutated.
// It is typically used in [ColorPalette.TokenColors].
func (gen *TokenColorGenerator) Generate() map[lexer.TokenType]string {
	colors := map[lexer.TokenType]string{
		lexer.Type:       gen.Keyword,
		lexer.Func:       gen.Keyword,
		lexer.String:     gen.String,
		lexer.Regex:      gen.String,
		lexer.Numeric:    gen.Number,
		lexer.Boolean:    gen.Boolean,
		lexer.Nil:        gen.Boolean,
		lexer.Illegal:    gen.Illegal,
		lexer.And:        gen.Operator,
		lexer.Or:         gen.Operator,
		lexer.Identifier: gen.Ident,
		lexer.Underscore: gen.Ident,
		// Comments
		lexer.BlockComment: gen.Comment,
		lexer.LineComment:  gen.Comment,
		lexer.Hashbang:     gen.Comment,
		// Punctuation
		lexer.Dot:                gen.Punct,
		lexer.Colon:              gen.Punct,
		lexer.Comma:              gen.Punct,
		lexer.LeftCurlyBrace:     gen.Punct,
		lexer.RightCurlyBrace:    gen.Punct,
		lexer.LeftParenthesis:    gen.Punct,
		lexer.RightParenthesis:   gen.Punct,
		lexer.LeftBracket:        gen.Punct,
		lexer.RightBracket:       gen.Punct,
		lexer.At:                 gen.Punct,
		lexer.HashLeftCurlyBrace: gen.Punct,
		lexer.Hash:               gen.Punct,
	}
	for _, op := range lexer.OperatorMap {
		if _, ok := colors[op]; !ok {
			colors[op] = gen.Operator
		}
	}
	for _, kw := range lexer.KeywordMap {
		if _, ok := colors[kw]; !ok {
			colors[kw] = gen.Keyword
		}
	}
	return colors
}
