version: '2'
formatters:
  enable:
    - gofumpt

run:
  build-tags:
    - goexperiment.jsonv2

linters:
  enable: [
    misspell, asasalint, bidichk, copyloopvar, exptostd,
    gosec, unconvert
    # errname, dupword, cyclop, exhaustive
  ]
  disable:
    - errcheck
    - unused
  settings:
    errcheck:
      exclude-functions:
        [fmt.Println, fmt.Fprintf, fmt.Printf, fmt.Fprintln, fmt.Fprint, os.File.Close]
    govet:
      disable:
        - composites
    exhaustive:
      default-signifies-exhaustive: true
      ignore-enum-types: "\\bTokenType\\b"
    gosec:
      severity: low
      confidence: low
      excludes:
        - G115
        - G104
        - G304
    staticcheck:
      checks:
        - '-ST1005'
