version: '2'
formatters:
  enable: []

run:
  build-tags:
    - goexperiment.jsonv2

linters:
  enable: [
      misspell,
      asasalint,
      bidichk,
      copyloopvar,
      exptostd,
      gosec,
      unconvert,
      usestdlibvars,
      usetesting,
      forbidigo,
      # errname, dupword, cyclop, exhaustive
    ]
  disable:
    - errcheck
    - unused
  settings:
    errcheck:
      exclude-functions:
        [fmt.Println, fmt.Fprintf, fmt.Printf, fmt.Fprintln, fmt.Fprint, os.File.Close]
    govet:
      disable:
        - composites
    exhaustive:
      default-signifies-exhaustive: true
      ignore-enum-types: "\\bTokenType\\b"
    gosec:
      severity: low
      confidence: low
      excludes:
        - G115
        - G104
        - G304
        - G305
        - G301
        - G302
        - G306
        - G307
        - G404
    forbidigo:
      exclude-godoc-examples: true
      analyze-types: true
      forbid:
        - pattern: ^fmt\.Print
          pkg: github.com/ProCode-Software/klar/internal/(lexer|parser|analysis)
    staticcheck:
      checks:
        - '-ST1005'
