#!/usr/bin/env bash
set -e

VERSION="0.0.1" # TODO: replace
LDFLAGS="-X 'github.com/ProCode-Software/klar/internal/version.KlarVersion=$VERSION'"
# ldflags: separate with another -X ...

# Generate files
go generate ./{cmd,internal,pkg}/...

# Clear console
if [[ "$1" = "-keep" ]]; then
    shift
else
    clear
fi

export GOEXPERIMENT=jsonv2 # Enable JSON v2

# Build binary if '-build' passed
case "$1" in
"-build")
    go build -ldflags="$LDFLAGS" -o klar ./cmd/klar
    ;;
"-time")
    shift
    time go run -ldflags="$LDFLAGS" ./cmd/klar $@
    ;;
*)
    go run -ldflags="$LDFLAGS" ./cmd/klar $@
    ;;
esac
exit $?
