#!/usr/bin/env bash
set -e

VERSION="0.0.2" # TODO: replace
LDFLAGS="-X 'github.com/ProCode-Software/klar/internal/version.KlarVersion=$VERSION'"
# ldflags: separate with another -X ...

# Generate files
go generate ./{cmd,internal,pkg}/...

# Clear console
clear

# Build binary if '-build' passed
case "$1" in
"-build")
    go build -ldflags="$LDFLAGS" -o klar ./cmd/klar
    ;;
"-time")
    shift
    time go run -ldflags="$LDFLAGS" ./cmd/klar $@
    ;;
*)
    go run -ldflags="$LDFLAGS" ./cmd/klar $@
    ;;
esac
exit $?
