#!/usr/bin/env bash
set -e

KLAR_DIR=$(dirname "$(realpath "${BASH_SOURCE[0]}")")
export KLAR_STD=$KLAR_DIR/std

VERSION="0.0.1"
LDFLAGS="-X 'github.com/ProCode-Software/klar/internal/cli.KlarVersion=$VERSION'"
# ldflags: separate with another -X ...

# Generate files
go generate "$KLAR_DIR"/internal/klarerrs

# Clear console
if [[ $1 == "-keep" ]]; then
    shift
elif [[ $1 != -build ]]; then
    clear
fi

export GOEXPERIMENT=jsonv2 # Enable JSON v2

# Build binary if '-build' passed
case "$1" in
"-build")
    go build -ldflags="$LDFLAGS" -o klar "$KLAR_DIR/cmd/klar"
    ;;
"-time")
    shift
    time go run -ldflags="$LDFLAGS" "$KLAR_DIR/cmd/klar" "$@"
    ;;
*)
    go run -ldflags="$LDFLAGS" "$KLAR_DIR/cmd/klar" "$@"
    ;;
esac
exit $?
