package jsir

type (
	ConstantDeclaration = BindingDeclaration
	VariableDeclaration = BindingDeclaration
)

type BindingDeclaration struct {
	Kind BindingKind
	Binding
}

// let x = 1, y = 2
type MultiBindingDeclaration struct {
	Kind     BindingKind
	Bindings []*Binding
}

type Binding struct {
	Variable Destructure
	Type     TSType     // TypeScript only
	Value    Expression // Can be nil if 'var'/'let'
}

type BindingKind int

const (
	LetBinding BindingKind = iota
	ConstBinding
	VarBinding   // Never generated by the Klar compiler
	UsingBinding // Newly added to ECMAScript. Not Baseline Widely Available as of 2026
)

type Destructure interface{ _destructure() }

type FunctionDeclaration struct {
	Name          string // Can be empty if used as an expression
	Params        []*FunctionParam
	VariadicParam *FunctionParam // If variadic (declared with '...')
	ReturnType    TSType
	Body          *Block // Can be nil in TypeScript
}

type FunctionParam struct {
	Name    string
	Type    TSType     // TypeScript only
	Default Expression // Can be nil
}

type ClassDeclaration struct {
	Name    string // Can be empty if expression
	Extends string // Can be empty
	Fields  []*BindingDeclaration
	Methods []*FunctionDeclaration // Includes 'constructor'
	// TODO: Static fields/methods, getters/setters, 'implements' for TS?
}

// JS has several types of 'export' statements. We will try to separate them
// into different IR nodes for efficiency.
// See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export

// ExportModifier exports a declaration statement.
//
//	export default function ...
//	export const ...
type ExportModifier struct {
	Default     bool
	Declaration Statement
}
