package jsir

type (
	ConstantDeclaration = BindingDeclaration
	VariableDeclaration = BindingDeclaration
)

type BindingDeclaration struct {
	Kind     BindingKind
	Variable Destructure
	Type     TSType     // TypeScript only
	Value    Expression // Can be nil if 'var'/'let'
}

type BindingKind int

const (
	LetBinding BindingKind = iota
	ConstBinding
	VarBinding   // Never generated by the Klar compiler
	UsingBinding // Newly added to ECMAScript. Not Baseline Widely Available as of 2026
)

type Destructure interface{ _destructure() }

type FunctionDeclaration struct {
	Name          string // Can be empty if used as an expression
	Params        []*FunctionParam
	VariadicParam *FunctionParam // If variadic (declared with '...')
	ReturnType    TSType
	Body          *Block // Can be nil in TypeScript
}

type FunctionParam struct {
	Name    string
	Type    TSType     // TypeScript only
	Default Expression // Can be nil
}
