// Code generated by "stringer -type=Operator -linecomment"; DO NOT EDIT.

package jsir

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpEqual-1]
	_ = x[OpNotEqual-2]
	_ = x[OpStrictEqual-3]
	_ = x[OpStrictNotEqual-4]
	_ = x[OpGreaterThan-5]
	_ = x[OpLessThan-6]
	_ = x[OpGreaterEqual-7]
	_ = x[OpLessEqual-8]
	_ = x[OpIn-9]
	_ = x[OpInstanceof-10]
	_ = x[OpPlus-11]
	_ = x[OpMinus-12]
	_ = x[OpTimes-13]
	_ = x[OpDivide-14]
	_ = x[OpRemainder-15]
	_ = x[OpIncrement-16]
	_ = x[OpDecrement-17]
	_ = x[OpExponent-18]
	_ = x[OpBitwiseAnd-19]
	_ = x[OpBitwiseOr-20]
	_ = x[OpBitwiseXOr-21]
	_ = x[OpBitwiseNot-22]
	_ = x[OpShiftLeft-23]
	_ = x[OpShiftRight-24]
	_ = x[OpUShiftRight-25]
	_ = x[OpLogicalAnd-26]
	_ = x[OpLogicalOr-27]
	_ = x[OpNullCoalesce-28]
	_ = x[OpLogicalNot-29]
	_ = x[OpPlusEqual-30]
	_ = x[OpMinusEqual-31]
	_ = x[OpTimesEqual-32]
	_ = x[OpDivideEqual-33]
	_ = x[OpRemainderEqual-34]
	_ = x[OpExponentEqual-35]
	_ = x[OpShiftLeftEqual-36]
	_ = x[OpShiftRightEqual-37]
	_ = x[OpUShiftRightEqual-38]
	_ = x[OpBitwiseAndEqual-39]
	_ = x[OpBitwiseOrEqual-40]
	_ = x[OpBitwiseXOrEqual-41]
	_ = x[OpLogicalAndEqual-42]
	_ = x[OpLogicalOrEqual-43]
	_ = x[OpNullCoalesceEqual-44]
	_ = x[OpAwait-45]
	_ = x[OpDelete-46]
	_ = x[OpVoid-47]
	_ = x[OpTypeof-48]
	_ = x[OpNew-49]
	_ = x[OpYield-50]
	_ = x[OpYieldStar-51]
}

const _Operator_name = "==!====!==><>=<=ininstanceof+-*/%++--**&|^~<<>>>>>&&||??!+=-=*=/=%=**=<<=>>=>>>=&=|=^=&&=||=??=awaitdeletevoidtypeofnewyieldyield*"

var _Operator_index = [...]uint8{0, 2, 4, 7, 10, 11, 12, 14, 16, 18, 28, 29, 30, 31, 32, 33, 35, 37, 39, 40, 41, 42, 43, 45, 47, 50, 52, 54, 56, 57, 59, 61, 63, 65, 67, 70, 73, 76, 80, 82, 84, 86, 89, 92, 95, 100, 106, 110, 116, 119, 124, 130}

func (i Operator) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_Operator_index)-1 {
		return "Operator(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Operator_name[_Operator_index[idx]:_Operator_index[idx+1]]
}
