// Code generated by astgen; DO NOT EDIT.

package ast

import (
	"github.com/ProCode-Software/klar/internal/lexer"
	"github.com/ProCode-Software/klar/internal/ranges"
)

func (e Program) GetRange() ranges.Range { return e.BaseNode.Range }
func (e Program) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e StringLiteral) GetRange() ranges.Range { return e.BaseNode.Range }
func (e StringLiteral) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e FloatLiteral) GetRange() ranges.Range { return e.BaseNode.Range }
func (e FloatLiteral) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e IntegerLiteral) GetRange() ranges.Range { return e.BaseNode.Range }
func (e IntegerLiteral) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e BooleanLiteral) GetRange() ranges.Range { return e.BaseNode.Range }
func (e BooleanLiteral) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e NilLiteral) GetRange() ranges.Range { return e.BaseNode.Range }
func (e NilLiteral) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e ExpressionStatement) GetRange() ranges.Range { return e.BaseNode.Range }
func (e ExpressionStatement) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e BinaryExpression) GetRange() ranges.Range { return e.BaseNode.Range }
func (e BinaryExpression) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e VariableDeclaration) GetRange() ranges.Range { return e.BaseNode.Range }
func (e VariableDeclaration) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e AssignmentStatement) GetRange() ranges.Range { return e.BaseNode.Range }
func (e AssignmentStatement) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e UnaryExpression) GetRange() ranges.Range { return e.BaseNode.Range }
func (e UnaryExpression) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e Symbol) GetRange() ranges.Range { return e.BaseNode.Range }
func (e Symbol) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e ImportStatement) GetRange() ranges.Range { return e.BaseNode.Range }
func (e ImportStatement) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e TypeAnnotation) GetRange() ranges.Range { return e.BaseNode.Range }
func (e TypeAnnotation) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e EnumDeclaration) GetRange() ranges.Range { return e.BaseNode.Range }
func (e EnumDeclaration) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e StructDeclaration) GetRange() ranges.Range { return e.BaseNode.Range }
func (e StructDeclaration) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e TypeAliasDeclaration) GetRange() ranges.Range { return e.BaseNode.Range }
func (e TypeAliasDeclaration) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e StructField) GetRange() ranges.Range { return e.BaseNode.Range }
func (e StructField) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e MapLiteral) GetRange() ranges.Range { return e.BaseNode.Range }
func (e MapLiteral) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e TupleLiteral) GetRange() ranges.Range { return e.BaseNode.Range }
func (e TupleLiteral) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e ReturnStatement) GetRange() ranges.Range { return e.BaseNode.Range }
func (e ReturnStatement) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e FunctionDeclaration) GetRange() ranges.Range { return e.BaseNode.Range }
func (e FunctionDeclaration) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e NextStatement) GetRange() ranges.Range { return e.BaseNode.Range }
func (e NextStatement) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e ListLiteral) GetRange() ranges.Range { return e.BaseNode.Range }
func (e ListLiteral) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e IndexExpression) GetRange() ranges.Range { return e.BaseNode.Range }
func (e IndexExpression) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e CallExpression) GetRange() ranges.Range { return e.BaseNode.Range }
func (e CallExpression) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e EnumLiteral) GetRange() ranges.Range { return e.BaseNode.Range }
func (e EnumLiteral) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e ForStatement) GetRange() ranges.Range { return e.BaseNode.Range }
func (e ForStatement) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e UpdateStatement) GetRange() ranges.Range { return e.BaseNode.Range }
func (e UpdateStatement) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e Discard) GetRange() ranges.Range { return e.BaseNode.Range }
func (e Discard) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e WhenExpression) GetRange() ranges.Range { return e.BaseNode.Range }
func (e WhenExpression) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e LambdaExpression) GetRange() ranges.Range { return e.BaseNode.Range }
func (e LambdaExpression) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e TypeTuple) GetRange() ranges.Range { return e.BaseNode.Range }
func (e TypeTuple) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e Attribute) GetRange() ranges.Range { return e.BaseNode.Range }
func (e Attribute) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e RangeExpression) GetRange() ranges.Range { return e.BaseNode.Range }
func (e RangeExpression) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e RestExpression) GetRange() ranges.Range { return e.BaseNode.Range }
func (e RestExpression) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e PipelineExpression) GetRange() ranges.Range { return e.BaseNode.Range }
func (e PipelineExpression) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e BadExpression) GetRange() ranges.Range { return e.BaseNode.Range }
func (e BadExpression) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e SliceExpression) GetRange() ranges.Range { return e.BaseNode.Range }
func (e SliceExpression) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e ParenExpression) GetRange() ranges.Range { return e.BaseNode.Range }
func (e ParenExpression) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e InterfaceDeclaration) GetRange() ranges.Range { return e.BaseNode.Range }
func (e InterfaceDeclaration) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e Comment) GetRange() ranges.Range { return e.BaseNode.Range }
func (e Comment) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e MethodType) GetRange() ranges.Range { return e.BaseNode.Range }
func (e MethodType) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e TypePair) GetRange() ranges.Range { return e.BaseNode.Range }
func (e TypePair) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e BreakStatement) GetRange() ranges.Range { return e.BaseNode.Range }
func (e BreakStatement) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e RegexLiteral) GetRange() ranges.Range { return e.BaseNode.Range }
func (e RegexLiteral) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e EnumItem) GetRange() ranges.Range { return e.BaseNode.Range }
func (e EnumItem) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e VersionLiteral) GetRange() ranges.Range { return e.BaseNode.Range }
func (e VersionLiteral) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e PrimitiveType) GetRange() ranges.Range { return e.BaseNode.Range }
func (e PrimitiveType) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e TypeAlias) GetRange() ranges.Range { return e.BaseNode.Range }
func (e TypeAlias) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e OptionalType) GetRange() ranges.Range { return e.BaseNode.Range }
func (e OptionalType) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e ListType) GetRange() ranges.Range { return e.BaseNode.Range }
func (e ListType) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e RestType) GetRange() ranges.Range { return e.BaseNode.Range }
func (e RestType) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e TupleType) GetRange() ranges.Range { return e.BaseNode.Range }
func (e TupleType) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e FunctionType) GetRange() ranges.Range { return e.BaseNode.Range }
func (e FunctionType) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e GenericType) GetRange() ranges.Range { return e.BaseNode.Range }
func (e GenericType) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
func (e UnionType) GetRange() ranges.Range { return e.BaseNode.Range }
func (e UnionType) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
