// Code generated by asttempl. DO NOT EDIT.
package ast

func (a *AssertExpression) Equal(b2 Node) bool {
	b, ok := b2.(*AssertExpression)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if a.Expression != nil && b.Expression != nil && !a.Expression.Equal(b.Expression) {
		return false
	}
	return true
}

func (a *AssignableTuple) Equal(b2 Node) bool {
	b, ok := b2.(*AssignableTuple)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if !equalSlice(a.Values, b.Values) {
		return false
	}
	return true
}

func (a *AssignableTypePair) Equal(b2 Node) bool {
	b, ok := b2.(*AssignableTypePair)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if !equalSlice(a.Keys, b.Keys) {
		return false
	}
	if a.Type != nil && b.Type != nil && !a.Type.Equal(b.Type) {
		return false
	}
	if a.Value != nil && b.Value != nil && !a.Value.Equal(b.Value) {
		return false
	}
	return true
}

func (a *AssignableVars) Equal(b2 Node) bool {
	b, ok := b2.(*AssignableVars)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if !equalSlice(a.Values, b.Values) {
		return false
	}
	return true
}

func (a *AssignmentStatement) Equal(b2 Node) bool {
	b, ok := b2.(*AssignmentStatement)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if !equalSlice(a.Assignee, b.Assignee) {
		return false
	}
	if !a.Operator.Equal(b.Operator) {
		return false
	}
	if !equalSlice(a.Values, b.Values) {
		return false
	}
	return true
}

func (a *Attribute) Equal(b2 Node) bool {
	b, ok := b2.(*Attribute)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if !a.Decorator.Equal(b.Decorator) {
		return false
	}
	if !equalSlice(a.Args, b.Args) {
		return false
	}
	return true
}

func (a *AwaitExpression) Equal(b2 Node) bool {
	b, ok := b2.(*AwaitExpression)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if a.Expression != nil && b.Expression != nil && !a.Expression.Equal(b.Expression) {
		return false
	}
	return true
}

func (a *BadExpression) Equal(b2 Node) bool {
	b, ok := b2.(*BadExpression)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if a.Value != nil && b.Value != nil && !a.Value.Equal(b.Value) {
		return false
	}
	if a.Token != b.Token {
		return false
	}
	return true
}

func (a *BinaryExpression) Equal(b2 Node) bool {
	b, ok := b2.(*BinaryExpression)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if a.Left != nil && b.Left != nil && !a.Left.Equal(b.Left) {
		return false
	}
	if a.Right != nil && b.Right != nil && !a.Right.Equal(b.Right) {
		return false
	}
	if !a.Operator.Equal(b.Operator) {
		return false
	}
	return true
}

func (a *Block) Equal(b2 Node) bool {
	b, ok := b2.(*Block)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if !equalSlice(a.Body, b.Body) {
		return false
	}
	return true
}

func (a *BooleanLiteral) Equal(b2 Node) bool {
	b, ok := b2.(*BooleanLiteral)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if a.Value != b.Value {
		return false
	}
	return true
}

func (a *CallExpression) Equal(b2 Node) bool {
	b, ok := b2.(*CallExpression)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if a.Callee != nil && b.Callee != nil && !a.Callee.Equal(b.Callee) {
		return false
	}
	if !equalSlice(a.Args, b.Args) {
		return false
	}
	return true
}

func (a *CallParam) Equal(b2 Node) bool {
	b, ok := b2.(*CallParam)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if !a.Label.Equal(b.Label) {
		return false
	}
	if a.Value != nil && b.Value != nil && !a.Value.Equal(b.Value) {
		return false
	}
	if a.Shorthand != b.Shorthand {
		return false
	}
	return true
}

func (a *Comment) Equal(b2 Node) bool {
	b, ok := b2.(*Comment)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if a.Type != b.Type {
		return false
	}
	if a.Value != b.Value {
		return false
	}
	return true
}

func (a *Discard) Equal(b2 Node) bool {
	b, ok := b2.(*Discard)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	return true
}

func (a *EnumDeclaration) Equal(b2 Node) bool {
	b, ok := b2.(*EnumDeclaration)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if !a.Identifier.Equal(b.Identifier) {
		return false
	}
	if !equalSlice(a.Generics, b.Generics) {
		return false
	}
	if !equalSlice(a.Inherited, b.Inherited) {
		return false
	}
	if a.ValueType != nil && b.ValueType != nil && !a.ValueType.Equal(b.ValueType) {
		return false
	}
	if !equalSlice(a.Values, b.Values) {
		return false
	}
	return true
}

func (a *EnumItem) Equal(b2 Node) bool {
	b, ok := b2.(*EnumItem)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if !a.Identifier.Equal(b.Identifier) {
		return false
	}
	if a.Value != nil && b.Value != nil && !a.Value.Equal(b.Value) {
		return false
	}
	if !equalSlice(a.Parameters, b.Parameters) {
		return false
	}
	if !equalSlice(a.Attributes, b.Attributes) {
		return false
	}
	return true
}

func (a *EnumLiteral) Equal(b2 Node) bool {
	b, ok := b2.(*EnumLiteral)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if !a.Name.Equal(b.Name) {
		return false
	}
	return true
}

func (a *ExpressionStatement) Equal(b2 Node) bool {
	b, ok := b2.(*ExpressionStatement)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if a.Expression != nil && b.Expression != nil && !a.Expression.Equal(b.Expression) {
		return false
	}
	return true
}

func (a *FloatLiteral) Equal(b2 Node) bool {
	b, ok := b2.(*FloatLiteral)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if a.Value != b.Value {
		return false
	}
	if a.Source != b.Source {
		return false
	}
	if a.Exponent != b.Exponent {
		return false
	}
	if a.Separator != b.Separator {
		return false
	}
	return true
}

func (a *ForExpression) Equal(b2 Node) bool {
	b, ok := b2.(*ForExpression)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if !equalSlice(a.Variables, b.Variables) {
		return false
	}
	if a.Iterator != nil && b.Iterator != nil && !a.Iterator.Equal(b.Iterator) {
		return false
	}
	if !a.Operator.Equal(b.Operator) {
		return false
	}
	if a.Value != nil && b.Value != nil && !a.Value.Equal(b.Value) {
		return false
	}
	if a.Block != nil && b.Block != nil && !a.Block.Equal(b.Block) {
		return false
	}
	return true
}

func (a *ForStatement) Equal(b2 Node) bool {
	b, ok := b2.(*ForStatement)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if !equalSlice(a.Variables, b.Variables) {
		return false
	}
	if a.Expression != nil && b.Expression != nil && !a.Expression.Equal(b.Expression) {
		return false
	}
	if a.Body != nil && b.Body != nil && !a.Body.Equal(b.Body) {
		return false
	}
	return true
}

func (a *FuncAliasDeclaration) Equal(b2 Node) bool {
	b, ok := b2.(*FuncAliasDeclaration)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if !a.Struct.Equal(b.Struct) {
		return false
	}
	if !a.Identifier.Equal(b.Identifier) {
		return false
	}
	if a.Target != nil && b.Target != nil && !a.Target.Equal(b.Target) {
		return false
	}
	return true
}

func (a *FunctionDeclaration) Equal(b2 Node) bool {
	b, ok := b2.(*FunctionDeclaration)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if !a.Identifier.Equal(b.Identifier) {
		return false
	}
	if !a.Struct.Equal(b.Struct) {
		return false
	}
	if !a.SelfName.Equal(b.SelfName) {
		return false
	}
	if !equalSlice(a.GenericParams, b.GenericParams) {
		return false
	}
	if !equalSlice(a.Parameters, b.Parameters) {
		return false
	}
	if a.ReturnType != nil && b.ReturnType != nil && !a.ReturnType.Equal(b.ReturnType) {
		return false
	}
	if a.Body != nil && b.Body != nil && !a.Body.Equal(b.Body) {
		return false
	}
	if a.Expression != nil && b.Expression != nil && !a.Expression.Equal(b.Expression) {
		return false
	}
	return true
}

func (a *FunctionParam) Equal(b2 Node) bool {
	b, ok := b2.(*FunctionParam)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if !equalSlice(a.Names, b.Names) {
		return false
	}
	if a.Type != nil && b.Type != nil && !a.Type.Equal(b.Type) {
		return false
	}
	if a.Default != nil && b.Default != nil && !a.Default.Equal(b.Default) {
		return false
	}
	return true
}

func (a *FunctionType) Equal(b2 Node) bool {
	b, ok := b2.(*FunctionType)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if a.Parameters != nil && b.Parameters != nil && !a.Parameters.Equal(b.Parameters) {
		return false
	}
	if a.ReturnType != nil && b.ReturnType != nil && !a.ReturnType.Equal(b.ReturnType) {
		return false
	}
	return true
}

func (a *GenericType) Equal(b2 Node) bool {
	b, ok := b2.(*GenericType)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if a.Name != nil && b.Name != nil && !a.Name.Equal(b.Name) {
		return false
	}
	if !equalSlice(a.Parameters, b.Parameters) {
		return false
	}
	return true
}

func (a *GoExpression) Equal(b2 Node) bool {
	b, ok := b2.(*GoExpression)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if a.Expression != nil && b.Expression != nil && !a.Expression.Equal(b.Expression) {
		return false
	}
	if a.Body != nil && b.Body != nil && !a.Body.Equal(b.Body) {
		return false
	}
	return true
}

func (a *IdentifierPair) Equal(b2 Node) bool {
	b, ok := b2.(*IdentifierPair)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if !a.Label.Equal(b.Label) {
		return false
	}
	if !a.Name.Equal(b.Name) {
		return false
	}
	return true
}

func (a *ImportStatement) Equal(b2 Node) bool {
	b, ok := b2.(*ImportStatement)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if !a.Alias.Equal(b.Alias) {
		return false
	}
	if !equalSlice(a.Module, b.Module) {
		return false
	}
	if a.Wildcard != b.Wildcard {
		return false
	}
	if !equalSlice(a.UnqualifiedImports, b.UnqualifiedImports) {
		return false
	}
	return true
}

func (a *IndexExpression) Equal(b2 Node) bool {
	b, ok := b2.(*IndexExpression)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if a.Object != nil && b.Object != nil && !a.Object.Equal(b.Object) {
		return false
	}
	if a.Property != nil && b.Property != nil && !a.Property.Equal(b.Property) {
		return false
	}
	if a.Computed != b.Computed {
		return false
	}
	return true
}

func (a *IntegerLiteral) Equal(b2 Node) bool {
	b, ok := b2.(*IntegerLiteral)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if a.Format != b.Format {
		return false
	}
	if a.Value != b.Value {
		return false
	}
	if a.Source != b.Source {
		return false
	}
	if a.Separator != b.Separator {
		return false
	}
	return true
}

func (a *InterfaceDeclaration) Equal(b2 Node) bool {
	b, ok := b2.(*InterfaceDeclaration)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if !a.Identifier.Equal(b.Identifier) {
		return false
	}
	if !equalSlice(a.InheritedTypes, b.InheritedTypes) {
		return false
	}
	if a.Tag != b.Tag {
		return false
	}
	if !equalSlice(a.Items, b.Items) {
		return false
	}
	return true
}

func (a *InterfaceItem) Equal(b2 Node) bool {
	b, ok := b2.(*InterfaceItem)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if a.TypePair != nil && b.TypePair != nil && !a.TypePair.Equal(b.TypePair) {
		return false
	}
	if !equalSlice(a.Attributes, b.Attributes) {
		return false
	}
	return true
}

func (a *LambdaExpression) Equal(b2 Node) bool {
	b, ok := b2.(*LambdaExpression)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if !equalSlice(a.Params, b.Params) {
		return false
	}
	if a.InParen != b.InParen {
		return false
	}
	if a.Block != nil && b.Block != nil && !a.Block.Equal(b.Block) {
		return false
	}
	if a.Expr != nil && b.Expr != nil && !a.Expr.Equal(b.Expr) {
		return false
	}
	return true
}

func (a *ListCastExpression) Equal(b2 Node) bool {
	b, ok := b2.(*ListCastExpression)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if a.Type != nil && b.Type != nil && !a.Type.Equal(b.Type) {
		return false
	}
	if !equalSlice(a.Args, b.Args) {
		return false
	}
	return true
}

func (a *ListDestructure) Equal(b2 Node) bool {
	b, ok := b2.(*ListDestructure)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if a.Tuple != b.Tuple {
		return false
	}
	if !equalSlice(a.Values, b.Values) {
		return false
	}
	return true
}

func (a *ListLiteral) Equal(b2 Node) bool {
	b, ok := b2.(*ListLiteral)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if !equalSlice(a.Items, b.Items) {
		return false
	}
	return true
}

func (a *ListType) Equal(b2 Node) bool {
	b, ok := b2.(*ListType)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if a.Value != nil && b.Value != nil && !a.Value.Equal(b.Value) {
		return false
	}
	return true
}

func (a *MapItem) Equal(b2 Node) bool {
	b, ok := b2.(*MapItem)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if !equalSlice(a.Keys, b.Keys) {
		return false
	}
	if a.Value != nil && b.Value != nil && !a.Value.Equal(b.Value) {
		return false
	}
	if a.Rest != b.Rest {
		return false
	}
	if a.Shorthand != b.Shorthand {
		return false
	}
	return true
}

func (a *MapLiteral) Equal(b2 Node) bool {
	b, ok := b2.(*MapLiteral)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if !equalSlice(a.Entries, b.Entries) {
		return false
	}
	return true
}

func (a *MapType) Equal(b2 Node) bool {
	b, ok := b2.(*MapType)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if a.Key != nil && b.Key != nil && !a.Key.Equal(b.Key) {
		return false
	}
	if a.Value != nil && b.Value != nil && !a.Value.Equal(b.Value) {
		return false
	}
	return true
}

func (a *MethodParam) Equal(b2 Node) bool {
	b, ok := b2.(*MethodParam)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if !equalSlice(a.Names, b.Names) {
		return false
	}
	if a.Type != nil && b.Type != nil && !a.Type.Equal(b.Type) {
		return false
	}
	return true
}

func (a *MethodType) Equal(b2 Node) bool {
	b, ok := b2.(*MethodType)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if a.ReturnType != nil && b.ReturnType != nil && !a.ReturnType.Equal(b.ReturnType) {
		return false
	}
	if !equalSlice(a.Parameters, b.Parameters) {
		return false
	}
	return true
}

func (a *NextStatement) Equal(b2 Node) bool {
	b, ok := b2.(*NextStatement)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if a.Loop != b.Loop {
		return false
	}
	return true
}

func (a *NilLiteral) Equal(b2 Node) bool {
	b, ok := b2.(*NilLiteral)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if a.Shorthand != b.Shorthand {
		return false
	}
	return true
}

func (a *ObjectDestructure) Equal(b2 Node) bool {
	b, ok := b2.(*ObjectDestructure)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if !equalSlice(a.Values, b.Values) {
		return false
	}
	return true
}

func (a *ObjectDestructureEntry) Equal(b2 Node) bool {
	b, ok := b2.(*ObjectDestructureEntry)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if !a.Alias.Equal(b.Alias) {
		return false
	}
	if a.Object != nil && b.Object != nil && !a.Object.Equal(b.Object) {
		return false
	}
	if a.Index != nil && b.Index != nil && !a.Index.Equal(b.Index) {
		return false
	}
	if a.Default != nil && b.Default != nil && !a.Default.Equal(b.Default) {
		return false
	}
	return true
}

func (a *ObjectPipeline) Equal(b2 Node) bool {
	b, ok := b2.(*ObjectPipeline)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if a.Object != nil && b.Object != nil && !a.Object.Equal(b.Object) {
		return false
	}
	if !equalSlice(a.Steps, b.Steps) {
		return false
	}
	return true
}

func (a *OpaqueDeclaration) Equal(b2 Node) bool {
	b, ok := b2.(*OpaqueDeclaration)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if a.Declaration != nil && b.Declaration != nil && !a.Declaration.Equal(b.Declaration) {
		return false
	}
	return true
}

func (a *OptionalType) Equal(b2 Node) bool {
	b, ok := b2.(*OptionalType)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if a.Value != nil && b.Value != nil && !a.Value.Equal(b.Value) {
		return false
	}
	return true
}

func (a *Pair) Equal(b2 Node) bool {
	b, ok := b2.(*Pair)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if a.Key != nil && b.Key != nil && !a.Key.Equal(b.Key) {
		return false
	}
	if a.Value != nil && b.Value != nil && !a.Value.Equal(b.Value) {
		return false
	}
	return true
}

func (a *ParenExpression) Equal(b2 Node) bool {
	b, ok := b2.(*ParenExpression)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if a.Expression != nil && b.Expression != nil && !a.Expression.Equal(b.Expression) {
		return false
	}
	return true
}

func (a *ParenType) Equal(b2 Node) bool {
	b, ok := b2.(*ParenType)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if a.Type != nil && b.Type != nil && !a.Type.Equal(b.Type) {
		return false
	}
	return true
}

func (a *PipelineExpression) Equal(b2 Node) bool {
	b, ok := b2.(*PipelineExpression)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if !equalSlice(a.Steps, b.Steps) {
		return false
	}
	return true
}

func (a *PrimitiveType) Equal(b2 Node) bool {
	b, ok := b2.(*PrimitiveType)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if a.Primitive != b.Primitive {
		return false
	}
	return true
}

func (a *Program) Equal(b2 Node) bool {
	b, ok := b2.(*Program)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if !equalSlice(a.Body, b.Body) {
		return false
	}
	if !equalSlice(a.Comments, b.Comments) {
		return false
	}
	return true
}

func (a *PublicDeclaration) Equal(b2 Node) bool {
	b, ok := b2.(*PublicDeclaration)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if a.Declaration != nil && b.Declaration != nil && !a.Declaration.Equal(b.Declaration) {
		return false
	}
	return true
}

func (a *QualifiedTypeAlias) Equal(b2 Node) bool {
	b, ok := b2.(*QualifiedTypeAlias)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if !a.Namespace.Equal(b.Namespace) {
		return false
	}
	if !a.Identifier.Equal(b.Identifier) {
		return false
	}
	return true
}

func (a *RangeExpression) Equal(b2 Node) bool {
	b, ok := b2.(*RangeExpression)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if a.From != nil && b.From != nil && !a.From.Equal(b.From) {
		return false
	}
	if a.To != nil && b.To != nil && !a.To.Equal(b.To) {
		return false
	}
	if a.Step != nil && b.Step != nil && !a.Step.Equal(b.Step) {
		return false
	}
	if !a.Operator.Equal(b.Operator) {
		return false
	}
	return true
}

func (a *RegexLiteral) Equal(b2 Node) bool {
	b, ok := b2.(*RegexLiteral)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if a.Source != b.Source {
		return false
	}
	if !equalSlice(a.Flags, b.Flags) {
		return false
	}
	if a.Multiline != b.Multiline {
		return false
	}
	return true
}

func (a *RelationalExpression) Equal(b2 Node) bool {
	b, ok := b2.(*RelationalExpression)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if !equalSlice(a.Expressions, b.Expressions) {
		return false
	}
	if !equalSlice(a.Operators, b.Operators) {
		return false
	}
	return true
}

func (a *RestExpression) Equal(b2 Node) bool {
	b, ok := b2.(*RestExpression)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if a.Expression != nil && b.Expression != nil && !a.Expression.Equal(b.Expression) {
		return false
	}
	return true
}

func (a *RestType) Equal(b2 Node) bool {
	b, ok := b2.(*RestType)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if a.Value != nil && b.Value != nil && !a.Value.Equal(b.Value) {
		return false
	}
	return true
}

func (a *ReturnStatement) Equal(b2 Node) bool {
	b, ok := b2.(*ReturnStatement)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if a.Value != nil && b.Value != nil && !a.Value.Equal(b.Value) {
		return false
	}
	return true
}

func (a *SliceExpression) Equal(b2 Node) bool {
	b, ok := b2.(*SliceExpression)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if a.Object != nil && b.Object != nil && !a.Object.Equal(b.Object) {
		return false
	}
	if a.From != nil && b.From != nil && !a.From.Equal(b.From) {
		return false
	}
	if a.To != nil && b.To != nil && !a.To.Equal(b.To) {
		return false
	}
	if !a.Operator.Equal(b.Operator) {
		return false
	}
	return true
}

func (a *StopStatement) Equal(b2 Node) bool {
	b, ok := b2.(*StopStatement)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if a.Loop != b.Loop {
		return false
	}
	return true
}

func (a *StringLiteral) Equal(b2 Node) bool {
	b, ok := b2.(*StringLiteral)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if a.QuoteStyle != b.QuoteStyle {
		return false
	}
	if a.Content != b.Content {
		return false
	}
	if !equalSlice(a.Fragments, b.Fragments) {
		return false
	}
	return true
}

func (a *StringTypeMatch) Equal(b2 Node) bool {
	b, ok := b2.(*StringTypeMatch)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if !a.Name.Equal(b.Name) {
		return false
	}
	if a.Type != nil && b.Type != nil && !a.Type.Equal(b.Type) {
		return false
	}
	return true
}

func (a *StructDeclaration) Equal(b2 Node) bool {
	b, ok := b2.(*StructDeclaration)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if !a.Identifier.Equal(b.Identifier) {
		return false
	}
	if !equalSlice(a.InheritedTypes, b.InheritedTypes) {
		return false
	}
	if !equalSlice(a.Fields, b.Fields) {
		return false
	}
	return true
}

func (a *StructDotInit) Equal(b2 Node) bool {
	b, ok := b2.(*StructDotInit)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if !equalSlice(a.Params, b.Params) {
		return false
	}
	return true
}

func (a *StructField) Equal(b2 Node) bool {
	b, ok := b2.(*StructField)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if !equalSlice(a.Names, b.Names) {
		return false
	}
	if a.Type != nil && b.Type != nil && !a.Type.Equal(b.Type) {
		return false
	}
	if a.Constant != b.Constant {
		return false
	}
	if a.Value != nil && b.Value != nil && !a.Value.Equal(b.Value) {
		return false
	}
	if !equalSlice(a.Attributes, b.Attributes) {
		return false
	}
	return true
}

func (a *Symbol) Equal(b2 Node) bool {
	b, ok := b2.(*Symbol)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if a.Identifier != b.Identifier {
		return false
	}
	return true
}

func (a *TryExpression) Equal(b2 Node) bool {
	b, ok := b2.(*TryExpression)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if a.Expression != nil && b.Expression != nil && !a.Expression.Equal(b.Expression) {
		return false
	}
	return true
}

func (a *TupleLiteral) Equal(b2 Node) bool {
	b, ok := b2.(*TupleLiteral)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if !equalSlice(a.Values, b.Values) {
		return false
	}
	return true
}

func (a *TupleType) Equal(b2 Node) bool {
	b, ok := b2.(*TupleType)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if !equalSlice(a.Values, b.Values) {
		return false
	}
	if a.Single != b.Single {
		return false
	}
	return true
}

func (a *TypeAlias) Equal(b2 Node) bool {
	b, ok := b2.(*TypeAlias)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if a.Identifier != b.Identifier {
		return false
	}
	return true
}

func (a *TypeAliasDeclaration) Equal(b2 Node) bool {
	b, ok := b2.(*TypeAliasDeclaration)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if !a.Identifier.Equal(b.Identifier) {
		return false
	}
	if a.Type != nil && b.Type != nil && !a.Type.Equal(b.Type) {
		return false
	}
	return true
}

func (a *TypeAnnotation) Equal(b2 Node) bool {
	b, ok := b2.(*TypeAnnotation)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if a.Variable != nil && b.Variable != nil && !a.Variable.Equal(b.Variable) {
		return false
	}
	if a.Type != nil && b.Type != nil && !a.Type.Equal(b.Type) {
		return false
	}
	return true
}

func (a *TypePair) Equal(b2 Node) bool {
	b, ok := b2.(*TypePair)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if !equalSlice(a.Keys, b.Keys) {
		return false
	}
	if a.Value != nil && b.Value != nil && !a.Value.Equal(b.Value) {
		return false
	}
	return true
}

func (a *UnaryExpression) Equal(b2 Node) bool {
	b, ok := b2.(*UnaryExpression)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if !a.Operator.Equal(b.Operator) {
		return false
	}
	if a.Right != nil && b.Right != nil && !a.Right.Equal(b.Right) {
		return false
	}
	return true
}

func (a *UnionType) Equal(b2 Node) bool {
	b, ok := b2.(*UnionType)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if !equalSlice(a.Options, b.Options) {
		return false
	}
	return true
}

func (a *UpdateStatement) Equal(b2 Node) bool {
	b, ok := b2.(*UpdateStatement)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if a.Left != nil && b.Left != nil && !a.Left.Equal(b.Left) {
		return false
	}
	if !a.Operator.Equal(b.Operator) {
		return false
	}
	return true
}

func (a *VariableDeclaration) Equal(b2 Node) bool {
	b, ok := b2.(*VariableDeclaration)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if !equalSlice(a.Variables, b.Variables) {
		return false
	}
	if !equalSlice(a.Values, b.Values) {
		return false
	}
	if a.ExplicitType != nil && b.ExplicitType != nil && !a.ExplicitType.Equal(b.ExplicitType) {
		return false
	}
	return true
}

func (a *VersionLiteral) Equal(b2 Node) bool {
	b, ok := b2.(*VersionLiteral)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if a.Version != b.Version {
		return false
	}
	return true
}

func (a *WhenCanCase) Equal(b2 Node) bool {
	b, ok := b2.(*WhenCanCase)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if !a.Operator.Equal(b.Operator) {
		return false
	}
	if a.Type != nil && b.Type != nil && !a.Type.Equal(b.Type) {
		return false
	}
	if !equalSlice(a.Params, b.Params) {
		return false
	}
	return true
}

func (a *WhenCase) Equal(b2 Node) bool {
	b, ok := b2.(*WhenCase)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if !equalSlice(a.Options, b.Options) {
		return false
	}
	if a.Guard != nil && b.Guard != nil && !a.Guard.Equal(b.Guard) {
		return false
	}
	if a.Braces != b.Braces {
		return false
	}
	if a.Body != nil && b.Body != nil && !a.Body.Equal(b.Body) {
		return false
	}
	return true
}

func (a *WhenExpression) Equal(b2 Node) bool {
	b, ok := b2.(*WhenExpression)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if !equalSlice(a.Subjects, b.Subjects) {
		return false
	}
	if !equalSlice(a.Cases, b.Cases) {
		return false
	}
	return true
}

func (a *WhileStatement) Equal(b2 Node) bool {
	b, ok := b2.(*WhileStatement)
	if !ok {
		return false
	}
	if a == nil || b == nil {
		return a == b
	}
	if a.Infinite != b.Infinite {
		return false
	}
	if a.Condition != nil && b.Condition != nil && !a.Condition.Equal(b.Condition) {
		return false
	}
	if a.Body != nil && b.Body != nil && !a.Body.Equal(b.Body) {
		return false
	}
	return true
}
