// Code generated by "stringer -type=PrimitiveTypeName -linecomment"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PrimitiveAny-0]
	_ = x[PrimitiveString-1]
	_ = x[PrimitiveInt-2]
	_ = x[PrimitiveFloat-3]
	_ = x[PrimitiveBool-4]
	_ = x[PrimitiveNothing-5]
	_ = x[PrimitiveResult-6]
	_ = x[PrimitiveError-7]
}

const _PrimitiveTypeName_name = "AnyStringIntFloatBoolNothingResultError"

var _PrimitiveTypeName_index = [...]uint8{0, 3, 9, 12, 17, 21, 28, 34, 39}

func (i PrimitiveTypeName) String() string {
	if i < 0 || i >= PrimitiveTypeName(len(_PrimitiveTypeName_index)-1) {
		return "PrimitiveTypeName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PrimitiveTypeName_name[_PrimitiveTypeName_index[i]:_PrimitiveTypeName_index[i+1]]
}
