// Code generated by asttempl. DO NOT EDIT.
package ast

func (n *AsExpression) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{1, n.Expression}, walkNode{2, n.Name})
}

func (n *AssertExpression) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{1, n.Expression})
}

func (n *AssignableTypePair) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkSlice[Assignable]{1, n.Keys}, walkNode{2, n.Type}, walkNode{3, n.Value})
}

func (n *AssignmentStatement) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkSlice[Assignable]{1, n.Assignee}, walkSlice[Expression]{3, n.Values})
}

func (n *Attribute) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{1, n.Name}, walkSlice[*CallParam]{2, n.Args})
}

func (n *AwaitExpression) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{1, n.Expression})
}

func (n *BadExpression) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{1, n.Value})
}

func (n *BinaryExpression) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{0, n.Left}, walkNode{1, n.Right})
}

func (n *Block) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkSlice[Statement]{1, n.Body})
}

func (n *BooleanLiteral) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c)
}

func (n *CallExpression) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{0, n.Callee}, walkSlice[*CallParam]{1, n.Args})
}

func (n *CallParam) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{0, n.Label}, walkNode{1, n.Value})
}

func (n *Comment) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c)
}

func (n *Discard) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c)
}

func (n *EnumDeclaration) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{0, n.Identifier}, walkSlice[Identifier]{1, n.Generics}, walkSlice[Type]{2, n.Inherited}, walkSlice[*EnumItem]{3, n.Values})
}

func (n *EnumItem) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{0, n.Identifier}, walkNode{1, n.Value}, walkNode{2, n.Parameters}, walkSlice[*Attribute]{3, n.Attributes})
}

func (n *EnumLiteral) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{1, n.Name})
}

func (n *ExpressionPair) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{1, n.Key}, walkNode{2, n.Value})
}

func (n *ExpressionStatement) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{1, n.Expression})
}

func (n *FloatLiteral) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c)
}

func (n *ForExpression) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkSlice[*AssignableTypePair]{1, n.Variables}, walkNode{2, n.Iterator}, walkNode{4, n.Value}, walkNode{5, n.Block})
}

func (n *ForStatement) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkSlice[*AssignableTypePair]{1, n.Variables}, walkNode{2, n.Label}, walkNode{3, n.Expression}, walkNode{4, n.Body})
}

func (n *FuncAliasDeclaration) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{1, n.Struct}, walkNode{2, n.Identifier}, walkNode{3, n.Target})
}

func (n *FunctionDeclaration) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{0, n.Identifier}, walkNode{1, n.SelfType}, walkNode{2, n.SelfName}, walkSlice[Identifier]{3, n.GenericParams}, walkSlice[*FunctionParam]{4, n.Parameters}, walkNode{5, n.ReturnType}, walkNode{6, n.Body}, walkNode{7, n.Expression})
}

func (n *FunctionParam) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkSlice[*IdentifierPair]{0, n.Names}, walkNode{1, n.Type}, walkNode{2, n.Default})
}

func (n *FunctionType) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{1, n.Parameters}, walkNode{2, n.ReturnType})
}

func (n *GenericType) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{1, n.Name}, walkSlice[Type]{2, n.Parameters})
}

func (n *GoExpression) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{1, n.Expression}, walkNode{2, n.Body})
}

func (n *IdentifierPair) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{1, n.Label}, walkNode{2, n.Name})
}

func (n *ImportStatement) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{1, n.Alias}, walkSlice[*IdentifierPair]{4, n.UnqualifiedImports})
}

func (n *IndexExpression) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{0, n.Object}, walkNode{1, n.Property})
}

func (n *IntegerLiteral) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c)
}

func (n *InterfaceDeclaration) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{0, n.Identifier}, walkSlice[Type]{1, n.InheritedTypes}, walkSlice[*InterfaceItem]{2, n.Items})
}

func (n *InterfaceItem) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{0, n.TypePair}, walkSlice[*Attribute]{1, n.Attributes})
}

func (n *LambdaExpression) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkSlice[*AssignableTypePair]{1, n.Params}, walkNode{3, n.Block}, walkNode{4, n.Expr})
}

func (n *ListCastExpression) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{1, n.Type}, walkSlice[*CallParam]{2, n.Args})
}

func (n *ListLiteral) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkSlice[Expression]{1, n.Items})
}

func (n *ListType) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{1, n.Value})
}

func (n *MapCastExpression) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{1, n.KeyType}, walkNode{2, n.ValueType}, walkSlice[*CallParam]{3, n.Args})
}

func (n *MapItem) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkSlice[Expression]{0, n.Keys}, walkNode{2, n.Value})
}

func (n *MapLiteral) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkSlice[*MapItem]{0, n.Entries})
}

func (n *MapType) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{1, n.Key}, walkNode{2, n.Value})
}

func (n *MethodParam) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkSlice[*IdentifierPair]{0, n.Names}, walkNode{1, n.Type})
}

func (n *MethodType) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{1, n.ReturnType}, walkSlice[Identifier]{2, n.GenericParams}, walkSlice[*MethodParam]{3, n.Parameters})
}

func (n *NextStatement) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{1, n.Label})
}

func (n *NilLiteral) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c)
}

func (n *ObjectDestructureEntry) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{1, n.Alias}, walkNode{2, n.Object}, walkNode{3, n.Index}, walkNode{4, n.Default})
}

func (n *ObjectPipeline) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{1, n.Object}, walkSlice[Node]{2, n.Steps})
}

func (n *OptionalType) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{1, n.Value})
}

func (n *ParenExpression) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{0, n.Expression})
}

func (n *ParenType) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{1, n.Label}, walkNode{2, n.Type})
}

func (n *PipelineExpression) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkSlice[Node]{0, n.Steps})
}

func (n *PrimitiveType) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c)
}

func (n *Program) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkSlice[Statement]{1, n.Body}, walkSlice[*Comment]{2, n.Comments})
}

func (n *PublicDeclaration) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{1, n.Declaration})
}

func (n *QualifiedTypeAlias) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{1, n.Namespace}, walkNode{2, n.Identifier})
}

func (n *RangeExpression) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{0, n.From}, walkNode{1, n.To}, walkNode{2, n.Step})
}

func (n *RegexLiteral) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c)
}

func (n *RelationalExpression) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkSlice[Expression]{1, n.Expressions})
}

func (n *RestExpression) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{2, n.Expression})
}

func (n *RestType) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{1, n.Value})
}

func (n *ReturnStatement) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{0, n.Value})
}

func (n *SliceExpression) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{0, n.Object}, walkNode{1, n.From}, walkNode{2, n.To})
}

func (n *StopStatement) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{1, n.Label})
}

func (n *StringLiteral) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c)
}

func (n *StringTypeMatch) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{1, n.Name}, walkNode{2, n.Type})
}

func (n *StructDeclaration) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{0, n.Identifier}, walkSlice[Type]{1, n.InheritedTypes}, walkSlice[*StructField]{2, n.Fields})
}

func (n *StructDotInit) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkSlice[*CallParam]{1, n.Params})
}

func (n *StructField) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkSlice[Identifier]{0, n.Names}, walkNode{1, n.Type}, walkNode{2, n.Value}, walkSlice[*Attribute]{3, n.Attributes})
}

func (n *SubOptions) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkSlice[Expression]{1, n.Options})
}

func (n *Symbol) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c)
}

func (n *TagDeclaration) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{0, n.Identifier}, walkSlice[Type]{1, n.InheritedTypes})
}

func (n *TryExpression) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{1, n.Expression})
}

func (n *TupleLiteral) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkSlice[Expression]{0, n.Values})
}

func (n *TupleType) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkSlice[*TypePair]{1, n.Values})
}

func (n *TypeAlias) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c)
}

func (n *TypeAliasDeclaration) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{0, n.Identifier}, walkNode{1, n.Type})
}

func (n *TypePair) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkSlice[Identifier]{0, n.Keys}, walkNode{1, n.Value})
}

func (n *UnaryExpression) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{1, n.Right})
}

func (n *UnionType) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkSlice[Type]{1, n.Options})
}

func (n *VariableDeclaration) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkSlice[Assignable]{1, n.Variables}, walkSlice[Expression]{2, n.Values}, walkNode{3, n.ExplicitType})
}

func (n *VersionLiteral) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c)
}

func (n *WhenCase) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkSlice[Identifier]{2, n.As}, walkNode{3, n.Guard}, walkNode{4, n.Body})
}

func (n *WhenExpression) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkSlice[Expression]{1, n.Subjects}, walkNode{2, n.Label}, walkSlice[*WhenCase]{3, n.Cases})
}

func (n *WhileStatement) Walk(v Visitor, c *Cursor) StopCode {
	return walkFields(v, n, c, walkNode{1, n.Condition}, walkNode{2, n.Label}, walkNode{3, n.Body})
}
