// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package lexer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOF-0]
	_ = x[EndOfStatement-1]
	_ = x[Illegal-2]
	_ = x[Newline-3]
	_ = x[Comma-4]
	_ = x[Dot-5]
	_ = x[LineComment-6]
	_ = x[BlockComment-7]
	_ = x[Colon-8]
	_ = x[LeftBracket-9]
	_ = x[RightBracket-10]
	_ = x[LeftParenthesis-11]
	_ = x[RightParenthesis-12]
	_ = x[LeftCurlyBrace-13]
	_ = x[RightCurlyBrace-14]
	_ = x[HashLeftCurlyBrace-15]
	_ = x[At-16]
	_ = x[Hash-17]
	_ = x[Identifier-18]
	_ = x[Numeric-19]
	_ = x[Boolean-20]
	_ = x[Nil-21]
	_ = x[String-22]
	_ = x[Underscore-23]
	_ = x[Plus-24]
	_ = x[Minus-25]
	_ = x[Asterisk-26]
	_ = x[Slash-27]
	_ = x[Percent-28]
	_ = x[Caret-29]
	_ = x[Equal-30]
	_ = x[ColonEqual-31]
	_ = x[PlusEqual-32]
	_ = x[MinusEqual-33]
	_ = x[PlusPlus-34]
	_ = x[MinusMinus-35]
	_ = x[EqualEqual-36]
	_ = x[NotEqual-37]
	_ = x[GreaterThan-38]
	_ = x[LessThan-39]
	_ = x[GreaterEqualTo-40]
	_ = x[LessEqualTo-41]
	_ = x[AndAnd-42]
	_ = x[OrOr-43]
	_ = x[Not-44]
	_ = x[Stroke-45]
	_ = x[Question-46]
	_ = x[Spread-47]
	_ = x[Arrow-48]
	_ = x[Pipeline-49]
	_ = x[And-50]
	_ = x[For-51]
	_ = x[Func-52]
	_ = x[Import-53]
	_ = x[In-54]
	_ = x[Next-55]
	_ = x[Or-56]
	_ = x[Public-57]
	_ = x[Return-58]
	_ = x[Type-59]
	_ = x[When-60]
}

const _TokenType_name = "EOFEndOfStatementIllegalNewlineCommaDotLineCommentBlockCommentColonLeftBracketRightBracketLeftParenthesisRightParenthesisLeftCurlyBraceRightCurlyBraceHashLeftCurlyBraceAtHashIdentifierNumericBooleanNilStringUnderscorePlusMinusAsteriskSlashPercentCaretEqualColonEqualPlusEqualMinusEqualPlusPlusMinusMinusEqualEqualNotEqualGreaterThanLessThanGreaterEqualToLessEqualToAndAndOrOrNotStrokeQuestionSpreadArrowPipelineAndForFuncImportInNextOrPublicReturnTypeWhen"

var _TokenType_index = [...]uint16{0, 3, 17, 24, 31, 36, 39, 50, 62, 67, 78, 90, 105, 121, 135, 150, 168, 170, 174, 184, 191, 198, 201, 207, 217, 221, 226, 234, 239, 246, 251, 256, 266, 275, 285, 293, 303, 313, 321, 332, 340, 354, 365, 371, 375, 378, 384, 392, 398, 403, 411, 414, 417, 421, 427, 429, 433, 435, 441, 447, 451, 455}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
