// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package lexer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOF-1]
	_ = x[EndOfStatement-2]
	_ = x[Illegal-3]
	_ = x[Newline-4]
	_ = x[Comma-5]
	_ = x[Dot-6]
	_ = x[LineComment-7]
	_ = x[BlockComment-8]
	_ = x[Colon-9]
	_ = x[LeftBracket-10]
	_ = x[RightBracket-11]
	_ = x[LeftParenthesis-12]
	_ = x[RightParenthesis-13]
	_ = x[LeftCurlyBrace-14]
	_ = x[RightCurlyBrace-15]
	_ = x[HashLeftCurlyBrace-16]
	_ = x[At-17]
	_ = x[Hash-18]
	_ = x[Identifier-19]
	_ = x[Numeric-20]
	_ = x[Boolean-21]
	_ = x[Nil-22]
	_ = x[String-23]
	_ = x[Underscore-24]
	_ = x[Plus-25]
	_ = x[Minus-26]
	_ = x[Asterisk-27]
	_ = x[Slash-28]
	_ = x[Percent-29]
	_ = x[Caret-30]
	_ = x[Equal-31]
	_ = x[ColonEqual-32]
	_ = x[PlusEqual-33]
	_ = x[MinusEqual-34]
	_ = x[PlusPlus-35]
	_ = x[MinusMinus-36]
	_ = x[EqualEqual-37]
	_ = x[NotEqual-38]
	_ = x[GreaterThan-39]
	_ = x[LessThan-40]
	_ = x[GreaterEqualTo-41]
	_ = x[LessEqualTo-42]
	_ = x[AndAnd-43]
	_ = x[OrOr-44]
	_ = x[Not-45]
	_ = x[Stroke-46]
	_ = x[Question-47]
	_ = x[Ellipsis-48]
	_ = x[Arrow-49]
	_ = x[Pipeline-50]
	_ = x[And-51]
	_ = x[For-52]
	_ = x[Func-53]
	_ = x[Import-54]
	_ = x[In-55]
	_ = x[Next-56]
	_ = x[Or-57]
	_ = x[Public-58]
	_ = x[Return-59]
	_ = x[Type-60]
	_ = x[When-61]
}

const _TokenType_name = "EOFEndOfStatementIllegalNewlineCommaDotLineCommentBlockCommentColonLeftBracketRightBracketLeftParenthesisRightParenthesisLeftCurlyBraceRightCurlyBraceHashLeftCurlyBraceAtHashIdentifierNumericBooleanNilStringUnderscorePlusMinusAsteriskSlashPercentCaretEqualColonEqualPlusEqualMinusEqualPlusPlusMinusMinusEqualEqualNotEqualGreaterThanLessThanGreaterEqualToLessEqualToAndAndOrOrNotStrokeQuestionEllipsisArrowPipelineAndForFuncImportInNextOrPublicReturnTypeWhen"

var _TokenType_index = [...]uint16{0, 3, 17, 24, 31, 36, 39, 50, 62, 67, 78, 90, 105, 121, 135, 150, 168, 170, 174, 184, 191, 198, 201, 207, 217, 221, 226, 234, 239, 246, 251, 256, 266, 275, 285, 293, 303, 313, 321, 332, 340, 354, 365, 371, 375, 378, 384, 392, 400, 405, 413, 416, 419, 423, 429, 431, 435, 437, 443, 449, 453, 457}

func (i TokenType) String() string {
	i -= 1
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
