// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package lexer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOF-1]
	_ = x[EndOfStatement-2]
	_ = x[Illegal-3]
	_ = x[Newline-4]
	_ = x[Comma-5]
	_ = x[Dot-6]
	_ = x[LineComment-7]
	_ = x[BlockComment-8]
	_ = x[Hashbang-9]
	_ = x[Colon-10]
	_ = x[LeftBracket-11]
	_ = x[RightBracket-12]
	_ = x[LeftParenthesis-13]
	_ = x[RightParenthesis-14]
	_ = x[LeftCurlyBrace-15]
	_ = x[RightCurlyBrace-16]
	_ = x[HashLeftCurlyBrace-17]
	_ = x[At-18]
	_ = x[Hash-19]
	_ = x[Identifier-20]
	_ = x[Numeric-21]
	_ = x[Boolean-22]
	_ = x[Nil-23]
	_ = x[String-24]
	_ = x[Underscore-25]
	_ = x[Plus-26]
	_ = x[Minus-27]
	_ = x[Asterisk-28]
	_ = x[Slash-29]
	_ = x[Percent-30]
	_ = x[Caret-31]
	_ = x[Equal-32]
	_ = x[ColonEqual-33]
	_ = x[PlusEqual-34]
	_ = x[MinusEqual-35]
	_ = x[PlusPlus-36]
	_ = x[MinusMinus-37]
	_ = x[EqualEqual-38]
	_ = x[NotEqual-39]
	_ = x[GreaterThan-40]
	_ = x[LessThan-41]
	_ = x[GreaterEqualTo-42]
	_ = x[LessEqualTo-43]
	_ = x[AndAnd-44]
	_ = x[OrOr-45]
	_ = x[Not-46]
	_ = x[Stroke-47]
	_ = x[Question-48]
	_ = x[Ellipsis-49]
	_ = x[Arrow-50]
	_ = x[Pipeline-51]
	_ = x[Backslash-52]
	_ = x[And-53]
	_ = x[Break-54]
	_ = x[For-55]
	_ = x[Func-56]
	_ = x[Import-57]
	_ = x[In-58]
	_ = x[Next-59]
	_ = x[Or-60]
	_ = x[Public-61]
	_ = x[Return-62]
	_ = x[Type-63]
	_ = x[When-64]
}

const _TokenType_name = "EOFEndOfStatementIllegalNewlineCommaDotLineCommentBlockCommentHashbangColonLeftBracketRightBracketLeftParenthesisRightParenthesisLeftCurlyBraceRightCurlyBraceHashLeftCurlyBraceAtHashIdentifierNumericBooleanNilStringUnderscorePlusMinusAsteriskSlashPercentCaretEqualColonEqualPlusEqualMinusEqualPlusPlusMinusMinusEqualEqualNotEqualGreaterThanLessThanGreaterEqualToLessEqualToAndAndOrOrNotStrokeQuestionEllipsisArrowPipelineBackslashAndBreakForFuncImportInNextOrPublicReturnTypeWhen"

var _TokenType_index = [...]uint16{0, 3, 17, 24, 31, 36, 39, 50, 62, 70, 75, 86, 98, 113, 129, 143, 158, 176, 178, 182, 192, 199, 206, 209, 215, 225, 229, 234, 242, 247, 254, 259, 264, 274, 283, 293, 301, 311, 321, 329, 340, 348, 362, 373, 379, 383, 386, 392, 400, 408, 413, 421, 430, 433, 438, 441, 445, 451, 453, 457, 459, 465, 471, 475, 479}

func (i TokenType) String() string {
	i -= 1
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
