// Code generated by "stringer -type=ErrorCode"; DO NOT EDIT.

package errors

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SyntaxErrorPrefix-0]
	_ = x[WarningPrefix-100]
	_ = x[TypeErrorPrefix-200]
	_ = x[ReferenceErrorPrefix-300]
	_ = x[ModuleErrorPrefix-400]
	_ = x[ImplementationErrorPrefix-500]
	_ = x[ErrTooManyErrors - -1]
	_ = x[ErrUnexpectedToken-1]
	_ = x[ErrExpectedToken-2]
	_ = x[ErrAliasInUnqualifiedImport-3]
	_ = x[ErrImportExpectedModule-4]
	_ = x[ErrImportInvalidWildcard-5]
	_ = x[ErrWildcardWithUnqualified-6]
	_ = x[ErrWildcardAndAlias-7]
	_ = x[ErrEmptyUnqualifiedImport-8]
	_ = x[ErrImportsGoFirst-9]
	_ = x[ErrUnterminatedString-10]
	_ = x[ErrMultilineQuotedString-11]
	_ = x[ErrUnterminatedComment-12]
	_ = x[ErrUnterminatedRegex-13]
	_ = x[ErrMisplacedShebang-14]
	_ = x[ErrInvalidComma-15]
	_ = x[ErrCurlyQuote-16]
	_ = x[ErrInvalidCharacter-17]
	_ = x[ErrStringEscape-18]
	_ = x[ErrUnicodeEscapeTooBig-19]
	_ = x[ErrConsecutiveSeparator-20]
	_ = x[ErrMisplacedSeparator-21]
	_ = x[ErrTrailingSeparator-22]
	_ = x[ErrExpectedHex-23]
	_ = x[ErrExpectedOctal-24]
	_ = x[ErrExpectedBinary-25]
	_ = x[ErrExpectedDecimal-26]
	_ = x[ErrInvalidVersion-27]
	_ = x[ErrUnderscoreValue-28]
	_ = x[ErrInvalidUpdate-29]
	_ = x[ErrInvalidUpdateExpr-30]
	_ = x[ErrColonEqual-31]
	_ = x[ErrAssignmentAsExpr-32]
	_ = x[ErrEmptyDestructure-33]
	_ = x[ErrInvalidAssignment-34]
	_ = x[ErrNonNameDeclaration-35]
	_ = x[ErrInvalidTypeAnnotation-36]
	_ = x[ErrDestructPatAfterColon-37]
	_ = x[ErrDestructInvalidEqual-38]
	_ = x[ErrMismatchedAssignment-39]
	_ = x[ErrGenericInFuncAlias-40]
	_ = x[ErrMissingFuncParamType-41]
	_ = x[ErrNonNameFuncAlias-42]
	_ = x[ErrInvalidOpaque-43]
	_ = x[ErrInvalidPublic-44]
	_ = x[ErrPublicGoesFirst-45]
	_ = x[ErrDuplicateModifier-46]
	_ = x[ErrFuncDotAfterSelf-47]
	_ = x[ErrReservedKeyword-48]
	_ = x[ErrNotAnExpression-49]
	_ = x[ErrInvalidLabelShorthand-50]
	_ = x[ErrInvalidLabel-51]
	_ = x[ErrReturnPipelineNotLast-52]
	_ = x[ErrInvalidObjectPipeStep-53]
	_ = x[ErrMultipleKeysInMapRest-54]
	_ = x[ErrExpectedExprAfterClosedRange-55]
	_ = x[ErrEllipsisForClosedRangeStep-56]
	_ = x[ErrMustBeFuncCall-57]
	_ = x[ErrSelfExecFuncNotAllowed-58]
	_ = x[ErrParenAroundLambdaType-59]
	_ = x[ErrParenAroundLambdaDefault-60]
	_ = x[ErrArrowAfterNonParenLambda-61]
	_ = x[ErrChainedNotEqual-62]
	_ = x[ErrMultiDirectionCompareChain-63]
	_ = x[ErrInequalityWithEqualChain-64]
	_ = x[ErrExpectedTypeAssignment-65]
	_ = x[ErrRequiredStructFieldType-66]
	_ = x[ErrEmptyGeneric-67]
	_ = x[ErrParenFuncTypeParams-68]
	_ = x[ErrIntfDefaultValue-69]
	_ = x[ErrMixTypeTupleLabels-70]
	_ = x[ErrIntfMultiKeyMethod-71]
	_ = x[ErrInvalidGenericType-72]
	_ = x[ErrInvalidArrow-73]
	_ = x[ErrForInvalidCondition-74]
	_ = x[ErrUnderscoreWithRest-75]
	_ = x[ErrNotAllowedInWhen-76]
	_ = x[ErrRequiredBraces-77]
	_ = x[ErrTryBlock-78]
	_ = x[ErrIfStatement-79]
	_ = x[ErrTripleEqual-80]
	_ = x[ErrInvalidLoop-81]
	_ = x[ErrRedeclaredVar-82]
	_ = x[ErrRedeclaredType-83]
	_ = x[ErrRedeclaredEnum-84]
	_ = x[ErrRedeclaredField-85]
	_ = x[ErrMethAndFieldSameName-86]
	_ = x[ErrMethodInOtherScope-87]
	_ = x[ErrProvenUnreachable-88]
	_ = x[ErrUnusedValue-89]
	_ = x[ErrReturnOutsideFunc-90]
	_ = x[ErrVarUndefined-301]
	_ = x[ErrEnumUndefined-302]
	_ = x[ErrTypeUndefined-303]
	_ = x[ErrEnumCycle-304]
	_ = x[ErrUntypedNil-201]
	_ = x[ErrUntypedEmptyList-202]
	_ = x[ErrUntypedEnum-203]
	_ = x[ErrUncheckedOptional-204]
	_ = x[ErrUncheckedResult-205]
	_ = x[ErrInvalidRestType-206]
	_ = x[ErrInvalidRestExpr-207]
	_ = x[ErrVariadicLast-208]
	_ = x[ErrTypeCycle-209]
	_ = x[ErrNoGenerics-210]
	_ = x[ErrWrongTypeParamLen-211]
	_ = x[ErrInvalidEnumValue-212]
	_ = x[ErrInheritNonStructOrIntf-213]
	_ = x[ErrConflictingInherit-214]
	_ = x[ErrNonStructReceiver-215]
	_ = x[ErrOverloadExists-216]
	_ = x[ErrAssignToConst-217]
	_ = x[ErrTypeMismatch-218]
	_ = x[ErrWrongAssignType-219]
	_ = x[ErrNonBoolLogical-220]
	_ = x[ErrMismatchedOperands-221]
	_ = x[ErrMismatchedDistrib-222]
	_ = x[ErrUncomparableTypes-223]
	_ = x[ErrIntTimesString-224]
	_ = x[ErrInvalidOperation-225]
	_ = x[WarnNotEqualOr-101]
	_ = x[WarnEqualAnd-102]
	_ = x[WarnUnreachable-103]
	_ = x[WarnUnused-104]
}

const (
	_ErrorCode_name_0 = "ErrTooManyErrorsSyntaxErrorPrefixErrUnexpectedTokenErrExpectedTokenErrAliasInUnqualifiedImportErrImportExpectedModuleErrImportInvalidWildcardErrWildcardWithUnqualifiedErrWildcardAndAliasErrEmptyUnqualifiedImportErrImportsGoFirstErrUnterminatedStringErrMultilineQuotedStringErrUnterminatedCommentErrUnterminatedRegexErrMisplacedShebangErrInvalidCommaErrCurlyQuoteErrInvalidCharacterErrStringEscapeErrUnicodeEscapeTooBigErrConsecutiveSeparatorErrMisplacedSeparatorErrTrailingSeparatorErrExpectedHexErrExpectedOctalErrExpectedBinaryErrExpectedDecimalErrInvalidVersionErrUnderscoreValueErrInvalidUpdateErrInvalidUpdateExprErrColonEqualErrAssignmentAsExprErrEmptyDestructureErrInvalidAssignmentErrNonNameDeclarationErrInvalidTypeAnnotationErrDestructPatAfterColonErrDestructInvalidEqualErrMismatchedAssignmentErrGenericInFuncAliasErrMissingFuncParamTypeErrNonNameFuncAliasErrInvalidOpaqueErrInvalidPublicErrPublicGoesFirstErrDuplicateModifierErrFuncDotAfterSelfErrReservedKeywordErrNotAnExpressionErrInvalidLabelShorthandErrInvalidLabelErrReturnPipelineNotLastErrInvalidObjectPipeStepErrMultipleKeysInMapRestErrExpectedExprAfterClosedRangeErrEllipsisForClosedRangeStepErrMustBeFuncCallErrSelfExecFuncNotAllowedErrParenAroundLambdaTypeErrParenAroundLambdaDefaultErrArrowAfterNonParenLambdaErrChainedNotEqualErrMultiDirectionCompareChainErrInequalityWithEqualChainErrExpectedTypeAssignmentErrRequiredStructFieldTypeErrEmptyGenericErrParenFuncTypeParamsErrIntfDefaultValueErrMixTypeTupleLabelsErrIntfMultiKeyMethodErrInvalidGenericTypeErrInvalidArrowErrForInvalidConditionErrUnderscoreWithRestErrNotAllowedInWhenErrRequiredBracesErrTryBlockErrIfStatementErrTripleEqualErrInvalidLoopErrRedeclaredVarErrRedeclaredTypeErrRedeclaredEnumErrRedeclaredFieldErrMethAndFieldSameNameErrMethodInOtherScopeErrProvenUnreachableErrUnusedValueErrReturnOutsideFunc"
	_ErrorCode_name_1 = "WarningPrefixWarnNotEqualOrWarnEqualAndWarnUnreachableWarnUnused"
	_ErrorCode_name_2 = "TypeErrorPrefixErrUntypedNilErrUntypedEmptyListErrUntypedEnumErrUncheckedOptionalErrUncheckedResultErrInvalidRestTypeErrInvalidRestExprErrVariadicLastErrTypeCycleErrNoGenericsErrWrongTypeParamLenErrInvalidEnumValueErrInheritNonStructOrIntfErrConflictingInheritErrNonStructReceiverErrOverloadExistsErrAssignToConstErrTypeMismatchErrWrongAssignTypeErrNonBoolLogicalErrMismatchedOperandsErrMismatchedDistribErrUncomparableTypesErrIntTimesStringErrInvalidOperation"
	_ErrorCode_name_3 = "ReferenceErrorPrefixErrVarUndefinedErrEnumUndefinedErrTypeUndefinedErrEnumCycle"
	_ErrorCode_name_4 = "ModuleErrorPrefix"
	_ErrorCode_name_5 = "ImplementationErrorPrefix"
)

var (
	_ErrorCode_index_0 = [...]uint16{0, 16, 33, 51, 67, 94, 117, 141, 167, 186, 211, 228, 249, 273, 295, 315, 334, 349, 362, 381, 396, 418, 441, 462, 482, 496, 512, 529, 547, 564, 582, 598, 618, 631, 650, 669, 689, 710, 734, 758, 781, 804, 825, 848, 867, 883, 899, 917, 937, 956, 974, 992, 1016, 1031, 1055, 1079, 1103, 1134, 1163, 1180, 1205, 1229, 1256, 1283, 1301, 1330, 1357, 1382, 1408, 1423, 1445, 1464, 1485, 1506, 1527, 1542, 1564, 1585, 1604, 1621, 1632, 1646, 1660, 1674, 1690, 1707, 1724, 1742, 1765, 1786, 1806, 1820, 1840}
	_ErrorCode_index_1 = [...]uint8{0, 13, 27, 39, 54, 64}
	_ErrorCode_index_2 = [...]uint16{0, 15, 28, 47, 61, 81, 99, 117, 135, 150, 162, 175, 195, 214, 239, 260, 280, 297, 313, 328, 346, 363, 384, 404, 424, 441, 460}
	_ErrorCode_index_3 = [...]uint8{0, 20, 35, 51, 67, 79}
)

func (i ErrorCode) String() string {
	switch {
	case -1 <= i && i <= 90:
		i -= -1
		return _ErrorCode_name_0[_ErrorCode_index_0[i]:_ErrorCode_index_0[i+1]]
	case 100 <= i && i <= 104:
		i -= 100
		return _ErrorCode_name_1[_ErrorCode_index_1[i]:_ErrorCode_index_1[i+1]]
	case 200 <= i && i <= 225:
		i -= 200
		return _ErrorCode_name_2[_ErrorCode_index_2[i]:_ErrorCode_index_2[i+1]]
	case 300 <= i && i <= 304:
		i -= 300
		return _ErrorCode_name_3[_ErrorCode_index_3[i]:_ErrorCode_index_3[i+1]]
	case i == 400:
		return _ErrorCode_name_4
	case i == 500:
		return _ErrorCode_name_5
	default:
		return "ErrorCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
