// Code generated by "stringer -type=ErrorCode"; DO NOT EDIT.

package errors

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SyntaxErrorPrefix-0]
	_ = x[WarningPrefix-100]
	_ = x[TypeErrorPrefix-200]
	_ = x[ReferenceErrorPrefix-300]
	_ = x[ErrUnexpectedToken-1]
	_ = x[ErrExpectedToken-2]
	_ = x[ErrAliasInUnqualifiedImport-3]
	_ = x[ErrImportExpectedModule-4]
	_ = x[ErrImportInvalidWildcard-5]
	_ = x[ErrImportTooManyWildcard-6]
	_ = x[ErrWildcardAndUnqImport-7]
	_ = x[ErrWildcardAndAlias-8]
	_ = x[ErrEmptyUnqImport-9]
	_ = x[ErrImportsGoFirst-10]
	_ = x[ErrUnterminatedString-11]
	_ = x[ErrUnterminatedComment-12]
	_ = x[ErrUnterminatedRegex-13]
	_ = x[ErrMisplacedShebang-14]
	_ = x[ErrInvalidComma-15]
	_ = x[ErrStringEscape-16]
	_ = x[ErrUnicodeEscTooBig-17]
	_ = x[ErrConsecutiveSep-18]
	_ = x[ErrMisplacedSep-19]
	_ = x[ErrTrailingSep-20]
	_ = x[ErrExpectedHex-21]
	_ = x[ErrExpectedOctal-22]
	_ = x[ErrExpectedBinary-23]
	_ = x[ErrExpectedDecimal-24]
	_ = x[ErrInvalidLambdaParams-25]
	_ = x[ErrInvalidVersionLit-26]
	_ = x[ErrUnderscoreValue-27]
	_ = x[ErrAssignmentAsExpr-28]
	_ = x[ErrEmptyDestructure-29]
	_ = x[ErrInvalidAssignment-30]
	_ = x[ErrNonNameDeclaration-31]
	_ = x[ErrColonEqual-32]
	_ = x[ErrInvalidTypeAnnotation-33]
	_ = x[ErrDestructPatAfterColon-34]
	_ = x[ErrDestructInvalidEqual-35]
	_ = x[ErrReservedKeyword-36]
	_ = x[ErrNotAnExpression-37]
	_ = x[ErrInvalidLabelShorthand-38]
	_ = x[ErrInvalidLabel-39]
	_ = x[ErrGenericInFuncAlias-40]
	_ = x[ErrMissingFuncParamType-41]
	_ = x[ErrReturnPipelineNotLast-42]
	_ = x[ErrInvalidObjPipeStep-43]
	_ = x[ErrNonNameFuncAlias-44]
	_ = x[ErrMultipleKeysInMapRest-45]
	_ = x[ErrInvalidUpdate-46]
	_ = x[ErrExpectedExprAfterClosedRange-47]
	_ = x[ErrEllipsisForClosedRange-48]
	_ = x[ErrExpectedTypeAssignment-49]
	_ = x[ErrRequiredStructFieldType-50]
	_ = x[ErrEmptyGeneric-51]
	_ = x[ErrParenRequiredFunc-52]
	_ = x[ErrInterfaceDefaultValue-53]
	_ = x[ErrMixTypeTupleLabels-54]
	_ = x[ErrInvalidOpaque-55]
	_ = x[ErrForInvalidCond-56]
	_ = x[ErrInvalidPublic-57]
	_ = x[ErrPublicFirst-58]
	_ = x[ErrDuplicateModifier-59]
	_ = x[ErrUnderscoreWithRest-60]
	_ = x[ErrNotAllowedInWhen-61]
	_ = x[ErrRedeclaredVar-62]
	_ = x[ErrRedeclaredType-63]
	_ = x[ErrRedeclaredEnum-64]
	_ = x[ErrRedeclaredField-65]
	_ = x[ErrMethAndFieldSameName-66]
	_ = x[ErrMethodInOtherScope-67]
	_ = x[ErrProvenUnreachable-68]
	_ = x[ErrUnusedValue-69]
	_ = x[ErrReturnOutsideFunc-70]
	_ = x[ErrVarUndefined-301]
	_ = x[ErrEnumUndefined-302]
	_ = x[ErrTypeUndefined-303]
	_ = x[ErrEnumCycle-304]
	_ = x[ErrUntypedNil-201]
	_ = x[ErrUntypedEmptyList-202]
	_ = x[ErrUntypedEnum-203]
	_ = x[ErrUncheckedOptional-204]
	_ = x[ErrUncheckedResult-205]
	_ = x[ErrInvalidRestType-206]
	_ = x[ErrInvalidRestExpr-207]
	_ = x[ErrVariadicLast-208]
	_ = x[ErrTypeCycle-209]
	_ = x[ErrNoGenerics-210]
	_ = x[ErrWrongTypeParamLen-211]
	_ = x[ErrInvalidEnumValue-212]
	_ = x[ErrInheritNonStructOrIntf-213]
	_ = x[ErrConflictingInherit-214]
	_ = x[ErrNonStructReceiver-215]
	_ = x[ErrOverloadExists-216]
	_ = x[ErrAssignToConst-217]
	_ = x[ErrTypeMismatch-218]
	_ = x[ErrWrongAssignType-219]
	_ = x[ErrNonBoolLogical-220]
	_ = x[ErrMismatchedOperands-221]
	_ = x[ErrMismatchedDistrib-222]
	_ = x[ErrUncomparableTypes-223]
	_ = x[ErrIntTimesString-224]
	_ = x[ErrInvalidOperation-225]
	_ = x[WarnNotEqualOr-101]
	_ = x[WarnEqualAnd-102]
	_ = x[WarnUnreachable-103]
	_ = x[WarnUnused-104]
}

const (
	_ErrorCode_name_0 = "SyntaxErrorPrefixErrUnexpectedTokenErrExpectedTokenErrAliasInUnqualifiedImportErrImportExpectedModuleErrImportInvalidWildcardErrImportTooManyWildcardErrWildcardAndUnqImportErrWildcardAndAliasErrEmptyUnqImportErrImportsGoFirstErrUnterminatedStringErrUnterminatedCommentErrUnterminatedRegexErrMisplacedShebangErrInvalidCommaErrStringEscapeErrUnicodeEscTooBigErrConsecutiveSepErrMisplacedSepErrTrailingSepErrExpectedHexErrExpectedOctalErrExpectedBinaryErrExpectedDecimalErrInvalidLambdaParamsErrInvalidVersionLitErrUnderscoreValueErrAssignmentAsExprErrEmptyDestructureErrInvalidAssignmentErrNonNameDeclarationErrColonEqualErrInvalidTypeAnnotationErrDestructPatAfterColonErrDestructInvalidEqualErrReservedKeywordErrNotAnExpressionErrInvalidLabelShorthandErrInvalidLabelErrGenericInFuncAliasErrMissingFuncParamTypeErrReturnPipelineNotLastErrInvalidObjPipeStepErrNonNameFuncAliasErrMultipleKeysInMapRestErrInvalidUpdateErrExpectedExprAfterClosedRangeErrEllipsisForClosedRangeErrExpectedTypeAssignmentErrRequiredStructFieldTypeErrEmptyGenericErrParenRequiredFuncErrInterfaceDefaultValueErrMixTypeTupleLabelsErrInvalidOpaqueErrForInvalidCondErrInvalidPublicErrPublicFirstErrDuplicateModifierErrUnderscoreWithRestErrNotAllowedInWhenErrRedeclaredVarErrRedeclaredTypeErrRedeclaredEnumErrRedeclaredFieldErrMethAndFieldSameNameErrMethodInOtherScopeErrProvenUnreachableErrUnusedValueErrReturnOutsideFunc"
	_ErrorCode_name_1 = "WarningPrefixWarnNotEqualOrWarnEqualAndWarnUnreachableWarnUnused"
	_ErrorCode_name_2 = "TypeErrorPrefixErrUntypedNilErrUntypedEmptyListErrUntypedEnumErrUncheckedOptionalErrUncheckedResultErrInvalidRestTypeErrInvalidRestExprErrVariadicLastErrTypeCycleErrNoGenericsErrWrongTypeParamLenErrInvalidEnumValueErrInheritNonStructOrIntfErrConflictingInheritErrNonStructReceiverErrOverloadExistsErrAssignToConstErrTypeMismatchErrWrongAssignTypeErrNonBoolLogicalErrMismatchedOperandsErrMismatchedDistribErrUncomparableTypesErrIntTimesStringErrInvalidOperation"
	_ErrorCode_name_3 = "ReferenceErrorPrefixErrVarUndefinedErrEnumUndefinedErrTypeUndefinedErrEnumCycle"
)

var (
	_ErrorCode_index_0 = [...]uint16{0, 17, 35, 51, 78, 101, 125, 149, 172, 191, 208, 225, 246, 268, 288, 307, 322, 337, 356, 373, 388, 402, 416, 432, 449, 467, 489, 509, 527, 546, 565, 585, 606, 619, 643, 667, 690, 708, 726, 750, 765, 786, 809, 833, 854, 873, 897, 913, 944, 969, 994, 1020, 1035, 1055, 1079, 1100, 1116, 1133, 1149, 1163, 1183, 1204, 1223, 1239, 1256, 1273, 1291, 1314, 1335, 1355, 1369, 1389}
	_ErrorCode_index_1 = [...]uint8{0, 13, 27, 39, 54, 64}
	_ErrorCode_index_2 = [...]uint16{0, 15, 28, 47, 61, 81, 99, 117, 135, 150, 162, 175, 195, 214, 239, 260, 280, 297, 313, 328, 346, 363, 384, 404, 424, 441, 460}
	_ErrorCode_index_3 = [...]uint8{0, 20, 35, 51, 67, 79}
)

func (i ErrorCode) String() string {
	switch {
	case 0 <= i && i <= 70:
		return _ErrorCode_name_0[_ErrorCode_index_0[i]:_ErrorCode_index_0[i+1]]
	case 100 <= i && i <= 104:
		i -= 100
		return _ErrorCode_name_1[_ErrorCode_index_1[i]:_ErrorCode_index_1[i+1]]
	case 200 <= i && i <= 225:
		i -= 200
		return _ErrorCode_name_2[_ErrorCode_index_2[i]:_ErrorCode_index_2[i+1]]
	case 300 <= i && i <= 304:
		i -= 300
		return _ErrorCode_name_3[_ErrorCode_index_3[i]:_ErrorCode_index_3[i+1]]
	default:
		return "ErrorCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
