// Code generated by "stringer -type=ErrorCode"; DO NOT EDIT.

package errors

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SyntaxErrorPrefix-0]
	_ = x[WarningPrefix-100]
	_ = x[TypeErrorPrefix-200]
	_ = x[ReferenceErrorPrefix-300]
	_ = x[ErrUnexpectedToken-1]
	_ = x[ErrExpectedToken-2]
	_ = x[ErrExpectedDotInBraceImport-3]
	_ = x[ErrAliasInUnqualifiedImport-4]
	_ = x[ErrImportExpectedModule-5]
	_ = x[ErrImportPrefixDot-6]
	_ = x[ErrImportInvalidWildcard-7]
	_ = x[ErrImportTooManyWildcard-8]
	_ = x[ErrWildcardAndUnqImport-9]
	_ = x[ErrWildcardAndAlias-10]
	_ = x[ErrEmptyUnqImport-11]
	_ = x[ErrImportsGoFirst-12]
	_ = x[ErrUnterminatedString-13]
	_ = x[ErrUnterminatedComment-14]
	_ = x[ErrUnterminatedBrace-15]
	_ = x[ErrMisplacedShebang-16]
	_ = x[ErrInvalidNumber-17]
	_ = x[ErrStringEscape-18]
	_ = x[ErrUnicodeEscTooBig-19]
	_ = x[ErrConsecutiveSep-20]
	_ = x[ErrMisplacedSep-21]
	_ = x[ErrTrailingSep-22]
	_ = x[ErrExpectedHex-23]
	_ = x[ErrExpectedOctal-24]
	_ = x[ErrExpectedBinary-25]
	_ = x[ErrExpectedDecimal-26]
	_ = x[ErrExpectedParamInLambda-27]
	_ = x[ErrExpectedSymbolAssign-28]
	_ = x[ErrReservedKeyword-29]
	_ = x[ErrExpectedExpression-30]
	_ = x[ErrInvalidLabelShorthand-31]
	_ = x[ErrInvalidLabel-32]
	_ = x[ErrMissingFuncParamType-33]
	_ = x[ErrNotEnoughEnumItems-34]
	_ = x[ErrExpectedTypeAssignment-35]
	_ = x[ErrRequiredStructFieldType-36]
	_ = x[ErrEmptyGeneric-37]
	_ = x[ErrParenRequiredFunc-38]
	_ = x[ErrForInvalidCond-39]
	_ = x[ErrInvalidPublic-40]
	_ = x[ErrUnderscoreWithRest-41]
	_ = x[ErrNotAllowedInGuard-42]
	_ = x[ErrRedeclaredVar-43]
	_ = x[ErrRedeclaredType-44]
	_ = x[ErrRedeclaredEnum-45]
	_ = x[ErrMethAndFieldSameName-46]
	_ = x[ErrMethodInOtherScope-47]
	_ = x[ErrProvenUnreachable-48]
	_ = x[ErrVarUndefined-301]
	_ = x[ErrEnumUndefined-302]
	_ = x[ErrTypeUndefined-303]
	_ = x[ErrEnumCycle-304]
	_ = x[ErrUntypedNil-201]
	_ = x[ErrUntypedEmptyList-202]
	_ = x[ErrUntypedEnum-203]
	_ = x[ErrUncheckedOptional-204]
	_ = x[ErrUncheckedResult-205]
	_ = x[ErrUnusedValue-206]
	_ = x[ErrInvalidRestType-207]
	_ = x[ErrInvalidRestExpr-208]
	_ = x[ErrVariadicLast-209]
	_ = x[ErrTypeCycle-210]
	_ = x[ErrNoGenerics-211]
	_ = x[ErrWrongTypeParamLen-212]
	_ = x[ErrInvalidEnumValue-213]
	_ = x[ErrInheritNonStructOrIntf-214]
	_ = x[ErrConflictingInherit-215]
	_ = x[ErrNonStructReceiver-216]
	_ = x[ErrOverloadExists-217]
	_ = x[ErrAssignToConst-218]
	_ = x[ErrTypeMismatch-219]
	_ = x[ErrWrongAssignType-220]
	_ = x[ErrNonBoolLogical-221]
	_ = x[ErrMismatchedOperands-222]
	_ = x[ErrMismatchedDistrib-223]
	_ = x[ErrUncomparableTypes-224]
	_ = x[ErrIntTimesString-225]
	_ = x[ErrInvalidOperation-226]
	_ = x[WarnNotEqualOr-101]
	_ = x[WarnEqualAnd-102]
	_ = x[WarnUnreachable-103]
	_ = x[WarnUnused-104]
}

const (
	_ErrorCode_name_0 = "SyntaxErrorPrefixErrUnexpectedTokenErrExpectedTokenErrExpectedDotInBraceImportErrAliasInUnqualifiedImportErrImportExpectedModuleErrImportPrefixDotErrImportInvalidWildcardErrImportTooManyWildcardErrWildcardAndUnqImportErrWildcardAndAliasErrEmptyUnqImportErrImportsGoFirstErrUnterminatedStringErrUnterminatedCommentErrUnterminatedBraceErrMisplacedShebangErrInvalidNumberErrStringEscapeErrUnicodeEscTooBigErrConsecutiveSepErrMisplacedSepErrTrailingSepErrExpectedHexErrExpectedOctalErrExpectedBinaryErrExpectedDecimalErrExpectedParamInLambdaErrExpectedSymbolAssignErrReservedKeywordErrExpectedExpressionErrInvalidLabelShorthandErrInvalidLabelErrMissingFuncParamTypeErrNotEnoughEnumItemsErrExpectedTypeAssignmentErrRequiredStructFieldTypeErrEmptyGenericErrParenRequiredFuncErrForInvalidCondErrInvalidPublicErrUnderscoreWithRestErrNotAllowedInGuardErrRedeclaredVarErrRedeclaredTypeErrRedeclaredEnumErrMethAndFieldSameNameErrMethodInOtherScopeErrProvenUnreachable"
	_ErrorCode_name_1 = "WarningPrefixWarnNotEqualOrWarnEqualAndWarnUnreachableWarnUnused"
	_ErrorCode_name_2 = "TypeErrorPrefixErrUntypedNilErrUntypedEmptyListErrUntypedEnumErrUncheckedOptionalErrUncheckedResultErrUnusedValueErrInvalidRestTypeErrInvalidRestExprErrVariadicLastErrTypeCycleErrNoGenericsErrWrongTypeParamLenErrInvalidEnumValueErrInheritNonStructOrIntfErrConflictingInheritErrNonStructReceiverErrOverloadExistsErrAssignToConstErrTypeMismatchErrWrongAssignTypeErrNonBoolLogicalErrMismatchedOperandsErrMismatchedDistribErrUncomparableTypesErrIntTimesStringErrInvalidOperation"
	_ErrorCode_name_3 = "ReferenceErrorPrefixErrVarUndefinedErrEnumUndefinedErrTypeUndefinedErrEnumCycle"
)

var (
	_ErrorCode_index_0 = [...]uint16{0, 17, 35, 51, 78, 105, 128, 146, 170, 194, 217, 236, 253, 270, 291, 313, 333, 352, 368, 383, 402, 419, 434, 448, 462, 478, 495, 513, 537, 560, 578, 599, 623, 638, 661, 682, 707, 733, 748, 768, 785, 801, 822, 842, 858, 875, 892, 915, 936, 956}
	_ErrorCode_index_1 = [...]uint8{0, 13, 27, 39, 54, 64}
	_ErrorCode_index_2 = [...]uint16{0, 15, 28, 47, 61, 81, 99, 113, 131, 149, 164, 176, 189, 209, 228, 253, 274, 294, 311, 327, 342, 360, 377, 398, 418, 438, 455, 474}
	_ErrorCode_index_3 = [...]uint8{0, 20, 35, 51, 67, 79}
)

func (i ErrorCode) String() string {
	switch {
	case 0 <= i && i <= 48:
		return _ErrorCode_name_0[_ErrorCode_index_0[i]:_ErrorCode_index_0[i+1]]
	case 100 <= i && i <= 104:
		i -= 100
		return _ErrorCode_name_1[_ErrorCode_index_1[i]:_ErrorCode_index_1[i+1]]
	case 200 <= i && i <= 226:
		i -= 200
		return _ErrorCode_name_2[_ErrorCode_index_2[i]:_ErrorCode_index_2[i+1]]
	case 300 <= i && i <= 304:
		i -= 300
		return _ErrorCode_name_3[_ErrorCode_index_3[i]:_ErrorCode_index_3[i+1]]
	default:
		return "ErrorCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
