// Code generated by "stringer -type=Code"; DO NOT EDIT.

package klarerrs

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoPrefix-0]
	_ = x[SyntaxErrorPrefix-100]
	_ = x[WarningPrefix-300]
	_ = x[TypeErrorPrefix-400]
	_ = x[ReferenceErrorPrefix-500]
	_ = x[ModuleErrorPrefix-600]
}

const (
	_Code_name_0 = "NoPrefix"
	_Code_name_1 = "SyntaxErrorPrefix"
	_Code_name_2 = "WarningPrefix"
	_Code_name_3 = "TypeErrorPrefix"
	_Code_name_4 = "ReferenceErrorPrefix"
	_Code_name_5 = "ModuleErrorPrefix"
)

func (i Code) String() string {
	switch {
	case i == 0:
		return _Code_name_0
	case i == 100:
		return _Code_name_1
	case i == 300:
		return _Code_name_2
	case i == 400:
		return _Code_name_3
	case i == 500:
		return _Code_name_4
	case i == 600:
		return _Code_name_5
	default:
		return "Code(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
