package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type goStruct struct {
	name     string
	inherits []string
	fields   []*goStructField
	comment  string
}

type goStructField struct {
	name string
	// Types can include Go slice syntax
	typ         string
	optional    bool // Declared with ?: in TS or a union with null
	comment     string
	sideComment string
}

type writer struct {
	mm            *MetaModel
	symbols       symbolMap
	sortedSymbols []string
	files         map[string]*os.File // Keys don't have .go suffix
	largeStructs  map[string]struct{}
}

func (w *writer) writeStructs() {
	for _, name := range w.sortedSymbols {
		entry := w.symbols[name]
		s, ok := entry.decl.(*Structure)
		if !ok {
			continue
		}
		file := w.getFile(entry.category)
		goStr := w.toGoStruct(s)
		writeGoStruct(goStr, file)
	}
}

func (w *writer) getFile(baseName string) *os.File {
	if baseName == "" {
		baseName = "general"
	}
	if w.files == nil {
		w.files = make(map[string]*os.File)
	}
	f, ok := w.files[baseName]
	if !ok {
		var err error
		f, err = os.Create(filepath.Join(outDir, baseName+".go"))
		if err != nil {
			panic(err)
		}
		_, err = f.WriteString(`// Code generated by lsp/generate; DO NOT EDIT.
package lsp

import "github.com/ProCode-Software/klar/pkg/lsp/rpc"

`)
		if err != nil {
			panic(err)
		}
		w.files[baseName] = f
	}
	return f
}

func (w *writer) isLarge(name string) (isLarge bool) {
	_, ok := w.largeStructs[name]
	if ok {
		return true
	}
	if w.largeStructs == nil {
		w.largeStructs = make(map[string]struct{})
	}
	sym := w.symbols[name]
	defer func() {
		if isLarge {
			w.largeStructs[name] = struct{}{}
		}
	}()
	switch decl := sym.decl.(type) {
	case *Structure:
		return len(decl.Properties) > 5
	case *StructureLiteral:
		return len(decl.Properties) > 5
	}
	return false
}

var NullType = Type{Kind: KindBase, Name: string(Null)}

func (w *writer) toGoStruct(s *Structure) *goStruct {
	goStr := &goStruct{
		name:    s.Name,
		comment: toGoDocComment(s.Documentation, s.Deprecated),
		fields:  make([]*goStructField, len(s.Properties)),
	}
	// Inherited types
	for _, group := range [...][]Type{s.Extends, s.Mixins} {
		for _, t := range group {
			// No occurrences of this in LSP 3.18
			if t.Kind != KindReference {
				panic("can't extend non-reference type " + t.Name)
			}
			goStr.inherits = append(goStr.inherits, t.Name)
		}
	}
	// Props
	for i, prop := range s.Properties {
		f := &goStructField{
			name:     prop.Name,
			comment:  toGoDocComment(prop.Documentation, prop.Deprecated),
			optional: prop.Optional,
		}
		var needSideComment bool
		if prop.Type.Kind == KindOr {
			union, hasNull := w.convertUnion(prop.Type, &needSideComment)
			f.typ = union
			if hasNull {
				f.optional = true
			}
		} else {
			f.typ = w.typeToGoType(prop.Type, &needSideComment)
		}
		if f.optional && f.typ[0] != '*' && !shouldIndirect(f.typ) {
			f.typ = "*" + f.typ
		}
		if needSideComment {
			f.sideComment = toTSType(prop.Type)
		}
		goStr.fields[i] = f
	}
	return goStr
}

// Go doc lists need a newline before them, and each line indented.
// If the object is deprecated, add "Deprecated: " at the beginning of
// a new line.
func toGoDocComment(comment, deprecated string) string {
	var isList bool
	var b strings.Builder
	for line := range strings.Lines(comment) {
		if strings.HasPrefix(line, "- ") {
			line = "\t" + line
			if !isList {
				b.WriteByte('\n')
			}
			isList = true
		} else {
			isList = false
		}
		b.WriteString(line)
	}
	if deprecated != "" {
		if b.Len() > 0 {
			b.WriteByte('\n')
		}
		b.WriteString("Deprecated: ")
		b.WriteString(deprecated)
	}
	return b.String()
}

func (w *writer) typeToGoType(t Type, needSideComment *bool) string {
	switch t.Kind {
	case KindReference:
		// Generic types. Declared as type aliases in the meta model
		switch t.Name {
		case "LSPAny":
			return "any"
		case "LSPObject":
			return "map[string]any"
		case "LSPArray":
			return "[]any" // Unused as of LSP 3.18
		}
		if w.isLarge(t.Name) {
			return "*" + t.Name
		}
		return t.Name
	case KindBase:
		return baseTypeToGoType(BaseTypes(t.Name))
	case KindOr:
		res, _ := w.convertUnion(t, needSideComment)
		return res
	case KindAnd:
		panic("intersection types unimplemented")
	case KindArray:
		return "[]" + w.typeToGoType(*t.Element, needSideComment)
	case KindBooleanLiteral:
		*needSideComment = true
		return "bool"
	case KindStringLiteral:
		*needSideComment = true
		return "string"
	case KindStructLiteral:
		*needSideComment = true
		if len(t.Value.A().Properties) > 0 {
			panic("found field with type 'literal' (struct literal) with properties")
		}
		return "struct{}"
	case KindIntegerLiteral:
		*needSideComment = true
		if integerIsInt32 {
			return "int32"
		}
		return "int"
	case KindMap:
		var v string
		if t.Value.Curr() == 0 {
			v = "struct{}"
		} else {
			v = w.typeToGoType(t.Value.B().A(), needSideComment)
		}
		return fmt.Sprintf(
			"map[%s]%s", w.typeToGoType(*t.Key, needSideComment), v,
		)
	case KindTuple:
		*needSideComment = true
		singleType := t.Items[0]
		for _, item := range t.Items[1:] {
			if !item.Equal(singleType) {
				panic("tuple contains different types")
			}
		}
		return fmt.Sprintf(
			"[%d]%s", len(t.Items),
			w.typeToGoType(singleType, needSideComment),
		)
	default:
		panic("unhandled type kind: " + t.Kind)
	}
}

func baseTypeToGoType(typ BaseTypes) string {
	switch BaseTypes(typ) {
	case URI:
		return "URI"
	case DocumentUri:
		return "DocumentURI" // Go naming convention
	case Integer:
		if integerIsInt32 {
			return "int32"
		}
		return "int"
	case UInteger:
		return "uint32"
	case Decimal:
		return "float64"
	case RegExp:
		// TODO: An import would be required, but the RegExp base type is never
		// used within the spec as of 3.18
		return "regexp.Regexp"
	case String:
		return "string"
	case Boolean:
		return "bool"
	case Null:
		return "struct{}"
	default:
		panic("unhandled base type: " + string(typ))
	}
}

func (w *writer) convertUnion(t Type, needSideCmt *bool) (s string, hasNull bool) {
	if len(t.Items) < 2 {
		panic(fmt.Sprintf("union must have at least 2 items, got %d", len(t.Items)))
	}
	types := make([]string, 0, len(t.Items))
	for _, item := range t.Items {
		if item.Equal(NullType) {
			hasNull = true
			continue
		}
		types = append(types, w.typeToGoType(item, needSideCmt))
	}
	if hasNull || len(types) > 2 {
		*needSideCmt = true
	}
	var indirect string
	if hasNull {
		indirect = "*"
	}
	switch len(types) {
	case 1:
		typ := types[0]
		switch {
		case typ[0] == '*':
			return types[0], hasNull // Don't double-indirect
		case !shouldIndirect(typ):
			return typ, hasNull // Some primitives can be kept as values
		}
		return "*" + types[0], hasNull
	case 2:
		return fmt.Sprintf("%srpc.Union2[%s, %s]", indirect, types[0], types[1]), hasNull
	case 3:
		return fmt.Sprintf(
			"%srpc.Union3[%s, %s, %s]", indirect,
			types[0], types[1], types[2],
		), hasNull
	default:
		*needSideCmt = true
		return "any", hasNull
	}
}

func shouldIndirect(typ string) bool {
	switch typ {
	case "string", "any", "int", "int32", "uint32", "float64":
		return true
	default:
		return true
	}
}

func writeGoStruct(s *goStruct, file *os.File) {
	var buf bytes.Buffer
	if s.comment != "" {
		fmt.Fprintf(&buf, "/* %s */\n", s.comment)
	}
	fmt.Fprintf(&buf, "type %s struct {\n", s.name)
	for _, inh := range s.inherits {
		buf.WriteByte('\t')
		buf.WriteString(inh)
		buf.WriteByte('\n')
	}
	for _, f := range s.fields {
		if s.comment != "" {
			fmt.Fprintf(&buf, "\t/* %s */\n", s.comment)
		}
		goName := strings.ToUpper(f.name[:1]) + f.name[1:]
		fmt.Fprintf(&buf, "\t%s %s", goName, f.typ)

		// JSON struct tags
		jsonTags := f.name
		if f.optional {
			jsonTags += ",omitempty"
		}
		fmt.Fprintf(&buf, " `json:\"%s\"`", jsonTags)

		if f.sideComment != "" {
			fmt.Fprintf(&buf, " // %s", f.sideComment)
		}
		buf.WriteByte('\n')
	}
	buf.WriteString("}\n\n")
	if _, err := buf.WriteTo(file); err != nil {
		panic(err)
	}
}

func toTSType(t Type) string {
	switch t.Kind {
	case KindAnd:
		return joinTypes(t.Items, " & ")
	case KindBase:
		return t.Name
	case KindOr:
		return joinTypes(t.Items, " | ")
	case KindStringLiteral, KindBooleanLiteral, KindIntegerLiteral:
		b := t.Value.B()
		return fmt.Sprintf("%v", b.B())
	case KindReference:
		return t.Name
	case KindArray:
		return toTSType(*t.Element) + "[]"
	case KindTuple:
		return "[" + joinTypes(t.Items, ", ") + "]"
	case KindMap:
		var v string
		if t.Value.Curr() == 0 {
			v = "{}"
		} else {
			v = toTSType(t.Value.B().A())
		}
		return fmt.Sprintf("Record<%s, %s>", t.Key.Name, v)
	case KindStructLiteral:
		return "{}"
	}
	panic("unhandled: " + t.Kind)
}

func joinTypes(t []Type, sep string) string {
	var b strings.Builder
	for i, t := range t {
		if i > 0 {
			b.WriteString(sep)
		}
		b.WriteString(toTSType(t))
	}
	return b.String()
}

func (w *writer) writeTypeAlias(a *TypeAlias, file *os.File) {
	switch a.Name {
	case "LSPArray", "LSPAny", "LSPObject":
		return
	}
	buf := &bytes.Buffer{}
	if a.Documentation != "" || a.Deprecated != "" {
		fmt.Fprintf(buf, "/* %s */\n", toGoDocComment(a.Documentation, a.Deprecated))
	}
	var needSideCmt bool
	fmt.Fprintf(buf, "type %s = %s", a.Name, w.typeToGoType(a.Type, &needSideCmt))
	if needSideCmt {
		fmt.Fprintf(buf, " // %s", toTSType(a.Type))
	}
	buf.WriteString("\n\n")
	if _, err := buf.WriteTo(file); err != nil {
		panic(err)
	}
}

func (w *writer) writeEnum(e *Enumeration, file *os.File) {
	buf := &bytes.Buffer{}
	if e.Documentation != "" || e.Deprecated != "" {
		fmt.Fprintf(buf, "/* %s */\n", toGoDocComment(e.Documentation, e.Deprecated))
	}
	if e.Type.Name == "" {
		panic(fmt.Sprintf("empty base type for %q: %#v", e.Name, e.Type))
	}
	fmt.Fprintf(
		buf, "type %s %s\n\nconst (\n", e.Name,
		baseTypeToGoType(e.Type.Name),
	)
	for _, val := range e.Values {
		if val.Documentation != "" || val.Deprecated != "" {
			fmt.Fprintf(
				buf, "\t/* %s */\n",
				toGoDocComment(val.Documentation, val.Deprecated),
			)
		}
		fmt.Fprintf(buf, "\t%s %s = %v\n", val.Name, e.Name, val.Value)
	}
	buf.WriteString(")\n")
	if _, err := buf.WriteTo(file); err != nil {
		panic(err)
	}
}
