package main

import (
	"bytes"
	"cmp"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

type goStruct struct {
	name       string
	inherits   []string
	fields     []*goStructField
	desc       string
	deprecated string
}

type goStructField struct {
	name string
	// Types can include Go slice syntax
	typ         string
	nullable    bool // Declared with ?: in TS or a union with null
	optional    bool // Declared with ?:
	docs        string
	deprecated  string
	sideComment string
}

type writer struct {
	mm            *MetaModel
	symbols       symbolMap
	sortedSymbols []string
	files         map[string]*bytes.Buffer // Keys don't have .go suffix
	largeStructs  map[string]struct{}
	currCategory  string
}

func (w *writer) writeStructs() {
	for _, name := range w.sortedSymbols {
		entry := w.symbols[name]
		s, ok := entry.decl.(*Structure)
		if !ok {
			continue
		}
		file := w.getFile(entry.category)
		w.currCategory = entry.category
		goStr := w.toGoStruct(s)
		writeGoStruct(goStr, file)
	}
}

func (w *writer) getFile(baseName string) *bytes.Buffer {
	baseName = cmp.Or(baseName, w.currCategory, "basic")
	if w.files == nil {
		w.files = make(map[string]*bytes.Buffer)
	}
	f, ok := w.files[baseName]
	if !ok {
		f = &bytes.Buffer{}
		f.WriteString(`// Code generated by lsp/generate; DO NOT EDIT.
package lsp

import "github.com/ProCode-Software/klar/pkg/lsp/rpc"

`)
		w.files[baseName] = f
	}
	return f
}

func (w *writer) isLarge(name string) (isLarge bool) {
	_, ok := w.largeStructs[name]
	if ok {
		return true
	}
	if w.largeStructs == nil {
		w.largeStructs = make(map[string]struct{})
	}
	sym := w.symbols[name]
	defer func() {
		if isLarge {
			w.largeStructs[name] = struct{}{}
		}
	}()
	switch decl := sym.decl.(type) {
	case *Structure:
		return len(decl.Properties) > 5
	case *StructureLiteral:
		return len(decl.Properties) > 5
	}
	return false
}

var NullType = Type{Kind: KindBase, Name: string(Null)}

func (w *writer) toGoStruct(s *Structure) *goStruct {
	goStr := &goStruct{
		name:       s.Name,
		desc:       s.Documentation,
		deprecated: s.Deprecated,
		fields:     make([]*goStructField, len(s.Properties)),
	}
	// Inherited types
	for _, group := range [...][]Type{s.Extends, s.Mixins} {
		for _, t := range group {
			// No occurrences of this in LSP 3.18
			if t.Kind != KindReference {
				panic("can't extend non-reference type " + t.Name)
			}
			goStr.inherits = append(goStr.inherits, t.Name)
		}
	}
	// Props
	for i, prop := range s.Properties {
		f := &goStructField{
			name:       prop.Name,
			docs:       prop.Documentation,
			deprecated: prop.Deprecated,
			optional:   prop.Optional,
		}
		var needSideComment bool
		if prop.Type.Kind == KindOr {
			union, hasNull := w.convertUnion(prop.Type, &needSideComment)
			f.typ = union
			if hasNull {
				f.nullable = true
			}
		} else {
			f.typ = w.typeToGoType(prop.Type, &needSideComment)
		}
		if (f.nullable || f.optional) && f.typ[0] != '*' && shouldIndirect(f.typ) {
			f.typ = "*" + f.typ
		}
		if needSideComment {
			f.sideComment = toTSType(prop.Type)
		}
		goStr.fields[i] = f
	}
	return goStr
}

func (w *writer) typeToGoType(t Type, needSideComment *bool) string {
	switch t.Kind {
	case KindReference:
		// Generic types. Declared as type aliases in the meta model
		switch t.Name {
		case "LSPAny":
			return "any"
		case "LSPObject":
			return "map[string]any"
		case "LSPArray":
			return "[]any" // Unused as of LSP 3.18
		}
		if w.isLarge(t.Name) {
			return "*" + t.Name
		}
		return t.Name
	case KindBase:
		return baseTypeToGoType(BaseTypes(t.Name))
	case KindOr:
		res, _ := w.convertUnion(t, needSideComment)
		return res
	case KindAnd:
		panic("intersection types unimplemented")
	case KindArray:
		return "[]" + w.typeToGoType(*t.Element, needSideComment)
	case KindBooleanLiteral:
		*needSideComment = true
		return "bool"
	case KindStringLiteral:
		*needSideComment = true
		return "string"
	case KindStructLiteral:
		*needSideComment = true
		if len(t.Value.A().Properties) > 0 {
			panic("found field with type 'literal' (struct literal) with properties")
		}
		return "struct{}"
	case KindIntegerLiteral:
		*needSideComment = true
		if integerIsInt32 {
			return "int32"
		}
		return "int"
	case KindMap:
		return fmt.Sprintf(
			"map[%s]%s", w.typeToGoType(*t.Key, needSideComment),
			w.typeToGoType(t.Value.A(), needSideComment),
		)
	case KindTuple:
		*needSideComment = true
		singleType := t.Items[0]
		for _, item := range t.Items[1:] {
			if !item.Equal(singleType) {
				panic("tuple contains different types")
			}
		}
		return fmt.Sprintf(
			"[%d]%s", len(t.Items),
			w.typeToGoType(singleType, needSideComment),
		)
	default:
		panic("unhandled type kind: " + t.Kind)
	}
}

func baseTypeToGoType(typ BaseTypes) string {
	switch typ {
	case URI:
		return "URI"
	case DocumentUri:
		return "DocumentURI" // Go naming convention
	case Integer:
		if integerIsInt32 {
			return "int32"
		}
		return "int"
	case UInteger:
		return "uint32"
	case Decimal:
		return "float64"
	case RegExp:
		// TODO: An import would be required, but the RegExp base type is never
		// used within the spec as of 3.18
		return "regexp.Regexp"
	case String:
		return "string"
	case Boolean:
		return "bool"
	case Null:
		return "struct{}"
	default:
		panic("unhandled base type: " + string(typ))
	}
}

func (w *writer) convertUnion(t Type, needSideCmt *bool) (s string, hasNull bool) {
	if len(t.Items) < 2 {
		panic(fmt.Sprintf("union must have at least 2 items, got %d", len(t.Items)))
	}
	types := make([]string, 0, len(t.Items))
	for _, item := range t.Items {
		if item.Equal(NullType) {
			hasNull = true
			continue
		}
		types = append(types, w.typeToGoType(item, needSideCmt))
	}
	if hasNull || len(types) > 2 {
		*needSideCmt = true
	}
	var indirect string
	if hasNull {
		indirect = "*"
	}
	switch len(types) {
	case 1:
		typ := types[0]
		switch {
		case typ[0] == '*':
			return types[0], hasNull // Don't double-indirect
		case !shouldIndirect(typ):
			return typ, hasNull // Some primitives can be kept as values
		}
		return "*" + types[0], hasNull
	case 2:
		return fmt.Sprintf("%srpc.Union2[%s, %s]", indirect, types[0], types[1]), hasNull
	case 3:
		return fmt.Sprintf(
			"%srpc.Union3[%s, %s, %s]", indirect,
			types[0], types[1], types[2],
		), hasNull
	default:
		*needSideCmt = true
		return "any", hasNull
	}
}

func shouldIndirect(typ string) bool {
	switch typ {
	case "string", "any", "int", "int32", "uint32", "float64":
		return false
	default:
		return !strings.HasPrefix(typ, "[]") // Don't indirect slices
	}
}

func toGoName(s string) string {
	return strings.ToUpper(s[:1]) + s[1:]
}

func writeGoStruct(s *goStruct, buf *bytes.Buffer) {
	writeComment(buf, s.desc, s.deprecated, false)
	fmt.Fprintf(buf, "type %s struct {\n", s.name)
	for _, inh := range s.inherits {
		buf.WriteByte('\t')
		buf.WriteString(inh)
		buf.WriteByte('\n')
	}
	for _, f := range s.fields {
		writeComment(buf, f.docs, f.deprecated, true)
		fmt.Fprintf(buf, "\t%s %s", toGoName(f.name), f.typ)

		// JSON struct tags
		jsonTags := f.name
		if f.optional {
			jsonTags += ",omitempty"
		}
		fmt.Fprintf(buf, " `json:\"%s\"`", jsonTags)

		if f.sideComment != "" {
			fmt.Fprintf(buf, " // %s", f.sideComment)
		}
		buf.WriteByte('\n')
	}
	buf.WriteString("}\n\n")
}

func toTSType(t Type) string {
	switch t.Kind {
	case KindAnd:
		return joinTypes(t.Items, " & ")
	case KindBase:
		return t.Name
	case KindOr:
		return joinTypes(t.Items, " | ")
	case KindStringLiteral:
		return fmt.Sprintf("%q", t.Value.B())
	case KindBooleanLiteral, KindIntegerLiteral:
		return fmt.Sprintf("%v", t.Value.B())
	case KindReference:
		return t.Name
	case KindArray:
		return toTSType(*t.Element) + "[]"
	case KindTuple:
		return "[" + joinTypes(t.Items, ", ") + "]"
	case KindMap:
		return fmt.Sprintf("Record<%s, %s>", t.Key.Name, toTSType(t.Value.A()))
	case KindStructLiteral:
		return "{}"
	}
	panic("unhandled: " + t.Kind)
}

func joinTypes(t []Type, sep string) string {
	var b strings.Builder
	for i, t := range t {
		if i > 0 {
			b.WriteString(sep)
		}
		b.WriteString(toTSType(t))
	}
	return b.String()
}

func (w *writer) writeTypeAlias(a *TypeAlias, buf *bytes.Buffer) {
	switch a.Name {
	case "LSPArray", "LSPAny", "LSPObject":
		return
	}
	writeComment(buf, a.Documentation, a.Deprecated, false)
	var needSideCmt bool
	fmt.Fprintf(buf, "type %s = %s", a.Name, w.typeToGoType(a.Type, &needSideCmt))
	if needSideCmt {
		fmt.Fprintf(buf, " // %s", toTSType(a.Type))
	}
	buf.WriteString("\n\n")
}

func (w *writer) writeEnum(e *Enumeration, buf *bytes.Buffer) {
	writeComment(buf, e.Documentation, e.Deprecated, false)
	fmt.Fprintf(
		buf, "type %s %s\n\nconst (\n", e.Name,
		baseTypeToGoType(e.Type.Name),
	)
	// Strip some common suffixes from each variant so the names are cleaner
	shortVariantName := strings.NewReplacer("Kind", "", "Filter", "", "Mode", "").
		Replace(e.Name)
	for _, val := range e.Values {
		writeComment(buf, val.Documentation, val.Deprecated, true)
		itemName := shortVariantName + toGoName(val.Name)
		var valStr string
		if s, ok := val.Value.(string); ok {
			valStr = strconv.Quote(s)
		} else {
			valStr = fmt.Sprintf("%v", val.Value)
		}
		fmt.Fprintf(buf, "\t%s %s = %s\n", itemName, e.Name, valStr)
	}
	buf.WriteString(")\n")
}

var referenceRegex = regexp.MustCompile(`\{@link ([^}\s]+)([^}]*)\}`)

// Go doc lists need a newline before them, and each line indented.
// If the object is deprecated, add "Deprecated: " at the beginning of
// a new line.
func writeComment(buf *bytes.Buffer, doc, deprecated string, indent bool) {
	if doc == "" && deprecated == "" {
		return
	}
	writeIndent := func() {
		if indent {
			buf.WriteByte('\t')
		}
	}

	var isList bool
	for line := range strings.Lines(doc) {
		// Replace {@link Object} with [Object] syntax for Go docs
		line = referenceRegex.ReplaceAllStringFunc(line, func(ref string) string {
			subs := referenceRegex.FindStringSubmatchIndex(ref)
			symbol := ref[subs[2]:subs[3]]
			text := ref[subs[4]:subs[5]]
			if text != "" {
				return fmt.Sprintf("%s [%s]", text, symbol)
			}
			return "[" + symbol + "]"
		})

		writeIndent()
		buf.WriteString("// ")
		if strings.HasPrefix(line, "- ") {
			line = "\t" + line
			if !isList {
				buf.WriteByte('\n')
				writeIndent()
				buf.WriteString("// ")
			}
			isList = true
		} else {
			isList = false
		}
		buf.WriteString(line)
	}
	if doc != "" {
		buf.WriteByte('\n') // Ending newline
	}

	if deprecated != "" {
		writeIndent()
		buf.WriteString("// Deprecated: ")
		buf.WriteString(deprecated)
		buf.WriteByte('\n')
	}
}

func (w *writer) writeFiles(dir string) {
	for basename, buf := range w.files {
		//nolint:gosec // G703 - this is a manually-run program
		if err := os.WriteFile(
			filepath.Join(dir, basename+".go"),
			buf.Bytes(), 0o644,
		); err != nil {
			panic(err)
		}
	}
}
