package main

import (
	"os"
	"regexp"
	"strings"
)

const header = `// Code generated by astgen; DO NOT EDIT.

package ast

import (
	"github.com/ProCode-Software/klar/internal/lexer"
	"github.com/ProCode-Software/klar/internal/ranges"
)

`

func main() {
	var (
		input     = os.Args[1]
		output    = os.Args[2]
		text, err = os.ReadFile(input)
		b         = strings.Builder{}
	)
	if err != nil {
		panic(err)
	}
	b.WriteString(header)
	re := regexp.MustCompile(`func \((.+)\) Kind\(\)`)
	for _, match := range re.FindAllSubmatch(text, -1) {
		name := string(match[1])
		b.WriteString(`func (e ` + name + ") GetRange() ranges.Range { return e.BaseNode.Range }\n")
		b.WriteString(`func (e ` + name + `) SetPos(start, end lexer.Position) Node {
	e.BaseNode.Range.Start, e.BaseNode.Range.End = start, end
	return e
}
`)
	}
	err = os.WriteFile(output, []byte(b.String()), 0o644)
	if err != nil {
		panic(err)
	}
}
