package main

import (
	"bytes"
	"go/format"
	"go/types"
	"log"
	"os"
	"text/template"
)

type (
	NodeList  = []*types.TypeName
	Package   = *types.Package
	Generator func(*bytes.Buffer, NodeList, Package) error
)

var generators = []Generator{
	GenerateEqual, GenerateWalk,
}

var outputs = []string{"equal_nodes.go", "walk_nodes.go"}

func main() {
	nodes, pkg, err := GetASTNodes()
	if err != nil {
		log.Fatalf("failed to get AST nodes: %v", err)
	}
	for i, gen := range generators {
		buf := &bytes.Buffer{}
		if err := gen(buf, nodes, pkg); err != nil {
			log.Fatalf("generator #%d failed: %v", i, err)
		}
		formatted, err := format.Source(buf.Bytes())
		if err != nil {
			log.Fatalf("failed to format file %s: %v", outputs[i], err)
		}
		if err := os.WriteFile(outputs[i], formatted, 0644); err != nil {
			log.Fatalf("failed to write file %s: %v", outputs[i], err)
		}
	}
}

var templateFuncs = template.FuncMap{
	"IsNode":                IsNode,
	"IsStatement":           IsStatement,
	"IsExpression":          IsExpression,
	"IsAssignable":          IsAssignable,
	"IsType":                IsType,
	"IsTypeDeclaration":     IsTypeDeclaration,
	"IsModifierDeclaration": IsModifierDeclaration,
	"IsDestructure":         IsDestructure,
	"ToStruct": func(t *types.TypeName) *types.Struct {
		return t.Type().Underlying().(*types.Struct)
	},
	"IsSlice": func(t types.Type) bool {
		_, ok := t.(*types.Slice)
		return ok
	},
	"HasName": func(t types.Type, name string) bool {
		// Unwrap pointer if necessary (handles *Identifier)
		if ptr, ok := t.(*types.Pointer); ok {
			t = ptr.Elem()
		}
		// Check for named types (structs, aliases, etc.)
		if named, ok := t.(*types.Named); ok {
			obj := named.Obj()
			// Check simple name (e.g., "Identifier")
			if obj.Name() == name {
				return true
			}
			// Check package-qualified name (e.g., "ast.Identifier")
			if obj.Pkg() != nil && obj.Pkg().Name()+"."+obj.Name() == name {
				return true
			}
		}
		return false
	},
}

func newTemplate(name, s string) *template.Template {
	t, err := template.New(name).Funcs(templateFuncs).Parse(s)
	if err != nil {
		log.Fatalf("failed to parse template %s: %v", name, err)
	}
	return t
}

func getFile(name string) *os.File {
	file, err := os.Create(name)
	if err != nil {
		log.Fatalf("failed to create file %s: %v", name, err)
	}
	return file
}

const Header = `// Code generated by asttempl. DO NOT EDIT.
package ast
`
