// Code generated by lsp/generate; DO NOT EDIT.
package lsp

import "github.com/ProCode-Software/klar/pkg/lsp/rpc"

/*
A special text edit with an additional change annotation.

@since 3.16.0.
*/
type AnnotatedTextEdit struct {
	TextEdit
	/*
		A special text edit with an additional change annotation.

		@since 3.16.0.
	*/
	AnnotationId ChangeAnnotationIdentifier `json:"annotationId"`
}

// @since 3.16.0
type CallHierarchyClientCapabilities struct {
	// @since 3.16.0
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
}

/*
Represents an incoming call, e.g. a caller of a method or constructor.

@since 3.16.0
*/
type CallHierarchyIncomingCall struct {
	/*
		Represents an incoming call, e.g. a caller of a method or constructor.

		@since 3.16.0
	*/
	From *CallHierarchyItem `json:"from"`
	/*
		Represents an incoming call, e.g. a caller of a method or constructor.

		@since 3.16.0
	*/
	FromRanges []Range `json:"fromRanges"`
}

/*
Call hierarchy options used during static registration.

@since 3.16.0
*/
type CallHierarchyOptions struct {
	WorkDoneProgressOptions
}

/*
Represents an outgoing call, e.g. calling a getter from a method or a method from a constructor etc.

@since 3.16.0
*/
type CallHierarchyOutgoingCall struct {
	/*
		Represents an outgoing call, e.g. calling a getter from a method or a method from a constructor etc.

		@since 3.16.0
	*/
	To *CallHierarchyItem `json:"to"`
	/*
		Represents an outgoing call, e.g. calling a getter from a method or a method from a constructor etc.

		@since 3.16.0
	*/
	FromRanges []Range `json:"fromRanges"`
}

// @since 3.18.0
type ChangeAnnotationsSupportOptions struct {
	// @since 3.18.0
	GroupsOnLabel *bool `json:"groupsOnLabel,omitempty"`
}

// Defines the capabilities provided by the client.
type ClientCapabilities struct {
	// Defines the capabilities provided by the client.
	Workspace *WorkspaceClientCapabilities `json:"workspace,omitempty"`
	// Defines the capabilities provided by the client.
	TextDocument *TextDocumentClientCapabilities `json:"textDocument,omitempty"`
	// Defines the capabilities provided by the client.
	NotebookDocument *NotebookDocumentClientCapabilities `json:"notebookDocument,omitempty"`
	// Defines the capabilities provided by the client.
	Window *WindowClientCapabilities `json:"window,omitempty"`
	// Defines the capabilities provided by the client.
	General *GeneralClientCapabilities `json:"general,omitempty"`
	// Defines the capabilities provided by the client.
	Experimental any `json:"experimental,omitempty"`
}

// @since 3.18.0
type ClientCodeActionKindOptions struct {
	// @since 3.18.0
	ValueSet []CodeActionKind `json:"valueSet"`
}

// @since 3.18.0
type ClientCodeActionLiteralOptions struct {
	// @since 3.18.0
	CodeActionKind ClientCodeActionKindOptions `json:"codeActionKind"`
}

// @since 3.18.0
type ClientCodeActionResolveOptions struct {
	// @since 3.18.0
	Properties []string `json:"properties"`
}

// @since 3.18.0
type ClientCodeLensResolveOptions struct {
	// @since 3.18.0
	Properties []string `json:"properties"`
}

// @since 3.18.0
type ClientCompletionItemInsertTextModeOptions struct {
	// @since 3.18.0
	ValueSet []InsertTextMode `json:"valueSet"`
}

// @since 3.18.0
type ClientCompletionItemOptions struct {
	// @since 3.18.0
	SnippetSupport *bool `json:"snippetSupport,omitempty"`
	// @since 3.18.0
	CommitCharactersSupport *bool `json:"commitCharactersSupport,omitempty"`
	// @since 3.18.0
	DocumentationFormat *[]MarkupKind `json:"documentationFormat,omitempty"`
	// @since 3.18.0
	DeprecatedSupport *bool `json:"deprecatedSupport,omitempty"`
	// @since 3.18.0
	PreselectSupport *bool `json:"preselectSupport,omitempty"`
	// @since 3.18.0
	TagSupport *CompletionItemTagOptions `json:"tagSupport,omitempty"`
	// @since 3.18.0
	InsertReplaceSupport *bool `json:"insertReplaceSupport,omitempty"`
	// @since 3.18.0
	ResolveSupport *ClientCompletionItemResolveOptions `json:"resolveSupport,omitempty"`
	// @since 3.18.0
	InsertTextModeSupport *ClientCompletionItemInsertTextModeOptions `json:"insertTextModeSupport,omitempty"`
	// @since 3.18.0
	LabelDetailsSupport *bool `json:"labelDetailsSupport,omitempty"`
}

// @since 3.18.0
type ClientCompletionItemOptionsKind struct {
	// @since 3.18.0
	ValueSet *[]CompletionItemKind `json:"valueSet,omitempty"`
}

// @since 3.18.0
type ClientCompletionItemResolveOptions struct {
	// @since 3.18.0
	Properties []string `json:"properties"`
}

// @since 3.18.0
type ClientDiagnosticsTagOptions struct {
	// @since 3.18.0
	ValueSet []DiagnosticTag `json:"valueSet"`
}

// @since 3.18.0
type ClientFoldingRangeKindOptions struct {
	// @since 3.18.0
	ValueSet *[]FoldingRangeKind `json:"valueSet,omitempty"`
}

// @since 3.18.0
type ClientFoldingRangeOptions struct {
	// @since 3.18.0
	CollapsedText *bool `json:"collapsedText,omitempty"`
}

/*
Information about the client

@since 3.15.0
@since 3.18.0 ClientInfo type name added.
*/
type ClientInfo struct {
	/*
		Information about the client

		@since 3.15.0
		@since 3.18.0 ClientInfo type name added.
	*/
	Name string `json:"name"`
	/*
		Information about the client

		@since 3.15.0
		@since 3.18.0 ClientInfo type name added.
	*/
	Version string `json:"version,omitempty"`
}

// @since 3.18.0
type ClientInlayHintResolveOptions struct {
	// @since 3.18.0
	Properties []string `json:"properties"`
}

// @since 3.18.0
type ClientSemanticTokensRequestFullDelta struct {
	// @since 3.18.0
	Delta *bool `json:"delta,omitempty"`
}

// @since 3.18.0
type ClientSemanticTokensRequestOptions struct {
	// @since 3.18.0
	Range *rpc.Union2[bool, struct{}] `json:"range,omitempty"` // boolean | {}
	// @since 3.18.0
	Full *rpc.Union2[bool, ClientSemanticTokensRequestFullDelta] `json:"full,omitempty"`
}

// @since 3.18.0
type ClientShowMessageActionItemOptions struct {
	// @since 3.18.0
	AdditionalPropertiesSupport *bool `json:"additionalPropertiesSupport,omitempty"`
}

// @since 3.18.0
type ClientSignatureInformationOptions struct {
	// @since 3.18.0
	DocumentationFormat *[]MarkupKind `json:"documentationFormat,omitempty"`
	// @since 3.18.0
	ParameterInformation *ClientSignatureParameterInformationOptions `json:"parameterInformation,omitempty"`
	// @since 3.18.0
	ActiveParameterSupport *bool `json:"activeParameterSupport,omitempty"`
	// @since 3.18.0
	NoActiveParameterSupport *bool `json:"noActiveParameterSupport,omitempty"`
}

// @since 3.18.0
type ClientSignatureParameterInformationOptions struct {
	// @since 3.18.0
	LabelOffsetSupport *bool `json:"labelOffsetSupport,omitempty"`
}

// @since 3.18.0
type ClientSymbolKindOptions struct {
	// @since 3.18.0
	ValueSet *[]SymbolKind `json:"valueSet,omitempty"`
}

// @since 3.18.0
type ClientSymbolResolveOptions struct {
	// @since 3.18.0
	Properties []string `json:"properties"`
}

// @since 3.18.0
type ClientSymbolTagOptions struct {
	// @since 3.18.0
	ValueSet []SymbolTag `json:"valueSet"`
}

/*
Contains additional diagnostic information about the context in which
a  code action [CodeActionProvider.provideCodeActions] is run.
*/
type CodeActionContext struct {
	/*
		Contains additional diagnostic information about the context in which
		a  code action [CodeActionProvider.provideCodeActions] is run.
	*/
	Diagnostics []*Diagnostic `json:"diagnostics"`
	/*
		Contains additional diagnostic information about the context in which
		a  code action [CodeActionProvider.provideCodeActions] is run.
	*/
	Only *[]CodeActionKind `json:"only,omitempty"`
	/*
		Contains additional diagnostic information about the context in which
		a  code action [CodeActionProvider.provideCodeActions] is run.
	*/
	TriggerKind *CodeActionTriggerKind `json:"triggerKind,omitempty"`
}

/*
Captures why the code action is currently disabled.

@since 3.18.0
*/
type CodeActionDisabled struct {
	/*
		Captures why the code action is currently disabled.

		@since 3.18.0
	*/
	Reason string `json:"reason"`
}

/*
Documentation for a class of code actions.

@since 3.18.0
*/
type CodeActionKindDocumentation struct {
	/*
		Documentation for a class of code actions.

		@since 3.18.0
	*/
	Kind CodeActionKind `json:"kind"`
	/*
		Documentation for a class of code actions.

		@since 3.18.0
	*/
	Command Command `json:"command"`
}

// Provider options for a [CodeActionRequest].
type CodeActionOptions struct {
	WorkDoneProgressOptions
	// Provider options for a [CodeActionRequest].
	CodeActionKinds *[]CodeActionKind `json:"codeActionKinds,omitempty"`
	// Provider options for a [CodeActionRequest].
	Documentation *[]CodeActionKindDocumentation `json:"documentation,omitempty"`
	// Provider options for a [CodeActionRequest].
	ResolveProvider *bool `json:"resolveProvider,omitempty"`
}

/*
Structure to capture a description for an error code.

@since 3.16.0
*/
type CodeDescription struct {
	/*
		Structure to capture a description for an error code.

		@since 3.16.0
	*/
	Href URI `json:"href"`
}

// Code Lens provider options of a [CodeLensRequest].
type CodeLensOptions struct {
	WorkDoneProgressOptions
	// Code Lens provider options of a [CodeLensRequest].
	ResolveProvider *bool `json:"resolveProvider,omitempty"`
}

// Represents a color in RGBA space.
type Color struct {
	// Represents a color in RGBA space.
	Red float64 `json:"red"`
	// Represents a color in RGBA space.
	Green float64 `json:"green"`
	// Represents a color in RGBA space.
	Blue float64 `json:"blue"`
	// Represents a color in RGBA space.
	Alpha float64 `json:"alpha"`
}

// Represents a color range from a document.
type ColorInformation struct {
	// Represents a color range from a document.
	Range Range `json:"range"`
	// Represents a color range from a document.
	Color Color `json:"color"`
}

type ColorPresentation struct {
	Label               string      `json:"label"`
	TextEdit            *TextEdit   `json:"textEdit,omitempty"`
	AdditionalTextEdits *[]TextEdit `json:"additionalTextEdits,omitempty"`
}

// Completion client capabilities
type CompletionClientCapabilities struct {
	// Completion client capabilities
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
	// Completion client capabilities
	CompletionItem *ClientCompletionItemOptions `json:"completionItem,omitempty"`
	// Completion client capabilities
	CompletionItemKind *ClientCompletionItemOptionsKind `json:"completionItemKind,omitempty"`
	// Completion client capabilities
	InsertTextMode *InsertTextMode `json:"insertTextMode,omitempty"`
	// Completion client capabilities
	ContextSupport *bool `json:"contextSupport,omitempty"`
	// Completion client capabilities
	CompletionList *CompletionListCapabilities `json:"completionList,omitempty"`
}

// Contains additional information about the context in which a completion request is triggered.
type CompletionContext struct {
	// Contains additional information about the context in which a completion request is triggered.
	TriggerKind CompletionTriggerKind `json:"triggerKind"`
	// Contains additional information about the context in which a completion request is triggered.
	TriggerCharacter string `json:"triggerCharacter,omitempty"`
}

/*
In many cases the items of an actual completion result share the same
value for properties like `commitCharacters` or the range of a text
edit. A completion list can therefore define item defaults which will
be used if a completion item itself doesn't specify the value.

If a completion list specifies a default value and a completion item
also specifies a corresponding value, the rules for combining these are
defined by `applyKinds` (if the client supports it), defaulting to
ApplyKind.Replace.

Servers are only allowed to return default values if the client
signals support for this via the `completionList.itemDefaults`
capability.

@since 3.17.0
*/
type CompletionItemDefaults struct {
	/*
		In many cases the items of an actual completion result share the same
		value for properties like `commitCharacters` or the range of a text
		edit. A completion list can therefore define item defaults which will
		be used if a completion item itself doesn't specify the value.

		If a completion list specifies a default value and a completion item
		also specifies a corresponding value, the rules for combining these are
		defined by `applyKinds` (if the client supports it), defaulting to
		ApplyKind.Replace.

		Servers are only allowed to return default values if the client
		signals support for this via the `completionList.itemDefaults`
		capability.

		@since 3.17.0
	*/
	CommitCharacters *[]string `json:"commitCharacters,omitempty"`
	/*
		In many cases the items of an actual completion result share the same
		value for properties like `commitCharacters` or the range of a text
		edit. A completion list can therefore define item defaults which will
		be used if a completion item itself doesn't specify the value.

		If a completion list specifies a default value and a completion item
		also specifies a corresponding value, the rules for combining these are
		defined by `applyKinds` (if the client supports it), defaulting to
		ApplyKind.Replace.

		Servers are only allowed to return default values if the client
		signals support for this via the `completionList.itemDefaults`
		capability.

		@since 3.17.0
	*/
	EditRange *rpc.Union2[Range, EditRangeWithInsertReplace] `json:"editRange,omitempty"`
	/*
		In many cases the items of an actual completion result share the same
		value for properties like `commitCharacters` or the range of a text
		edit. A completion list can therefore define item defaults which will
		be used if a completion item itself doesn't specify the value.

		If a completion list specifies a default value and a completion item
		also specifies a corresponding value, the rules for combining these are
		defined by `applyKinds` (if the client supports it), defaulting to
		ApplyKind.Replace.

		Servers are only allowed to return default values if the client
		signals support for this via the `completionList.itemDefaults`
		capability.

		@since 3.17.0
	*/
	InsertTextFormat *InsertTextFormat `json:"insertTextFormat,omitempty"`
	/*
		In many cases the items of an actual completion result share the same
		value for properties like `commitCharacters` or the range of a text
		edit. A completion list can therefore define item defaults which will
		be used if a completion item itself doesn't specify the value.

		If a completion list specifies a default value and a completion item
		also specifies a corresponding value, the rules for combining these are
		defined by `applyKinds` (if the client supports it), defaulting to
		ApplyKind.Replace.

		Servers are only allowed to return default values if the client
		signals support for this via the `completionList.itemDefaults`
		capability.

		@since 3.17.0
	*/
	InsertTextMode *InsertTextMode `json:"insertTextMode,omitempty"`
	/*
		In many cases the items of an actual completion result share the same
		value for properties like `commitCharacters` or the range of a text
		edit. A completion list can therefore define item defaults which will
		be used if a completion item itself doesn't specify the value.

		If a completion list specifies a default value and a completion item
		also specifies a corresponding value, the rules for combining these are
		defined by `applyKinds` (if the client supports it), defaulting to
		ApplyKind.Replace.

		Servers are only allowed to return default values if the client
		signals support for this via the `completionList.itemDefaults`
		capability.

		@since 3.17.0
	*/
	Data any `json:"data,omitempty"`
}

/*
Additional details for a completion item label.

@since 3.17.0
*/
type CompletionItemLabelDetails struct {
	/*
		Additional details for a completion item label.

		@since 3.17.0
	*/
	Detail string `json:"detail,omitempty"`
	/*
		Additional details for a completion item label.

		@since 3.17.0
	*/
	Description string `json:"description,omitempty"`
}

// @since 3.18.0
type CompletionItemTagOptions struct {
	// @since 3.18.0
	ValueSet []CompletionItemTag `json:"valueSet"`
}

/*
Represents a collection of  completion items [CompletionItem] to be presented
in the editor.
*/
type CompletionList struct {
	/*
		Represents a collection of  completion items [CompletionItem] to be presented
		in the editor.
	*/
	IsIncomplete bool `json:"isIncomplete"`
	/*
		Represents a collection of  completion items [CompletionItem] to be presented
		in the editor.
	*/
	ItemDefaults *CompletionItemDefaults `json:"itemDefaults,omitempty"`
	/*
		Represents a collection of  completion items [CompletionItem] to be presented
		in the editor.
	*/
	ApplyKind *CompletionItemApplyKinds `json:"applyKind,omitempty"`
	/*
		Represents a collection of  completion items [CompletionItem] to be presented
		in the editor.
	*/
	Items []*CompletionItem `json:"items"`
}

/*
The client supports the following `CompletionList` specific
capabilities.

@since 3.17.0
*/
type CompletionListCapabilities struct {
	/*
		The client supports the following `CompletionList` specific
		capabilities.

		@since 3.17.0
	*/
	ItemDefaults *[]string `json:"itemDefaults,omitempty"`
	/*
		The client supports the following `CompletionList` specific
		capabilities.

		@since 3.17.0
	*/
	ApplyKindSupport *bool `json:"applyKindSupport,omitempty"`
}

// Completion options.
type CompletionOptions struct {
	WorkDoneProgressOptions
	// Completion options.
	TriggerCharacters *[]string `json:"triggerCharacters,omitempty"`
	// Completion options.
	AllCommitCharacters *[]string `json:"allCommitCharacters,omitempty"`
	// Completion options.
	ResolveProvider *bool `json:"resolveProvider,omitempty"`
	// Completion options.
	CompletionItem *ServerCompletionItemOptions `json:"completionItem,omitempty"`
}

// Options to create a file.
type CreateFileOptions struct {
	// Options to create a file.
	Overwrite *bool `json:"overwrite,omitempty"`
	// Options to create a file.
	IgnoreIfExists *bool `json:"ignoreIfExists,omitempty"`
}

type DeclarationOptions struct {
	WorkDoneProgressOptions
}

// Server Capabilities for a [DefinitionRequest].
type DefinitionOptions struct {
	WorkDoneProgressOptions
}

// Delete file options
type DeleteFileOptions struct {
	// Delete file options
	Recursive *bool `json:"recursive,omitempty"`
	// Delete file options
	IgnoreIfNotExists *bool `json:"ignoreIfNotExists,omitempty"`
}

/*
Client capabilities specific to diagnostic pull requests.

@since 3.17.0
*/
type DiagnosticClientCapabilities struct {
	DiagnosticsCapabilities
	/*
		Client capabilities specific to diagnostic pull requests.

		@since 3.17.0
	*/
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
	/*
		Client capabilities specific to diagnostic pull requests.

		@since 3.17.0
	*/
	RelatedDocumentSupport *bool `json:"relatedDocumentSupport,omitempty"`
	/*
		Client capabilities specific to diagnostic pull requests.

		@since 3.17.0
	*/
	MarkupMessageSupport *bool `json:"markupMessageSupport,omitempty"`
}

/*
Diagnostic options.

@since 3.17.0
*/
type DiagnosticOptions struct {
	WorkDoneProgressOptions
	/*
		Diagnostic options.

		@since 3.17.0
	*/
	Identifier string `json:"identifier,omitempty"`
	/*
		Diagnostic options.

		@since 3.17.0
	*/
	InterFileDependencies bool `json:"interFileDependencies"`
	/*
		Diagnostic options.

		@since 3.17.0
	*/
	WorkspaceDiagnostics bool `json:"workspaceDiagnostics"`
}

// General diagnostics capabilities for pull and push model.
type DiagnosticsCapabilities struct {
	// General diagnostics capabilities for pull and push model.
	RelatedInformation *bool `json:"relatedInformation,omitempty"`
	// General diagnostics capabilities for pull and push model.
	TagSupport *ClientDiagnosticsTagOptions `json:"tagSupport,omitempty"`
	// General diagnostics capabilities for pull and push model.
	CodeDescriptionSupport *bool `json:"codeDescriptionSupport,omitempty"`
	// General diagnostics capabilities for pull and push model.
	DataSupport *bool `json:"dataSupport,omitempty"`
}

type DidChangeConfigurationClientCapabilities struct {
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
}

type DocumentColorOptions struct {
	WorkDoneProgressOptions
}

// Client capabilities of a [DocumentFormattingRequest].
type DocumentFormattingClientCapabilities struct {
	// Client capabilities of a [DocumentFormattingRequest].
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
}

// Provider options for a [DocumentFormattingRequest].
type DocumentFormattingOptions struct {
	WorkDoneProgressOptions
}

// Client Capabilities for a [DocumentHighlightRequest].
type DocumentHighlightClientCapabilities struct {
	// Client Capabilities for a [DocumentHighlightRequest].
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
}

// Provider options for a [DocumentHighlightRequest].
type DocumentHighlightOptions struct {
	WorkDoneProgressOptions
}

// Provider options for a [DocumentLinkRequest].
type DocumentLinkOptions struct {
	WorkDoneProgressOptions
	// Provider options for a [DocumentLinkRequest].
	ResolveProvider *bool `json:"resolveProvider,omitempty"`
}

// Provider options for a [DocumentOnTypeFormattingRequest].
type DocumentOnTypeFormattingOptions struct {
	// Provider options for a [DocumentOnTypeFormattingRequest].
	FirstTriggerCharacter string `json:"firstTriggerCharacter"`
	// Provider options for a [DocumentOnTypeFormattingRequest].
	MoreTriggerCharacter *[]string `json:"moreTriggerCharacter,omitempty"`
}

// Provider options for a [DocumentRangeFormattingRequest].
type DocumentRangeFormattingOptions struct {
	WorkDoneProgressOptions
	// Provider options for a [DocumentRangeFormattingRequest].
	RangesSupport *bool `json:"rangesSupport,omitempty"`
}

// Client Capabilities for a [DocumentSymbolRequest].
type DocumentSymbolClientCapabilities struct {
	// Client Capabilities for a [DocumentSymbolRequest].
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
	// Client Capabilities for a [DocumentSymbolRequest].
	SymbolKind *ClientSymbolKindOptions `json:"symbolKind,omitempty"`
	// Client Capabilities for a [DocumentSymbolRequest].
	HierarchicalDocumentSymbolSupport *bool `json:"hierarchicalDocumentSymbolSupport,omitempty"`
	// Client Capabilities for a [DocumentSymbolRequest].
	TagSupport *ClientSymbolTagOptions `json:"tagSupport,omitempty"`
	// Client Capabilities for a [DocumentSymbolRequest].
	LabelSupport *bool `json:"labelSupport,omitempty"`
}

// Provider options for a [DocumentSymbolRequest].
type DocumentSymbolOptions struct {
	WorkDoneProgressOptions
	// Provider options for a [DocumentSymbolRequest].
	Label string `json:"label,omitempty"`
}

// The client capabilities of a [ExecuteCommandRequest].
type ExecuteCommandClientCapabilities struct {
	// The client capabilities of a [ExecuteCommandRequest].
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
}

// The server capabilities of a [ExecuteCommandRequest].
type ExecuteCommandOptions struct {
	WorkDoneProgressOptions
	// The server capabilities of a [ExecuteCommandRequest].
	Commands []string `json:"commands"`
}

/*
Represents information on a file/folder create.

@since 3.16.0
*/
type FileCreate struct {
	/*
		Represents information on a file/folder create.

		@since 3.16.0
	*/
	Uri DocumentURI `json:"uri"`
}

/*
Represents information on a file/folder delete.

@since 3.16.0
*/
type FileDelete struct {
	/*
		Represents information on a file/folder delete.

		@since 3.16.0
	*/
	Uri DocumentURI `json:"uri"`
}

// An event describing a file change.
type FileEvent struct {
	// An event describing a file change.
	Uri DocumentURI `json:"uri"`
	// An event describing a file change.
	Type FileChangeType `json:"type"`
}

/*
Capabilities relating to events from file operations by the user in the client.

These events do not come from the file system, they come from user operations
like renaming a file in the UI.

@since 3.16.0
*/
type FileOperationClientCapabilities struct {
	/*
		Capabilities relating to events from file operations by the user in the client.

		These events do not come from the file system, they come from user operations
		like renaming a file in the UI.

		@since 3.16.0
	*/
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
	/*
		Capabilities relating to events from file operations by the user in the client.

		These events do not come from the file system, they come from user operations
		like renaming a file in the UI.

		@since 3.16.0
	*/
	DidCreate *bool `json:"didCreate,omitempty"`
	/*
		Capabilities relating to events from file operations by the user in the client.

		These events do not come from the file system, they come from user operations
		like renaming a file in the UI.

		@since 3.16.0
	*/
	WillCreate *bool `json:"willCreate,omitempty"`
	/*
		Capabilities relating to events from file operations by the user in the client.

		These events do not come from the file system, they come from user operations
		like renaming a file in the UI.

		@since 3.16.0
	*/
	DidRename *bool `json:"didRename,omitempty"`
	/*
		Capabilities relating to events from file operations by the user in the client.

		These events do not come from the file system, they come from user operations
		like renaming a file in the UI.

		@since 3.16.0
	*/
	WillRename *bool `json:"willRename,omitempty"`
	/*
		Capabilities relating to events from file operations by the user in the client.

		These events do not come from the file system, they come from user operations
		like renaming a file in the UI.

		@since 3.16.0
	*/
	DidDelete *bool `json:"didDelete,omitempty"`
	/*
		Capabilities relating to events from file operations by the user in the client.

		These events do not come from the file system, they come from user operations
		like renaming a file in the UI.

		@since 3.16.0
	*/
	WillDelete *bool `json:"willDelete,omitempty"`
}

/*
A filter to describe in which file operation requests or notifications
the server is interested in receiving.

@since 3.16.0
*/
type FileOperationFilter struct {
	/*
		A filter to describe in which file operation requests or notifications
		the server is interested in receiving.

		@since 3.16.0
	*/
	Scheme string `json:"scheme,omitempty"`
	/*
		A filter to describe in which file operation requests or notifications
		the server is interested in receiving.

		@since 3.16.0
	*/
	Pattern FileOperationPattern `json:"pattern"`
}

/*
Options for notifications/requests for user operations on files.

@since 3.16.0
*/
type FileOperationOptions struct {
	/*
		Options for notifications/requests for user operations on files.

		@since 3.16.0
	*/
	DidCreate *FileOperationRegistrationOptions `json:"didCreate,omitempty"`
	/*
		Options for notifications/requests for user operations on files.

		@since 3.16.0
	*/
	WillCreate *FileOperationRegistrationOptions `json:"willCreate,omitempty"`
	/*
		Options for notifications/requests for user operations on files.

		@since 3.16.0
	*/
	DidRename *FileOperationRegistrationOptions `json:"didRename,omitempty"`
	/*
		Options for notifications/requests for user operations on files.

		@since 3.16.0
	*/
	WillRename *FileOperationRegistrationOptions `json:"willRename,omitempty"`
	/*
		Options for notifications/requests for user operations on files.

		@since 3.16.0
	*/
	DidDelete *FileOperationRegistrationOptions `json:"didDelete,omitempty"`
	/*
		Options for notifications/requests for user operations on files.

		@since 3.16.0
	*/
	WillDelete *FileOperationRegistrationOptions `json:"willDelete,omitempty"`
}

/*
A pattern to describe in which file operation requests or notifications
the server is interested in receiving.

@since 3.16.0
*/
type FileOperationPattern struct {
	/*
		A pattern to describe in which file operation requests or notifications
		the server is interested in receiving.

		@since 3.16.0
	*/
	Glob string `json:"glob"`
	/*
		A pattern to describe in which file operation requests or notifications
		the server is interested in receiving.

		@since 3.16.0
	*/
	Matches *FileOperationPatternKind `json:"matches,omitempty"`
	/*
		A pattern to describe in which file operation requests or notifications
		the server is interested in receiving.

		@since 3.16.0
	*/
	Options *FileOperationPatternOptions `json:"options,omitempty"`
}

/*
Matching options for the file operation pattern.

@since 3.16.0
*/
type FileOperationPatternOptions struct {
	/*
		Matching options for the file operation pattern.

		@since 3.16.0
	*/
	IgnoreCase *bool `json:"ignoreCase,omitempty"`
}

type FileSystemWatcher struct {
	GlobPattern GlobPattern `json:"globPattern"`
	Kind        *WatchKind  `json:"kind,omitempty"`
}

/*
Represents a folding range. To be valid, start and end line must be bigger than zero and smaller
than the number of lines in the document. Clients are free to ignore invalid ranges.
*/
type FoldingRange struct {
	/*
		Represents a folding range. To be valid, start and end line must be bigger than zero and smaller
		than the number of lines in the document. Clients are free to ignore invalid ranges.
	*/
	StartLine uint32 `json:"startLine"`
	/*
		Represents a folding range. To be valid, start and end line must be bigger than zero and smaller
		than the number of lines in the document. Clients are free to ignore invalid ranges.
	*/
	StartCharacter uint32 `json:"startCharacter,omitempty"`
	/*
		Represents a folding range. To be valid, start and end line must be bigger than zero and smaller
		than the number of lines in the document. Clients are free to ignore invalid ranges.
	*/
	EndLine uint32 `json:"endLine"`
	/*
		Represents a folding range. To be valid, start and end line must be bigger than zero and smaller
		than the number of lines in the document. Clients are free to ignore invalid ranges.
	*/
	EndCharacter uint32 `json:"endCharacter,omitempty"`
	/*
		Represents a folding range. To be valid, start and end line must be bigger than zero and smaller
		than the number of lines in the document. Clients are free to ignore invalid ranges.
	*/
	Kind *FoldingRangeKind `json:"kind,omitempty"`
	/*
		Represents a folding range. To be valid, start and end line must be bigger than zero and smaller
		than the number of lines in the document. Clients are free to ignore invalid ranges.
	*/
	CollapsedText string `json:"collapsedText,omitempty"`
}

type FoldingRangeClientCapabilities struct {
	DynamicRegistration *bool                          `json:"dynamicRegistration,omitempty"`
	RangeLimit          uint32                         `json:"rangeLimit,omitempty"`
	LineFoldingOnly     *bool                          `json:"lineFoldingOnly,omitempty"`
	FoldingRangeKind    *ClientFoldingRangeKindOptions `json:"foldingRangeKind,omitempty"`
	FoldingRange        *ClientFoldingRangeOptions     `json:"foldingRange,omitempty"`
}

type FoldingRangeOptions struct {
	WorkDoneProgressOptions
}

// Value-object describing what options formatting should use.
type FormattingOptions struct {
	// Value-object describing what options formatting should use.
	TabSize uint32 `json:"tabSize"`
	// Value-object describing what options formatting should use.
	InsertSpaces bool `json:"insertSpaces"`
	// Value-object describing what options formatting should use.
	TrimTrailingWhitespace *bool `json:"trimTrailingWhitespace,omitempty"`
	// Value-object describing what options formatting should use.
	InsertFinalNewline *bool `json:"insertFinalNewline,omitempty"`
	// Value-object describing what options formatting should use.
	TrimFinalNewlines *bool `json:"trimFinalNewlines,omitempty"`
}

/*
A diagnostic report with a full set of problems.

@since 3.17.0
*/
type FullDocumentDiagnosticReport struct {
	/*
		A diagnostic report with a full set of problems.

		@since 3.17.0
	*/
	Kind string `json:"kind"` // full
	/*
		A diagnostic report with a full set of problems.

		@since 3.17.0
	*/
	ResultId string `json:"resultId,omitempty"`
	/*
		A diagnostic report with a full set of problems.

		@since 3.17.0
	*/
	Items []*Diagnostic `json:"items"`
}

/*
General client capabilities.

@since 3.16.0
*/
type GeneralClientCapabilities struct {
	/*
		General client capabilities.

		@since 3.16.0
	*/
	StaleRequestSupport *StaleRequestSupportOptions `json:"staleRequestSupport,omitempty"`
	/*
		General client capabilities.

		@since 3.16.0
	*/
	RegularExpressions *RegularExpressionsClientCapabilities `json:"regularExpressions,omitempty"`
	/*
		General client capabilities.

		@since 3.16.0
	*/
	Markdown *MarkdownClientCapabilities `json:"markdown,omitempty"`
	/*
		General client capabilities.

		@since 3.16.0
	*/
	PositionEncodings *[]PositionEncodingKind `json:"positionEncodings,omitempty"`
}

// The result of a hover request.
type Hover struct {
	// The result of a hover request.
	Contents rpc.Union3[MarkupContent, MarkedString, []MarkedString] `json:"contents"` // MarkupContent | MarkedString | MarkedString[]
	// The result of a hover request.
	Range *Range `json:"range,omitempty"`
}

type HoverClientCapabilities struct {
	DynamicRegistration *bool         `json:"dynamicRegistration,omitempty"`
	ContentFormat       *[]MarkupKind `json:"contentFormat,omitempty"`
}

// Hover options.
type HoverOptions struct {
	WorkDoneProgressOptions
}

type ImplementationOptions struct {
	WorkDoneProgressOptions
}

/*
An inlay hint label part allows for interactive and composite labels
of inlay hints.

@since 3.17.0
*/
type InlayHintLabelPart struct {
	/*
		An inlay hint label part allows for interactive and composite labels
		of inlay hints.

		@since 3.17.0
	*/
	Value string `json:"value"`
	/*
		An inlay hint label part allows for interactive and composite labels
		of inlay hints.

		@since 3.17.0
	*/
	Tooltip *rpc.Union2[string, MarkupContent] `json:"tooltip,omitempty"`
	/*
		An inlay hint label part allows for interactive and composite labels
		of inlay hints.

		@since 3.17.0
	*/
	Location *Location `json:"location,omitempty"`
	/*
		An inlay hint label part allows for interactive and composite labels
		of inlay hints.

		@since 3.17.0
	*/
	Command *Command `json:"command,omitempty"`
}

/*
Inlay hint options used during static registration.

@since 3.17.0
*/
type InlayHintOptions struct {
	WorkDoneProgressOptions
	/*
		Inlay hint options used during static registration.

		@since 3.17.0
	*/
	ResolveProvider *bool `json:"resolveProvider,omitempty"`
}

/*
Client capabilities specific to inline completions.

@since 3.18.0
*/
type InlineCompletionClientCapabilities struct {
	/*
		Client capabilities specific to inline completions.

		@since 3.18.0
	*/
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
}

/*
Provides information about the context in which an inline completion was requested.

@since 3.18.0
*/
type InlineCompletionContext struct {
	/*
		Provides information about the context in which an inline completion was requested.

		@since 3.18.0
	*/
	TriggerKind InlineCompletionTriggerKind `json:"triggerKind"`
	/*
		Provides information about the context in which an inline completion was requested.

		@since 3.18.0
	*/
	SelectedCompletionInfo *SelectedCompletionInfo `json:"selectedCompletionInfo,omitempty"`
}

/*
An inline completion item represents a text snippet that is proposed inline to complete text that is being typed.

@since 3.18.0
*/
type InlineCompletionItem struct {
	/*
		An inline completion item represents a text snippet that is proposed inline to complete text that is being typed.

		@since 3.18.0
	*/
	InsertText rpc.Union2[string, StringValue] `json:"insertText"`
	/*
		An inline completion item represents a text snippet that is proposed inline to complete text that is being typed.

		@since 3.18.0
	*/
	FilterText string `json:"filterText,omitempty"`
	/*
		An inline completion item represents a text snippet that is proposed inline to complete text that is being typed.

		@since 3.18.0
	*/
	Range *Range `json:"range,omitempty"`
	/*
		An inline completion item represents a text snippet that is proposed inline to complete text that is being typed.

		@since 3.18.0
	*/
	Command *Command `json:"command,omitempty"`
}

/*
Represents a collection of  inline completion items [InlineCompletionItem] to be presented in the editor.

@since 3.18.0
*/
type InlineCompletionList struct {
	/*
		Represents a collection of  inline completion items [InlineCompletionItem] to be presented in the editor.

		@since 3.18.0
	*/
	Items []InlineCompletionItem `json:"items"`
}

/*
Inline completion options used during static registration.

@since 3.18.0
*/
type InlineCompletionOptions struct {
	WorkDoneProgressOptions
}

// @since 3.17.0
type InlineValueContext struct {
	// @since 3.17.0
	FrameId int `json:"frameId"`
	// @since 3.17.0
	StoppedLocation Range `json:"stoppedLocation"`
}

/*
To compute an inline value through an expression evaluation.

If only a range is specified, the expression should be
extracted from the underlying document.

An optional expression could be evaluated instead of
the extracted expression.

@since 3.17.0
*/
type InlineValueEvaluatableExpression struct {
	/*
		To compute an inline value through an expression evaluation.

		If only a range is specified, the expression should be
		extracted from the underlying document.

		An optional expression could be evaluated instead of
		the extracted expression.

		@since 3.17.0
	*/
	Range Range `json:"range"`
	/*
		To compute an inline value through an expression evaluation.

		If only a range is specified, the expression should be
		extracted from the underlying document.

		An optional expression could be evaluated instead of
		the extracted expression.

		@since 3.17.0
	*/
	Expression string `json:"expression,omitempty"`
}

/*
Inline value options used during static registration.

@since 3.17.0
*/
type InlineValueOptions struct {
	WorkDoneProgressOptions
}

/*
To compute inline value through a variable lookup.

If only a range is specified, the variable name should
be extracted from the underlying document.

An optional variable name could be used to lookup instead
of the extracted name.

@since 3.17.0
*/
type InlineValueVariableLookup struct {
	/*
		To compute inline value through a variable lookup.

		If only a range is specified, the variable name should
		be extracted from the underlying document.

		An optional variable name could be used to lookup instead
		of the extracted name.

		@since 3.17.0
	*/
	Range Range `json:"range"`
	/*
		To compute inline value through a variable lookup.

		If only a range is specified, the variable name should
		be extracted from the underlying document.

		An optional variable name could be used to lookup instead
		of the extracted name.

		@since 3.17.0
	*/
	VariableName string `json:"variableName,omitempty"`
	/*
		To compute inline value through a variable lookup.

		If only a range is specified, the variable name should
		be extracted from the underlying document.

		An optional variable name could be used to lookup instead
		of the extracted name.

		@since 3.17.0
	*/
	CaseSensitiveLookup bool `json:"caseSensitiveLookup"`
}

/*
Client workspace capabilities specific to inline values.

@since 3.17.0
*/
type InlineValueWorkspaceClientCapabilities struct {
	/*
		Client workspace capabilities specific to inline values.

		@since 3.17.0
	*/
	RefreshSupport *bool `json:"refreshSupport,omitempty"`
}

/*
A special text edit to provide an insert and a replace operation.

@since 3.16.0
*/
type InsertReplaceEdit struct {
	/*
		A special text edit to provide an insert and a replace operation.

		@since 3.16.0
	*/
	NewText string `json:"newText"`
	/*
		A special text edit to provide an insert and a replace operation.

		@since 3.16.0
	*/
	Insert Range `json:"insert"`
	/*
		A special text edit to provide an insert and a replace operation.

		@since 3.16.0
	*/
	Replace Range `json:"replace"`
}

/*
Client capabilities for the linked editing range request.

@since 3.16.0
*/
type LinkedEditingRangeClientCapabilities struct {
	/*
		Client capabilities for the linked editing range request.

		@since 3.16.0
	*/
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
}

type LinkedEditingRangeOptions struct {
	WorkDoneProgressOptions
}

/*
Represents a location inside a resource, such as a line
inside a text file.
*/
type Location struct {
	/*
		Represents a location inside a resource, such as a line
		inside a text file.
	*/
	Uri DocumentURI `json:"uri"`
	/*
		Represents a location inside a resource, such as a line
		inside a text file.
	*/
	Range Range `json:"range"`
}

/*
Represents the connection of two locations. Provides additional metadata over normal  locations [Location],
including an origin range.
*/
type LocationLink struct {
	/*
		Represents the connection of two locations. Provides additional metadata over normal  locations [Location],
		including an origin range.
	*/
	OriginSelectionRange *Range `json:"originSelectionRange,omitempty"`
	/*
		Represents the connection of two locations. Provides additional metadata over normal  locations [Location],
		including an origin range.
	*/
	TargetUri DocumentURI `json:"targetUri"`
	/*
		Represents the connection of two locations. Provides additional metadata over normal  locations [Location],
		including an origin range.
	*/
	TargetRange Range `json:"targetRange"`
	/*
		Represents the connection of two locations. Provides additional metadata over normal  locations [Location],
		including an origin range.
	*/
	TargetSelectionRange Range `json:"targetSelectionRange"`
}

/*
Location with only uri and does not include range.

@since 3.18.0
*/
type LocationUriOnly struct {
	/*
		Location with only uri and does not include range.

		@since 3.18.0
	*/
	Uri DocumentURI `json:"uri"`
}

/*
@since 3.18.0
@deprecated use MarkupContent instead.

* Deprecated: use MarkupContent instead.
*/
type MarkedStringWithLanguage struct {
	/*
		@since 3.18.0
		@deprecated use MarkupContent instead.

		* Deprecated: use MarkupContent instead.
	*/
	Language string `json:"language"`
	/*
		@since 3.18.0
		@deprecated use MarkupContent instead.

		* Deprecated: use MarkupContent instead.
	*/
	Value string `json:"value"`
}

/*
A `MarkupContent` literal represents a string value which content is interpreted base on its
kind flag. Currently the protocol supports `plaintext` and `markdown` as markup kinds.

If the kind is `markdown` then the value can contain fenced code blocks like in GitHub issues.
See https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting

Here is an example how such a string can be constructed using JavaScript / TypeScript:
```ts

	let markdown: MarkdownContent = {
	 kind: MarkupKind.Markdown,
	 value: [
	   '# Header',
	   'Some text',
	   '```typescript',
	   'someCode();',
	   '```'
	 ].join('\n')
	};

```

*Please Note* that clients might sanitize the return markdown. A client could decide to
remove HTML from the markdown to avoid script execution.
*/
type MarkupContent struct {
	/*
		A `MarkupContent` literal represents a string value which content is interpreted base on its
		kind flag. Currently the protocol supports `plaintext` and `markdown` as markup kinds.

		If the kind is `markdown` then the value can contain fenced code blocks like in GitHub issues.
		See https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting

		Here is an example how such a string can be constructed using JavaScript / TypeScript:
		```ts
		let markdown: MarkdownContent = {
		 kind: MarkupKind.Markdown,
		 value: [
		   '# Header',
		   'Some text',
		   '```typescript',
		   'someCode();',
		   '```'
		 ].join('\n')
		};
		```

		*Please Note* that clients might sanitize the return markdown. A client could decide to
		remove HTML from the markdown to avoid script execution.
	*/
	Kind MarkupKind `json:"kind"`
	/*
		A `MarkupContent` literal represents a string value which content is interpreted base on its
		kind flag. Currently the protocol supports `plaintext` and `markdown` as markup kinds.

		If the kind is `markdown` then the value can contain fenced code blocks like in GitHub issues.
		See https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting

		Here is an example how such a string can be constructed using JavaScript / TypeScript:
		```ts
		let markdown: MarkdownContent = {
		 kind: MarkupKind.Markdown,
		 value: [
		   '# Header',
		   'Some text',
		   '```typescript',
		   'someCode();',
		   '```'
		 ].join('\n')
		};
		```

		*Please Note* that clients might sanitize the return markdown. A client could decide to
		remove HTML from the markdown to avoid script execution.
	*/
	Value string `json:"value"`
}

type MessageActionItem struct {
	Title string `json:"title"`
}

/*
Moniker definition to match LSIF 0.5 moniker definition.

@since 3.16.0
*/
type Moniker struct {
	/*
		Moniker definition to match LSIF 0.5 moniker definition.

		@since 3.16.0
	*/
	Scheme string `json:"scheme"`
	/*
		Moniker definition to match LSIF 0.5 moniker definition.

		@since 3.16.0
	*/
	Identifier string `json:"identifier"`
	/*
		Moniker definition to match LSIF 0.5 moniker definition.

		@since 3.16.0
	*/
	Unique UniquenessLevel `json:"unique"`
	/*
		Moniker definition to match LSIF 0.5 moniker definition.

		@since 3.16.0
	*/
	Kind *MonikerKind `json:"kind,omitempty"`
}

/*
Client capabilities specific to the moniker request.

@since 3.16.0
*/
type MonikerClientCapabilities struct {
	/*
		Client capabilities specific to the moniker request.

		@since 3.16.0
	*/
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
}

type MonikerOptions struct {
	WorkDoneProgressOptions
}

/*
A change describing how to move a `NotebookCell`
array from state S to S'.

@since 3.17.0
*/
type NotebookCellArrayChange struct {
	/*
		A change describing how to move a `NotebookCell`
		array from state S to S'.

		@since 3.17.0
	*/
	Start uint32 `json:"start"`
	/*
		A change describing how to move a `NotebookCell`
		array from state S to S'.

		@since 3.17.0
	*/
	DeleteCount uint32 `json:"deleteCount"`
	/*
		A change describing how to move a `NotebookCell`
		array from state S to S'.

		@since 3.17.0
	*/
	Cells *[]NotebookCell `json:"cells,omitempty"`
}

// @since 3.18.0
type NotebookCellLanguage struct {
	// @since 3.18.0
	Language string `json:"language"`
}

/*
A notebook cell text document filter denotes a cell text
document by different properties.

@since 3.17.0
*/
type NotebookCellTextDocumentFilter struct {
	/*
		A notebook cell text document filter denotes a cell text
		document by different properties.

		@since 3.17.0
	*/
	Notebook rpc.Union2[string, NotebookDocumentFilter] `json:"notebook"`
	/*
		A notebook cell text document filter denotes a cell text
		document by different properties.

		@since 3.17.0
	*/
	Language string `json:"language,omitempty"`
}

/*
A notebook document.

@since 3.17.0
*/
type NotebookDocument struct {
	/*
		A notebook document.

		@since 3.17.0
	*/
	Uri URI `json:"uri"`
	/*
		A notebook document.

		@since 3.17.0
	*/
	NotebookType string `json:"notebookType"`
	/*
		A notebook document.

		@since 3.17.0
	*/
	Version int `json:"version"`
	/*
		A notebook document.

		@since 3.17.0
	*/
	Metadata *map[string]any `json:"metadata,omitempty"`
	/*
		A notebook document.

		@since 3.17.0
	*/
	Cells []NotebookCell `json:"cells"`
}

/*
Structural changes to cells in a notebook document.

@since 3.18.0
*/
type NotebookDocumentCellChangeStructure struct {
	/*
		Structural changes to cells in a notebook document.

		@since 3.18.0
	*/
	Array NotebookCellArrayChange `json:"array"`
	/*
		Structural changes to cells in a notebook document.

		@since 3.18.0
	*/
	DidOpen *[]TextDocumentItem `json:"didOpen,omitempty"`
	/*
		Structural changes to cells in a notebook document.

		@since 3.18.0
	*/
	DidClose *[]TextDocumentIdentifier `json:"didClose,omitempty"`
}

/*
Cell changes to a notebook document.

@since 3.18.0
*/
type NotebookDocumentCellChanges struct {
	/*
		Cell changes to a notebook document.

		@since 3.18.0
	*/
	Structure *NotebookDocumentCellChangeStructure `json:"structure,omitempty"`
	/*
		Cell changes to a notebook document.

		@since 3.18.0
	*/
	Data *[]NotebookCell `json:"data,omitempty"`
	/*
		Cell changes to a notebook document.

		@since 3.18.0
	*/
	TextContent *[]NotebookDocumentCellContentChanges `json:"textContent,omitempty"`
}

/*
Content changes to a cell in a notebook document.

@since 3.18.0
*/
type NotebookDocumentCellContentChanges struct {
	/*
		Content changes to a cell in a notebook document.

		@since 3.18.0
	*/
	Document VersionedTextDocumentIdentifier `json:"document"`
	/*
		Content changes to a cell in a notebook document.

		@since 3.18.0
	*/
	Changes []TextDocumentContentChangeEvent `json:"changes"`
}

/*
A change event for a notebook document.

@since 3.17.0
*/
type NotebookDocumentChangeEvent struct {
	/*
		A change event for a notebook document.

		@since 3.17.0
	*/
	Metadata *map[string]any `json:"metadata,omitempty"`
	/*
		A change event for a notebook document.

		@since 3.17.0
	*/
	Cells *NotebookDocumentCellChanges `json:"cells,omitempty"`
}

/*
Capabilities specific to the notebook document support.

@since 3.17.0
*/
type NotebookDocumentClientCapabilities struct {
	/*
		Capabilities specific to the notebook document support.

		@since 3.17.0
	*/
	Synchronization NotebookDocumentSyncClientCapabilities `json:"synchronization"`
}

/*
A notebook document filter where `notebookType` is required field.

@since 3.18.0
*/
type NotebookDocumentFilterNotebookType struct {
	/*
		A notebook document filter where `notebookType` is required field.

		@since 3.18.0
	*/
	NotebookType string `json:"notebookType"`
	/*
		A notebook document filter where `notebookType` is required field.

		@since 3.18.0
	*/
	Scheme string `json:"scheme,omitempty"`
	/*
		A notebook document filter where `notebookType` is required field.

		@since 3.18.0
	*/
	Pattern *GlobPattern `json:"pattern,omitempty"`
}

/*
A notebook document filter where `pattern` is required field.

@since 3.18.0
*/
type NotebookDocumentFilterPattern struct {
	/*
		A notebook document filter where `pattern` is required field.

		@since 3.18.0
	*/
	NotebookType string `json:"notebookType,omitempty"`
	/*
		A notebook document filter where `pattern` is required field.

		@since 3.18.0
	*/
	Scheme string `json:"scheme,omitempty"`
	/*
		A notebook document filter where `pattern` is required field.

		@since 3.18.0
	*/
	Pattern GlobPattern `json:"pattern"`
}

/*
A notebook document filter where `scheme` is required field.

@since 3.18.0
*/
type NotebookDocumentFilterScheme struct {
	/*
		A notebook document filter where `scheme` is required field.

		@since 3.18.0
	*/
	NotebookType string `json:"notebookType,omitempty"`
	/*
		A notebook document filter where `scheme` is required field.

		@since 3.18.0
	*/
	Scheme string `json:"scheme"`
	/*
		A notebook document filter where `scheme` is required field.

		@since 3.18.0
	*/
	Pattern *GlobPattern `json:"pattern,omitempty"`
}

// @since 3.18.0
type NotebookDocumentFilterWithCells struct {
	// @since 3.18.0
	Notebook *rpc.Union2[string, NotebookDocumentFilter] `json:"notebook,omitempty"`
	// @since 3.18.0
	Cells []NotebookCellLanguage `json:"cells"`
}

// @since 3.18.0
type NotebookDocumentFilterWithNotebook struct {
	// @since 3.18.0
	Notebook rpc.Union2[string, NotebookDocumentFilter] `json:"notebook"`
	// @since 3.18.0
	Cells *[]NotebookCellLanguage `json:"cells,omitempty"`
}

/*
A literal to identify a notebook document in the client.

@since 3.17.0
*/
type NotebookDocumentIdentifier struct {
	/*
		A literal to identify a notebook document in the client.

		@since 3.17.0
	*/
	Uri URI `json:"uri"`
}

/*
Notebook specific client capabilities.

@since 3.17.0
*/
type NotebookDocumentSyncClientCapabilities struct {
	/*
		Notebook specific client capabilities.

		@since 3.17.0
	*/
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
	/*
		Notebook specific client capabilities.

		@since 3.17.0
	*/
	ExecutionSummarySupport *bool `json:"executionSummarySupport,omitempty"`
}

/*
Options specific to a notebook plus its cells
to be synced to the server.

If a selector provides a notebook document
filter but no cell selector all cells of a
matching notebook document will be synced.

If a selector provides no notebook document
filter but only a cell selector all notebook
document that contain at least one matching
cell will be synced.

@since 3.17.0
*/
type NotebookDocumentSyncOptions struct {
	/*
		Options specific to a notebook plus its cells
		to be synced to the server.

		If a selector provides a notebook document
		filter but no cell selector all cells of a
		matching notebook document will be synced.

		If a selector provides no notebook document
		filter but only a cell selector all notebook
		document that contain at least one matching
		cell will be synced.

		@since 3.17.0
	*/
	NotebookSelector []rpc.Union2[NotebookDocumentFilterWithNotebook, NotebookDocumentFilterWithCells] `json:"notebookSelector"`
	/*
		Options specific to a notebook plus its cells
		to be synced to the server.

		If a selector provides a notebook document
		filter but no cell selector all cells of a
		matching notebook document will be synced.

		If a selector provides no notebook document
		filter but only a cell selector all notebook
		document that contain at least one matching
		cell will be synced.

		@since 3.17.0
	*/
	Save *bool `json:"save,omitempty"`
}

/*
Represents a parameter of a callable-signature. A parameter can
have a label and a doc-comment.
*/
type ParameterInformation struct {
	/*
		Represents a parameter of a callable-signature. A parameter can
		have a label and a doc-comment.
	*/
	Label rpc.Union2[string, [2]uint32] `json:"label"` // string | [uinteger, uinteger]
	/*
		Represents a parameter of a callable-signature. A parameter can
		have a label and a doc-comment.
	*/
	Documentation *rpc.Union2[string, MarkupContent] `json:"documentation,omitempty"`
}

type PartialResultParams struct {
	PartialResultToken *ProgressToken `json:"partialResultToken,omitempty"`
}

/*
Position in a text document expressed as zero-based line and character
offset. Prior to 3.17 the offsets were always based on a UTF-16 string
representation. So a string of the form `a𐐀b` the character offset of the
character `a` is 0, the character offset of `𐐀` is 1 and the character
offset of b is 3 since `𐐀` is represented using two code units in UTF-16.
Since 3.17 clients and servers can agree on a different string encoding
representation (e.g. UTF-8). The client announces it's supported encoding
via the client capability [`general.positionEncodings`](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#clientCapabilities).
The value is an array of position encodings the client supports, with
decreasing preference (e.g. the encoding at index `0` is the most preferred
one). To stay backwards compatible the only mandatory encoding is UTF-16
represented via the string `utf-16`. The server can pick one of the
encodings offered by the client and signals that encoding back to the
client via the initialize result's property
[`capabilities.positionEncoding`](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#serverCapabilities). If the string value
`utf-16` is missing from the client's capability `general.positionEncodings`
servers can safely assume that the client supports UTF-16. If the server
omits the position encoding in its initialize result the encoding defaults
to the string value `utf-16`. Implementation considerations: since the
conversion from one encoding into another requires the content of the
file / line the conversion is best done where the file is read which is
usually on the server side.

Positions are line end character agnostic. So you can not specify a position
that denotes `\r|\n` or `\n|` where `|` represents the character offset.

@since 3.17.0 - support for negotiated position encoding.
*/
type Position struct {
	/*
		Position in a text document expressed as zero-based line and character
		offset. Prior to 3.17 the offsets were always based on a UTF-16 string
		representation. So a string of the form `a𐐀b` the character offset of the
		character `a` is 0, the character offset of `𐐀` is 1 and the character
		offset of b is 3 since `𐐀` is represented using two code units in UTF-16.
		Since 3.17 clients and servers can agree on a different string encoding
		representation (e.g. UTF-8). The client announces it's supported encoding
		via the client capability [`general.positionEncodings`](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#clientCapabilities).
		The value is an array of position encodings the client supports, with
		decreasing preference (e.g. the encoding at index `0` is the most preferred
		one). To stay backwards compatible the only mandatory encoding is UTF-16
		represented via the string `utf-16`. The server can pick one of the
		encodings offered by the client and signals that encoding back to the
		client via the initialize result's property
		[`capabilities.positionEncoding`](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#serverCapabilities). If the string value
		`utf-16` is missing from the client's capability `general.positionEncodings`
		servers can safely assume that the client supports UTF-16. If the server
		omits the position encoding in its initialize result the encoding defaults
		to the string value `utf-16`. Implementation considerations: since the
		conversion from one encoding into another requires the content of the
		file / line the conversion is best done where the file is read which is
		usually on the server side.

		Positions are line end character agnostic. So you can not specify a position
		that denotes `\r|\n` or `\n|` where `|` represents the character offset.

		@since 3.17.0 - support for negotiated position encoding.
	*/
	Line uint32 `json:"line"`
	/*
		Position in a text document expressed as zero-based line and character
		offset. Prior to 3.17 the offsets were always based on a UTF-16 string
		representation. So a string of the form `a𐐀b` the character offset of the
		character `a` is 0, the character offset of `𐐀` is 1 and the character
		offset of b is 3 since `𐐀` is represented using two code units in UTF-16.
		Since 3.17 clients and servers can agree on a different string encoding
		representation (e.g. UTF-8). The client announces it's supported encoding
		via the client capability [`general.positionEncodings`](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#clientCapabilities).
		The value is an array of position encodings the client supports, with
		decreasing preference (e.g. the encoding at index `0` is the most preferred
		one). To stay backwards compatible the only mandatory encoding is UTF-16
		represented via the string `utf-16`. The server can pick one of the
		encodings offered by the client and signals that encoding back to the
		client via the initialize result's property
		[`capabilities.positionEncoding`](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#serverCapabilities). If the string value
		`utf-16` is missing from the client's capability `general.positionEncodings`
		servers can safely assume that the client supports UTF-16. If the server
		omits the position encoding in its initialize result the encoding defaults
		to the string value `utf-16`. Implementation considerations: since the
		conversion from one encoding into another requires the content of the
		file / line the conversion is best done where the file is read which is
		usually on the server side.

		Positions are line end character agnostic. So you can not specify a position
		that denotes `\r|\n` or `\n|` where `|` represents the character offset.

		@since 3.17.0 - support for negotiated position encoding.
	*/
	Character uint32 `json:"character"`
}

// @since 3.18.0
type PrepareRenameDefaultBehavior struct {
	// @since 3.18.0
	DefaultBehavior bool `json:"defaultBehavior"`
}

/*
A previous result id in a workspace pull request.

@since 3.17.0
*/
type PreviousResultId struct {
	/*
		A previous result id in a workspace pull request.

		@since 3.17.0
	*/
	Uri DocumentURI `json:"uri"`
	/*
		A previous result id in a workspace pull request.

		@since 3.17.0
	*/
	Value string `json:"value"`
}

// Client Capabilities for a [ReferencesRequest].
type ReferenceClientCapabilities struct {
	// Client Capabilities for a [ReferencesRequest].
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
}

/*
Value-object that contains additional information when
requesting references.
*/
type ReferenceContext struct {
	/*
		Value-object that contains additional information when
		requesting references.
	*/
	IncludeDeclaration bool `json:"includeDeclaration"`
}

// Reference options.
type ReferenceOptions struct {
	WorkDoneProgressOptions
}

/*
A full diagnostic report with a set of related documents.

@since 3.17.0
*/
type RelatedFullDocumentDiagnosticReport struct {
	FullDocumentDiagnosticReport
	/*
		A full diagnostic report with a set of related documents.

		@since 3.17.0
	*/
	RelatedDocuments *map[DocumentURI]struct{} `json:"relatedDocuments,omitempty"`
}

/*
An unchanged diagnostic report with a set of related documents.

@since 3.17.0
*/
type RelatedUnchangedDocumentDiagnosticReport struct {
	UnchangedDocumentDiagnosticReport
	/*
		An unchanged diagnostic report with a set of related documents.

		@since 3.17.0
	*/
	RelatedDocuments *map[DocumentURI]struct{} `json:"relatedDocuments,omitempty"`
}

/*
A relative pattern is a helper to construct glob patterns that are matched
relatively to a base URI. The common value for a `baseUri` is a workspace
folder root, but it can be another absolute URI as well.

@since 3.17.0
*/
type RelativePattern struct {
	/*
		A relative pattern is a helper to construct glob patterns that are matched
		relatively to a base URI. The common value for a `baseUri` is a workspace
		folder root, but it can be another absolute URI as well.

		@since 3.17.0
	*/
	BaseUri rpc.Union2[WorkspaceFolder, URI] `json:"baseUri"`
	/*
		A relative pattern is a helper to construct glob patterns that are matched
		relatively to a base URI. The common value for a `baseUri` is a workspace
		folder root, but it can be another absolute URI as well.

		@since 3.17.0
	*/
	Pattern Pattern `json:"pattern"`
}

type RenameClientCapabilities struct {
	DynamicRegistration           *bool                          `json:"dynamicRegistration,omitempty"`
	PrepareSupport                *bool                          `json:"prepareSupport,omitempty"`
	PrepareSupportDefaultBehavior *PrepareSupportDefaultBehavior `json:"prepareSupportDefaultBehavior,omitempty"`
	HonorsChangeAnnotations       *bool                          `json:"honorsChangeAnnotations,omitempty"`
}

// Rename file operation
type RenameFile struct {
	ResourceOperation
	// Rename file operation
	Kind string `json:"kind"` // rename
	// Rename file operation
	OldUri DocumentURI `json:"oldUri"`
	// Rename file operation
	NewUri DocumentURI `json:"newUri"`
	// Rename file operation
	Options *RenameFileOptions `json:"options,omitempty"`
}

// Rename file options
type RenameFileOptions struct {
	// Rename file options
	Overwrite *bool `json:"overwrite,omitempty"`
	// Rename file options
	IgnoreIfExists *bool `json:"ignoreIfExists,omitempty"`
}

// Save options.
type SaveOptions struct {
	// Save options.
	IncludeText *bool `json:"includeText,omitempty"`
}

/*
Describes the currently selected completion item.

@since 3.18.0
*/
type SelectedCompletionInfo struct {
	/*
		Describes the currently selected completion item.

		@since 3.18.0
	*/
	Range Range `json:"range"`
	/*
		Describes the currently selected completion item.

		@since 3.18.0
	*/
	Text string `json:"text"`
}

/*
A selection range represents a part of a selection hierarchy. A selection range
may have a parent selection range that contains it.
*/
type SelectionRange struct {
	/*
		A selection range represents a part of a selection hierarchy. A selection range
		may have a parent selection range that contains it.
	*/
	Range Range `json:"range"`
	/*
		A selection range represents a part of a selection hierarchy. A selection range
		may have a parent selection range that contains it.
	*/
	Parent *SelectionRange `json:"parent,omitempty"`
}

type SelectionRangeClientCapabilities struct {
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
}

type SelectionRangeOptions struct {
	WorkDoneProgressOptions
}

// @since 3.16.0
type SemanticTokensClientCapabilities struct {
	// @since 3.16.0
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
	// @since 3.16.0
	Requests ClientSemanticTokensRequestOptions `json:"requests"`
	// @since 3.16.0
	TokenTypes []string `json:"tokenTypes"`
	// @since 3.16.0
	TokenModifiers []string `json:"tokenModifiers"`
	// @since 3.16.0
	Formats []TokenFormat `json:"formats"`
	// @since 3.16.0
	OverlappingTokenSupport *bool `json:"overlappingTokenSupport,omitempty"`
	// @since 3.16.0
	MultilineTokenSupport *bool `json:"multilineTokenSupport,omitempty"`
	// @since 3.16.0
	ServerCancelSupport *bool `json:"serverCancelSupport,omitempty"`
	// @since 3.16.0
	AugmentsSyntaxTokens *bool `json:"augmentsSyntaxTokens,omitempty"`
}

// @since 3.16.0
type SemanticTokensDelta struct {
	// @since 3.16.0
	ResultId string `json:"resultId,omitempty"`
	// @since 3.16.0
	Edits []SemanticTokensEdit `json:"edits"`
}

// @since 3.16.0
type SemanticTokensEdit struct {
	// @since 3.16.0
	Start uint32 `json:"start"`
	// @since 3.16.0
	DeleteCount uint32 `json:"deleteCount"`
	// @since 3.16.0
	Data *[]uint32 `json:"data,omitempty"`
}

/*
Semantic tokens options to support deltas for full documents

@since 3.18.0
*/
type SemanticTokensFullDelta struct {
	/*
		Semantic tokens options to support deltas for full documents

		@since 3.18.0
	*/
	Delta *bool `json:"delta,omitempty"`
}

// @since 3.16.0
type SemanticTokensLegend struct {
	// @since 3.16.0
	TokenTypes []string `json:"tokenTypes"`
	// @since 3.16.0
	TokenModifiers []string `json:"tokenModifiers"`
}

// @since 3.16.0
type SemanticTokensOptions struct {
	WorkDoneProgressOptions
	// @since 3.16.0
	Legend SemanticTokensLegend `json:"legend"`
	// @since 3.16.0
	Range *rpc.Union2[bool, struct{}] `json:"range,omitempty"` // boolean | {}
	// @since 3.16.0
	Full *rpc.Union2[bool, SemanticTokensFullDelta] `json:"full,omitempty"`
}

/*
Defines the capabilities provided by a language
server.
*/
type ServerCapabilities struct {
	/*
		Defines the capabilities provided by a language
		server.
	*/
	PositionEncoding *PositionEncodingKind `json:"positionEncoding,omitempty"`
	/*
		Defines the capabilities provided by a language
		server.
	*/
	TextDocumentSync *rpc.Union2[TextDocumentSyncOptions, TextDocumentSyncKind] `json:"textDocumentSync,omitempty"`
	/*
		Defines the capabilities provided by a language
		server.
	*/
	NotebookDocumentSync *rpc.Union2[NotebookDocumentSyncOptions, NotebookDocumentSyncRegistrationOptions] `json:"notebookDocumentSync,omitempty"`
	/*
		Defines the capabilities provided by a language
		server.
	*/
	CompletionProvider *CompletionOptions `json:"completionProvider,omitempty"`
	/*
		Defines the capabilities provided by a language
		server.
	*/
	HoverProvider *rpc.Union2[bool, HoverOptions] `json:"hoverProvider,omitempty"`
	/*
		Defines the capabilities provided by a language
		server.
	*/
	SignatureHelpProvider *SignatureHelpOptions `json:"signatureHelpProvider,omitempty"`
	/*
		Defines the capabilities provided by a language
		server.
	*/
	DeclarationProvider *rpc.Union3[bool, DeclarationOptions, DeclarationRegistrationOptions] `json:"declarationProvider,omitempty"` // boolean | DeclarationOptions | DeclarationRegistrationOptions
	/*
		Defines the capabilities provided by a language
		server.
	*/
	DefinitionProvider *rpc.Union2[bool, DefinitionOptions] `json:"definitionProvider,omitempty"`
	/*
		Defines the capabilities provided by a language
		server.
	*/
	TypeDefinitionProvider *rpc.Union3[bool, TypeDefinitionOptions, TypeDefinitionRegistrationOptions] `json:"typeDefinitionProvider,omitempty"` // boolean | TypeDefinitionOptions | TypeDefinitionRegistrationOptions
	/*
		Defines the capabilities provided by a language
		server.
	*/
	ImplementationProvider *rpc.Union3[bool, ImplementationOptions, ImplementationRegistrationOptions] `json:"implementationProvider,omitempty"` // boolean | ImplementationOptions | ImplementationRegistrationOptions
	/*
		Defines the capabilities provided by a language
		server.
	*/
	ReferencesProvider *rpc.Union2[bool, ReferenceOptions] `json:"referencesProvider,omitempty"`
	/*
		Defines the capabilities provided by a language
		server.
	*/
	DocumentHighlightProvider *rpc.Union2[bool, DocumentHighlightOptions] `json:"documentHighlightProvider,omitempty"`
	/*
		Defines the capabilities provided by a language
		server.
	*/
	DocumentSymbolProvider *rpc.Union2[bool, DocumentSymbolOptions] `json:"documentSymbolProvider,omitempty"`
	/*
		Defines the capabilities provided by a language
		server.
	*/
	CodeActionProvider *rpc.Union2[bool, CodeActionOptions] `json:"codeActionProvider,omitempty"`
	/*
		Defines the capabilities provided by a language
		server.
	*/
	CodeLensProvider *CodeLensOptions `json:"codeLensProvider,omitempty"`
	/*
		Defines the capabilities provided by a language
		server.
	*/
	DocumentLinkProvider *DocumentLinkOptions `json:"documentLinkProvider,omitempty"`
	/*
		Defines the capabilities provided by a language
		server.
	*/
	ColorProvider *rpc.Union3[bool, DocumentColorOptions, DocumentColorRegistrationOptions] `json:"colorProvider,omitempty"` // boolean | DocumentColorOptions | DocumentColorRegistrationOptions
	/*
		Defines the capabilities provided by a language
		server.
	*/
	WorkspaceSymbolProvider *rpc.Union2[bool, WorkspaceSymbolOptions] `json:"workspaceSymbolProvider,omitempty"`
	/*
		Defines the capabilities provided by a language
		server.
	*/
	DocumentFormattingProvider *rpc.Union2[bool, DocumentFormattingOptions] `json:"documentFormattingProvider,omitempty"`
	/*
		Defines the capabilities provided by a language
		server.
	*/
	DocumentRangeFormattingProvider *rpc.Union2[bool, DocumentRangeFormattingOptions] `json:"documentRangeFormattingProvider,omitempty"`
	/*
		Defines the capabilities provided by a language
		server.
	*/
	DocumentOnTypeFormattingProvider *DocumentOnTypeFormattingOptions `json:"documentOnTypeFormattingProvider,omitempty"`
	/*
		Defines the capabilities provided by a language
		server.
	*/
	RenameProvider *rpc.Union2[bool, RenameOptions] `json:"renameProvider,omitempty"`
	/*
		Defines the capabilities provided by a language
		server.
	*/
	FoldingRangeProvider *rpc.Union3[bool, FoldingRangeOptions, FoldingRangeRegistrationOptions] `json:"foldingRangeProvider,omitempty"` // boolean | FoldingRangeOptions | FoldingRangeRegistrationOptions
	/*
		Defines the capabilities provided by a language
		server.
	*/
	SelectionRangeProvider *rpc.Union3[bool, SelectionRangeOptions, SelectionRangeRegistrationOptions] `json:"selectionRangeProvider,omitempty"` // boolean | SelectionRangeOptions | SelectionRangeRegistrationOptions
	/*
		Defines the capabilities provided by a language
		server.
	*/
	ExecuteCommandProvider *ExecuteCommandOptions `json:"executeCommandProvider,omitempty"`
	/*
		Defines the capabilities provided by a language
		server.
	*/
	CallHierarchyProvider *rpc.Union3[bool, CallHierarchyOptions, CallHierarchyRegistrationOptions] `json:"callHierarchyProvider,omitempty"` // boolean | CallHierarchyOptions | CallHierarchyRegistrationOptions
	/*
		Defines the capabilities provided by a language
		server.
	*/
	LinkedEditingRangeProvider *rpc.Union3[bool, LinkedEditingRangeOptions, LinkedEditingRangeRegistrationOptions] `json:"linkedEditingRangeProvider,omitempty"` // boolean | LinkedEditingRangeOptions | LinkedEditingRangeRegistrationOptions
	/*
		Defines the capabilities provided by a language
		server.
	*/
	SemanticTokensProvider *rpc.Union2[SemanticTokensOptions, SemanticTokensRegistrationOptions] `json:"semanticTokensProvider,omitempty"`
	/*
		Defines the capabilities provided by a language
		server.
	*/
	MonikerProvider *rpc.Union3[bool, MonikerOptions, MonikerRegistrationOptions] `json:"monikerProvider,omitempty"` // boolean | MonikerOptions | MonikerRegistrationOptions
	/*
		Defines the capabilities provided by a language
		server.
	*/
	TypeHierarchyProvider *rpc.Union3[bool, TypeHierarchyOptions, TypeHierarchyRegistrationOptions] `json:"typeHierarchyProvider,omitempty"` // boolean | TypeHierarchyOptions | TypeHierarchyRegistrationOptions
	/*
		Defines the capabilities provided by a language
		server.
	*/
	InlineValueProvider *rpc.Union3[bool, InlineValueOptions, InlineValueRegistrationOptions] `json:"inlineValueProvider,omitempty"` // boolean | InlineValueOptions | InlineValueRegistrationOptions
	/*
		Defines the capabilities provided by a language
		server.
	*/
	InlayHintProvider *rpc.Union3[bool, InlayHintOptions, InlayHintRegistrationOptions] `json:"inlayHintProvider,omitempty"` // boolean | InlayHintOptions | InlayHintRegistrationOptions
	/*
		Defines the capabilities provided by a language
		server.
	*/
	DiagnosticProvider *rpc.Union2[DiagnosticOptions, DiagnosticRegistrationOptions] `json:"diagnosticProvider,omitempty"`
	/*
		Defines the capabilities provided by a language
		server.
	*/
	InlineCompletionProvider *rpc.Union2[bool, InlineCompletionOptions] `json:"inlineCompletionProvider,omitempty"`
	/*
		Defines the capabilities provided by a language
		server.
	*/
	Workspace *WorkspaceOptions `json:"workspace,omitempty"`
	/*
		Defines the capabilities provided by a language
		server.
	*/
	Experimental any `json:"experimental,omitempty"`
}

// @since 3.18.0
type ServerCompletionItemOptions struct {
	// @since 3.18.0
	LabelDetailsSupport *bool `json:"labelDetailsSupport,omitempty"`
}

/*
Information about the server

@since 3.15.0
@since 3.18.0 ServerInfo type name added.
*/
type ServerInfo struct {
	/*
		Information about the server

		@since 3.15.0
		@since 3.18.0 ServerInfo type name added.
	*/
	Name string `json:"name"`
	/*
		Information about the server

		@since 3.15.0
		@since 3.18.0 ServerInfo type name added.
	*/
	Version string `json:"version,omitempty"`
}

// Client Capabilities for a [SignatureHelpRequest].
type SignatureHelpClientCapabilities struct {
	// Client Capabilities for a [SignatureHelpRequest].
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
	// Client Capabilities for a [SignatureHelpRequest].
	SignatureInformation *ClientSignatureInformationOptions `json:"signatureInformation,omitempty"`
	// Client Capabilities for a [SignatureHelpRequest].
	ContextSupport *bool `json:"contextSupport,omitempty"`
}

/*
Additional information about the context in which a signature help request was triggered.

@since 3.15.0
*/
type SignatureHelpContext struct {
	/*
		Additional information about the context in which a signature help request was triggered.

		@since 3.15.0
	*/
	TriggerKind SignatureHelpTriggerKind `json:"triggerKind"`
	/*
		Additional information about the context in which a signature help request was triggered.

		@since 3.15.0
	*/
	TriggerCharacter string `json:"triggerCharacter,omitempty"`
	/*
		Additional information about the context in which a signature help request was triggered.

		@since 3.15.0
	*/
	IsRetrigger bool `json:"isRetrigger"`
	/*
		Additional information about the context in which a signature help request was triggered.

		@since 3.15.0
	*/
	ActiveSignatureHelp *SignatureHelp `json:"activeSignatureHelp,omitempty"`
}

// Server Capabilities for a [SignatureHelpRequest].
type SignatureHelpOptions struct {
	WorkDoneProgressOptions
	// Server Capabilities for a [SignatureHelpRequest].
	TriggerCharacters *[]string `json:"triggerCharacters,omitempty"`
	// Server Capabilities for a [SignatureHelpRequest].
	RetriggerCharacters *[]string `json:"retriggerCharacters,omitempty"`
}

/*
An interactive text edit.

@since 3.18.0
*/
type SnippetTextEdit struct {
	/*
		An interactive text edit.

		@since 3.18.0
	*/
	Range Range `json:"range"`
	/*
		An interactive text edit.

		@since 3.18.0
	*/
	Snippet StringValue `json:"snippet"`
	/*
		An interactive text edit.

		@since 3.18.0
	*/
	AnnotationId *ChangeAnnotationIdentifier `json:"annotationId,omitempty"`
}

// @since 3.18.0
type StaleRequestSupportOptions struct {
	// @since 3.18.0
	Cancel bool `json:"cancel"`
	// @since 3.18.0
	RetryOnContentModified []string `json:"retryOnContentModified"`
}

/*
Static registration options to be returned in the initialize
request.
*/
type StaticRegistrationOptions struct {
	/*
		Static registration options to be returned in the initialize
		request.
	*/
	Id string `json:"id,omitempty"`
}

/*
A string value used as a snippet is a template which allows to insert text
and to control the editor cursor when insertion happens.

A snippet can define tab stops and placeholders with `$1`, `$2`
and `${3:foo}`. `$0` defines the final tab stop, it defaults to
the end of the snippet. Variables are defined with `$name` and
`${name:default value}`.

@since 3.18.0
*/
type StringValue struct {
	/*
		A string value used as a snippet is a template which allows to insert text
		and to control the editor cursor when insertion happens.

		A snippet can define tab stops and placeholders with `$1`, `$2`
		and `${3:foo}`. `$0` defines the final tab stop, it defaults to
		the end of the snippet. Variables are defined with `$name` and
		`${name:default value}`.

		@since 3.18.0
	*/
	Kind string `json:"kind"` // snippet
	/*
		A string value used as a snippet is a template which allows to insert text
		and to control the editor cursor when insertion happens.

		A snippet can define tab stops and placeholders with `$1`, `$2`
		and `${3:foo}`. `$0` defines the final tab stop, it defaults to
		the end of the snippet. Variables are defined with `$name` and
		`${name:default value}`.

		@since 3.18.0
	*/
	Value string `json:"value"`
}

/*
Represents information about programming constructs like variables, classes,
interfaces etc.
*/
type SymbolInformation struct {
	BaseSymbolInformation
	/*
		Represents information about programming constructs like variables, classes,
		interfaces etc.
	*/
	Deprecated *bool `json:"deprecated,omitempty"`
	/*
		Represents information about programming constructs like variables, classes,
		interfaces etc.
	*/
	Location Location `json:"location"`
}

// @since 3.18.0
type TextDocumentContentChangePartial struct {
	// @since 3.18.0
	Range Range `json:"range"`
	// @since 3.18.0
	RangeLength uint32 `json:"rangeLength,omitempty"`
	// @since 3.18.0
	Text string `json:"text"`
}

// @since 3.18.0
type TextDocumentContentChangeWholeDocument struct {
	// @since 3.18.0
	Text string `json:"text"`
}

/*
Client capabilities for a text document content provider.

@since 3.18.0
*/
type TextDocumentContentClientCapabilities struct {
	/*
		Client capabilities for a text document content provider.

		@since 3.18.0
	*/
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
}

/*
Text document content provider options.

@since 3.18.0
*/
type TextDocumentContentOptions struct {
	/*
		Text document content provider options.

		@since 3.18.0
	*/
	Schemes []string `json:"schemes"`
}

type TextDocumentFilterClientCapabilities struct {
	RelativePatternSupport *bool `json:"relativePatternSupport,omitempty"`
}

/*
A document filter where `language` is required field.

@since 3.18.0
*/
type TextDocumentFilterLanguage struct {
	/*
		A document filter where `language` is required field.

		@since 3.18.0
	*/
	Language string `json:"language"`
	/*
		A document filter where `language` is required field.

		@since 3.18.0
	*/
	Scheme string `json:"scheme,omitempty"`
	/*
		A document filter where `language` is required field.

		@since 3.18.0
	*/
	Pattern *GlobPattern `json:"pattern,omitempty"`
}

/*
A document filter where `pattern` is required field.

@since 3.18.0
*/
type TextDocumentFilterPattern struct {
	/*
		A document filter where `pattern` is required field.

		@since 3.18.0
	*/
	Language string `json:"language,omitempty"`
	/*
		A document filter where `pattern` is required field.

		@since 3.18.0
	*/
	Scheme string `json:"scheme,omitempty"`
	/*
		A document filter where `pattern` is required field.

		@since 3.18.0
	*/
	Pattern GlobPattern `json:"pattern"`
}

/*
A document filter where `scheme` is required field.

@since 3.18.0
*/
type TextDocumentFilterScheme struct {
	/*
		A document filter where `scheme` is required field.

		@since 3.18.0
	*/
	Language string `json:"language,omitempty"`
	/*
		A document filter where `scheme` is required field.

		@since 3.18.0
	*/
	Scheme string `json:"scheme"`
	/*
		A document filter where `scheme` is required field.

		@since 3.18.0
	*/
	Pattern *GlobPattern `json:"pattern,omitempty"`
}

// A literal to identify a text document in the client.
type TextDocumentIdentifier struct {
	// A literal to identify a text document in the client.
	Uri DocumentURI `json:"uri"`
}

/*
An item to transfer a text document from the client to the
server.
*/
type TextDocumentItem struct {
	/*
		An item to transfer a text document from the client to the
		server.
	*/
	Uri DocumentURI `json:"uri"`
	/*
		An item to transfer a text document from the client to the
		server.
	*/
	LanguageId LanguageKind `json:"languageId"`
	/*
		An item to transfer a text document from the client to the
		server.
	*/
	Version int `json:"version"`
	/*
		An item to transfer a text document from the client to the
		server.
	*/
	Text string `json:"text"`
}

/*
A parameter literal used in requests to pass a text document and a position inside that
document.
*/
type TextDocumentPositionParams struct {
	/*
		A parameter literal used in requests to pass a text document and a position inside that
		document.
	*/
	TextDocument TextDocumentIdentifier `json:"textDocument"`
	/*
		A parameter literal used in requests to pass a text document and a position inside that
		document.
	*/
	Position Position `json:"position"`
}

type TextDocumentSyncOptions struct {
	OpenClose         *bool                          `json:"openClose,omitempty"`
	Change            *TextDocumentSyncKind          `json:"change,omitempty"`
	WillSave          *bool                          `json:"willSave,omitempty"`
	WillSaveWaitUntil *bool                          `json:"willSaveWaitUntil,omitempty"`
	Save              *rpc.Union2[bool, SaveOptions] `json:"save,omitempty"`
}

// A text edit applicable to a text document.
type TextEdit struct {
	// A text edit applicable to a text document.
	Range Range `json:"range"`
	// A text edit applicable to a text document.
	NewText string `json:"newText"`
}

// Since 3.6.0
type TypeDefinitionClientCapabilities struct {
	// Since 3.6.0
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
	// Since 3.6.0
	LinkSupport *bool `json:"linkSupport,omitempty"`
}

type TypeDefinitionOptions struct {
	WorkDoneProgressOptions
}

// @since 3.17.0
type TypeHierarchyItem struct {
	// @since 3.17.0
	Name string `json:"name"`
	// @since 3.17.0
	Kind SymbolKind `json:"kind"`
	// @since 3.17.0
	Tags *[]SymbolTag `json:"tags,omitempty"`
	// @since 3.17.0
	Detail string `json:"detail,omitempty"`
	// @since 3.17.0
	Uri DocumentURI `json:"uri"`
	// @since 3.17.0
	Range Range `json:"range"`
	// @since 3.17.0
	SelectionRange Range `json:"selectionRange"`
	// @since 3.17.0
	Data any `json:"data,omitempty"`
}

/*
Type hierarchy options used during static registration.

@since 3.17.0
*/
type TypeHierarchyOptions struct {
	WorkDoneProgressOptions
}

// General parameters to unregister a request or notification.
type Unregistration struct {
	// General parameters to unregister a request or notification.
	Id string `json:"id"`
	// General parameters to unregister a request or notification.
	Method string `json:"method"`
}

// A text document identifier to denote a specific version of a text document.
type VersionedTextDocumentIdentifier struct {
	TextDocumentIdentifier
	// A text document identifier to denote a specific version of a text document.
	Version int `json:"version"`
}

type WorkDoneProgressBegin struct {
	Kind        string `json:"kind"` // begin
	Title       string `json:"title"`
	Cancellable *bool  `json:"cancellable,omitempty"`
	Message     string `json:"message,omitempty"`
	Percentage  uint32 `json:"percentage,omitempty"`
}

type WorkDoneProgressOptions struct {
	WorkDoneProgress *bool `json:"workDoneProgress,omitempty"`
}

type WorkDoneProgressParams struct {
	WorkDoneToken *ProgressToken `json:"workDoneToken,omitempty"`
}

type WorkDoneProgressReport struct {
	Kind        string `json:"kind"` // report
	Cancellable *bool  `json:"cancellable,omitempty"`
	Message     string `json:"message,omitempty"`
	Percentage  uint32 `json:"percentage,omitempty"`
}

// Workspace specific client capabilities.
type WorkspaceClientCapabilities struct {
	// Workspace specific client capabilities.
	ApplyEdit *bool `json:"applyEdit,omitempty"`
	// Workspace specific client capabilities.
	WorkspaceEdit *WorkspaceEditClientCapabilities `json:"workspaceEdit,omitempty"`
	// Workspace specific client capabilities.
	DidChangeConfiguration *DidChangeConfigurationClientCapabilities `json:"didChangeConfiguration,omitempty"`
	// Workspace specific client capabilities.
	DidChangeWatchedFiles *DidChangeWatchedFilesClientCapabilities `json:"didChangeWatchedFiles,omitempty"`
	// Workspace specific client capabilities.
	Symbol *WorkspaceSymbolClientCapabilities `json:"symbol,omitempty"`
	// Workspace specific client capabilities.
	ExecuteCommand *ExecuteCommandClientCapabilities `json:"executeCommand,omitempty"`
	// Workspace specific client capabilities.
	WorkspaceFolders *bool `json:"workspaceFolders,omitempty"`
	// Workspace specific client capabilities.
	Configuration *bool `json:"configuration,omitempty"`
	// Workspace specific client capabilities.
	SemanticTokens *SemanticTokensWorkspaceClientCapabilities `json:"semanticTokens,omitempty"`
	// Workspace specific client capabilities.
	CodeLens *CodeLensWorkspaceClientCapabilities `json:"codeLens,omitempty"`
	// Workspace specific client capabilities.
	FileOperations *FileOperationClientCapabilities `json:"fileOperations,omitempty"`
	// Workspace specific client capabilities.
	InlineValue *InlineValueWorkspaceClientCapabilities `json:"inlineValue,omitempty"`
	// Workspace specific client capabilities.
	InlayHint *InlayHintWorkspaceClientCapabilities `json:"inlayHint,omitempty"`
	// Workspace specific client capabilities.
	Diagnostics *DiagnosticWorkspaceClientCapabilities `json:"diagnostics,omitempty"`
	// Workspace specific client capabilities.
	FoldingRange *FoldingRangeWorkspaceClientCapabilities `json:"foldingRange,omitempty"`
	// Workspace specific client capabilities.
	TextDocumentContent *TextDocumentContentClientCapabilities `json:"textDocumentContent,omitempty"`
}

/*
A workspace edit represents changes to many resources managed in the workspace. The edit
should either provide `changes` or `documentChanges`. If documentChanges are present
they are preferred over `changes` if the client can handle versioned document edits.

Since version 3.13.0 a workspace edit can contain resource operations as well. If resource
operations are present clients need to execute the operations in the order in which they
are provided. So a workspace edit for example can consist of the following two changes:
(1) a create file a.txt and (2) a text document edit which insert text into file a.txt.

An invalid sequence (e.g. (1) delete file a.txt and (2) insert text into file a.txt) will
cause failure of the operation. How the client recovers from the failure is described by
the client capability: `workspace.workspaceEdit.failureHandling`
*/
type WorkspaceEdit struct {
	/*
		A workspace edit represents changes to many resources managed in the workspace. The edit
		should either provide `changes` or `documentChanges`. If documentChanges are present
		they are preferred over `changes` if the client can handle versioned document edits.

		Since version 3.13.0 a workspace edit can contain resource operations as well. If resource
		operations are present clients need to execute the operations in the order in which they
		are provided. So a workspace edit for example can consist of the following two changes:
		(1) a create file a.txt and (2) a text document edit which insert text into file a.txt.

		An invalid sequence (e.g. (1) delete file a.txt and (2) insert text into file a.txt) will
		cause failure of the operation. How the client recovers from the failure is described by
		the client capability: `workspace.workspaceEdit.failureHandling`
	*/
	Changes *map[DocumentURI]struct{} `json:"changes,omitempty"`
	/*
		A workspace edit represents changes to many resources managed in the workspace. The edit
		should either provide `changes` or `documentChanges`. If documentChanges are present
		they are preferred over `changes` if the client can handle versioned document edits.

		Since version 3.13.0 a workspace edit can contain resource operations as well. If resource
		operations are present clients need to execute the operations in the order in which they
		are provided. So a workspace edit for example can consist of the following two changes:
		(1) a create file a.txt and (2) a text document edit which insert text into file a.txt.

		An invalid sequence (e.g. (1) delete file a.txt and (2) insert text into file a.txt) will
		cause failure of the operation. How the client recovers from the failure is described by
		the client capability: `workspace.workspaceEdit.failureHandling`
	*/
	DocumentChanges *[]any `json:"documentChanges,omitempty"` // TextDocumentEdit | CreateFile | RenameFile | DeleteFile[]
	/*
		A workspace edit represents changes to many resources managed in the workspace. The edit
		should either provide `changes` or `documentChanges`. If documentChanges are present
		they are preferred over `changes` if the client can handle versioned document edits.

		Since version 3.13.0 a workspace edit can contain resource operations as well. If resource
		operations are present clients need to execute the operations in the order in which they
		are provided. So a workspace edit for example can consist of the following two changes:
		(1) a create file a.txt and (2) a text document edit which insert text into file a.txt.

		An invalid sequence (e.g. (1) delete file a.txt and (2) insert text into file a.txt) will
		cause failure of the operation. How the client recovers from the failure is described by
		the client capability: `workspace.workspaceEdit.failureHandling`
	*/
	ChangeAnnotations *map[ChangeAnnotationIdentifier]struct{} `json:"changeAnnotations,omitempty"`
}

type WorkspaceEditClientCapabilities struct {
	DocumentChanges         *bool                            `json:"documentChanges,omitempty"`
	ResourceOperations      *[]ResourceOperationKind         `json:"resourceOperations,omitempty"`
	FailureHandling         *FailureHandlingKind             `json:"failureHandling,omitempty"`
	NormalizesLineEndings   *bool                            `json:"normalizesLineEndings,omitempty"`
	ChangeAnnotationSupport *ChangeAnnotationsSupportOptions `json:"changeAnnotationSupport,omitempty"`
	MetadataSupport         *bool                            `json:"metadataSupport,omitempty"`
	SnippetEditSupport      *bool                            `json:"snippetEditSupport,omitempty"`
}

/*
Additional data about a workspace edit.

@since 3.18.0
*/
type WorkspaceEditMetadata struct {
	/*
		Additional data about a workspace edit.

		@since 3.18.0
	*/
	IsRefactoring *bool `json:"isRefactoring,omitempty"`
}

// A workspace folder inside a client.
type WorkspaceFolder struct {
	// A workspace folder inside a client.
	Uri URI `json:"uri"`
	// A workspace folder inside a client.
	Name string `json:"name"`
}

// The workspace folder change event.
type WorkspaceFoldersChangeEvent struct {
	// The workspace folder change event.
	Added []WorkspaceFolder `json:"added"`
	// The workspace folder change event.
	Removed []WorkspaceFolder `json:"removed"`
}

type WorkspaceFoldersInitializeParams struct {
	WorkspaceFolders *[]WorkspaceFolder `json:"workspaceFolders,omitempty"` // WorkspaceFolder[] | null
}

type WorkspaceFoldersServerCapabilities struct {
	Supported           *bool                     `json:"supported,omitempty"`
	ChangeNotifications *rpc.Union2[string, bool] `json:"changeNotifications,omitempty"`
}

/*
A full document diagnostic report for a workspace diagnostic result.

@since 3.17.0
*/
type WorkspaceFullDocumentDiagnosticReport struct {
	FullDocumentDiagnosticReport
	/*
		A full document diagnostic report for a workspace diagnostic result.

		@since 3.17.0
	*/
	Uri DocumentURI `json:"uri"`
	/*
		A full document diagnostic report for a workspace diagnostic result.

		@since 3.17.0
	*/
	Version int `json:"version,omitempty"` // integer | null
}

/*
Defines workspace specific capabilities of the server.

@since 3.18.0
*/
type WorkspaceOptions struct {
	/*
		Defines workspace specific capabilities of the server.

		@since 3.18.0
	*/
	WorkspaceFolders *WorkspaceFoldersServerCapabilities `json:"workspaceFolders,omitempty"`
	/*
		Defines workspace specific capabilities of the server.

		@since 3.18.0
	*/
	FileOperations *FileOperationOptions `json:"fileOperations,omitempty"`
	/*
		Defines workspace specific capabilities of the server.

		@since 3.18.0
	*/
	TextDocumentContent *rpc.Union2[TextDocumentContentOptions, TextDocumentContentRegistrationOptions] `json:"textDocumentContent,omitempty"`
}

// Server capabilities for a [WorkspaceSymbolRequest].
type WorkspaceSymbolOptions struct {
	WorkDoneProgressOptions
	// Server capabilities for a [WorkspaceSymbolRequest].
	ResolveProvider *bool `json:"resolveProvider,omitempty"`
}

// The initialize parameters
type _InitializeParams struct {
	WorkDoneProgressParams
	// The initialize parameters
	ProcessId int `json:"processId,omitempty"` // integer | null
	// The initialize parameters
	ClientInfo *ClientInfo `json:"clientInfo,omitempty"`
	// The initialize parameters
	Locale string `json:"locale,omitempty"`
	// The initialize parameters
	RootPath string `json:"rootPath,omitempty"` // string | null
	// The initialize parameters
	RootUri *DocumentURI `json:"rootUri,omitempty"` // DocumentUri | null
	// The initialize parameters
	Capabilities *ClientCapabilities `json:"capabilities"`
	// The initialize parameters
	InitializationOptions any `json:"initializationOptions,omitempty"`
	// The initialize parameters
	Trace *TraceValue `json:"trace,omitempty"`
}

/*
Defines how values from a set of defaults and an individual item will be
merged.

@since 3.18.0
*/
type ApplyKind uint32

const (
	/*
		The value from the individual item (if provided and not `null`) will be
		used instead of the default.
	*/
	ApplyReplace ApplyKind = 1
	/*
		The value from the item will be merged with the default.

		The specific rules for mergeing values are defined against each field
		that supports merging.
	*/
	ApplyMerge ApplyKind = 2
)
