// Code generated by lsp/generate; DO NOT EDIT.
package lsp

/*
The parameter of a `callHierarchy/incomingCalls` request.

@since 3.16.0
*/
type CallHierarchyIncomingCallsParams struct {
	WorkDoneProgressParams
	PartialResultParams
	/*
		The parameter of a `callHierarchy/incomingCalls` request.

		@since 3.16.0
	*/
	Item *CallHierarchyItem `json:"item"`
}

/*
Represents programming constructs like functions or constructors in the context
of call hierarchy.

@since 3.16.0
*/
type CallHierarchyItem struct {
	/*
		Represents programming constructs like functions or constructors in the context
		of call hierarchy.

		@since 3.16.0
	*/
	Name string `json:"name"`
	/*
		Represents programming constructs like functions or constructors in the context
		of call hierarchy.

		@since 3.16.0
	*/
	Kind SymbolKind `json:"kind"`
	/*
		Represents programming constructs like functions or constructors in the context
		of call hierarchy.

		@since 3.16.0
	*/
	Tags []SymbolTag `json:"tags,omitempty"`
	/*
		Represents programming constructs like functions or constructors in the context
		of call hierarchy.

		@since 3.16.0
	*/
	Detail string `json:"detail,omitempty"`
	/*
		Represents programming constructs like functions or constructors in the context
		of call hierarchy.

		@since 3.16.0
	*/
	Uri DocumentURI `json:"uri"`
	/*
		Represents programming constructs like functions or constructors in the context
		of call hierarchy.

		@since 3.16.0
	*/
	Range Range `json:"range"`
	/*
		Represents programming constructs like functions or constructors in the context
		of call hierarchy.

		@since 3.16.0
	*/
	SelectionRange Range `json:"selectionRange"`
	/*
		Represents programming constructs like functions or constructors in the context
		of call hierarchy.

		@since 3.16.0
	*/
	Data any `json:"data,omitempty"`
}

/*
The parameter of a `callHierarchy/outgoingCalls` request.

@since 3.16.0
*/
type CallHierarchyOutgoingCallsParams struct {
	WorkDoneProgressParams
	PartialResultParams
	/*
		The parameter of a `callHierarchy/outgoingCalls` request.

		@since 3.16.0
	*/
	Item *CallHierarchyItem `json:"item"`
}
