// Code generated by lsp/generate; DO NOT EDIT.
package lsp

type RegistrationParams struct {
	Registrations []Registration `json:"registrations"`
}

/*
Client capabilities specific to regular expressions.

@since 3.16.0
*/
type RegularExpressionsClientCapabilities struct {
	/*
		Client capabilities specific to regular expressions.

		@since 3.16.0
	*/
	Engine RegularExpressionEngineKind `json:"engine"`
	/*
		Client capabilities specific to regular expressions.

		@since 3.16.0
	*/
	Version string `json:"version,omitempty"`
}

type UnregistrationParams struct {
	Unregisterations []Unregistration `json:"unregisterations"`
}

/*
A versioned notebook document identifier.

@since 3.17.0
*/
type VersionedNotebookDocumentIdentifier struct {
	/*
		A versioned notebook document identifier.

		@since 3.17.0
	*/
	Version int `json:"version"`
	/*
		A versioned notebook document identifier.

		@since 3.17.0
	*/
	Uri URI `json:"uri"`
}

type RegularExpressionEngineKind = string

type WatchKind uint32

const (
	// Interested in create events.
	WatchCreate WatchKind = 1
	// Interested in change events
	WatchChange WatchKind = 2
	// Interested in delete events
	WatchDelete WatchKind = 4
)
