// Code generated by lsp/generate; DO NOT EDIT.
package lsp

/*
A code action represents a change that can be performed in code, e.g. to fix a problem or
to refactor code.

A CodeAction must set either `edit` and/or a `command`. If both are supplied, the `edit` is applied first, then the `command` is executed.
*/
type CodeAction struct {
	/*
		A code action represents a change that can be performed in code, e.g. to fix a problem or
		to refactor code.

		A CodeAction must set either `edit` and/or a `command`. If both are supplied, the `edit` is applied first, then the `command` is executed.
	*/
	Title string `json:"title"`
	/*
		A code action represents a change that can be performed in code, e.g. to fix a problem or
		to refactor code.

		A CodeAction must set either `edit` and/or a `command`. If both are supplied, the `edit` is applied first, then the `command` is executed.
	*/
	Kind *CodeActionKind `json:"kind,omitempty"`
	/*
		A code action represents a change that can be performed in code, e.g. to fix a problem or
		to refactor code.

		A CodeAction must set either `edit` and/or a `command`. If both are supplied, the `edit` is applied first, then the `command` is executed.
	*/
	Diagnostics *[]*Diagnostic `json:"diagnostics,omitempty"`
	/*
		A code action represents a change that can be performed in code, e.g. to fix a problem or
		to refactor code.

		A CodeAction must set either `edit` and/or a `command`. If both are supplied, the `edit` is applied first, then the `command` is executed.
	*/
	IsPreferred *bool `json:"isPreferred,omitempty"`
	/*
		A code action represents a change that can be performed in code, e.g. to fix a problem or
		to refactor code.

		A CodeAction must set either `edit` and/or a `command`. If both are supplied, the `edit` is applied first, then the `command` is executed.
	*/
	Disabled *CodeActionDisabled `json:"disabled,omitempty"`
	/*
		A code action represents a change that can be performed in code, e.g. to fix a problem or
		to refactor code.

		A CodeAction must set either `edit` and/or a `command`. If both are supplied, the `edit` is applied first, then the `command` is executed.
	*/
	Edit *WorkspaceEdit `json:"edit,omitempty"`
	/*
		A code action represents a change that can be performed in code, e.g. to fix a problem or
		to refactor code.

		A CodeAction must set either `edit` and/or a `command`. If both are supplied, the `edit` is applied first, then the `command` is executed.
	*/
	Command *Command `json:"command,omitempty"`
	/*
		A code action represents a change that can be performed in code, e.g. to fix a problem or
		to refactor code.

		A CodeAction must set either `edit` and/or a `command`. If both are supplied, the `edit` is applied first, then the `command` is executed.
	*/
	Data any `json:"data,omitempty"`
	/*
		A code action represents a change that can be performed in code, e.g. to fix a problem or
		to refactor code.

		A CodeAction must set either `edit` and/or a `command`. If both are supplied, the `edit` is applied first, then the `command` is executed.
	*/
	Tags *[]CodeActionTag `json:"tags,omitempty"`
}

// The Client Capabilities of a [CodeActionRequest].
type CodeActionClientCapabilities struct {
	// The Client Capabilities of a [CodeActionRequest].
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
	// The Client Capabilities of a [CodeActionRequest].
	CodeActionLiteralSupport *ClientCodeActionLiteralOptions `json:"codeActionLiteralSupport,omitempty"`
	// The Client Capabilities of a [CodeActionRequest].
	IsPreferredSupport *bool `json:"isPreferredSupport,omitempty"`
	// The Client Capabilities of a [CodeActionRequest].
	DisabledSupport *bool `json:"disabledSupport,omitempty"`
	// The Client Capabilities of a [CodeActionRequest].
	DataSupport *bool `json:"dataSupport,omitempty"`
	// The Client Capabilities of a [CodeActionRequest].
	ResolveSupport *ClientCodeActionResolveOptions `json:"resolveSupport,omitempty"`
	// The Client Capabilities of a [CodeActionRequest].
	HonorsChangeAnnotations *bool `json:"honorsChangeAnnotations,omitempty"`
	// The Client Capabilities of a [CodeActionRequest].
	DocumentationSupport *bool `json:"documentationSupport,omitempty"`
	// The Client Capabilities of a [CodeActionRequest].
	TagSupport *CodeActionTagOptions `json:"tagSupport,omitempty"`
}

// A set of predefined code action kinds
type CodeActionKind string

const (
	// Empty kind.
	CodeActionEmpty CodeActionKind = ""
	// Base kind for quickfix actions: 'quickfix'
	CodeActionQuickFix CodeActionKind = "quickfix"
	// Base kind for refactoring actions: 'refactor'
	CodeActionRefactor CodeActionKind = "refactor"
	/*
		Base kind for refactoring extraction actions: 'refactor.extract'

		Example extract actions:


		- Extract method
			- Extract function
			- Extract variable
			- Extract interface from class
			- ...
	*/
	CodeActionRefactorExtract CodeActionKind = "refactor.extract"
	/*
		Base kind for refactoring inline actions: 'refactor.inline'

		Example inline actions:


		- Inline function
			- Inline variable
			- Inline constant
			- ...
	*/
	CodeActionRefactorInline CodeActionKind = "refactor.inline"
	/*
		Base kind for refactoring move actions: `refactor.move`

		Example move actions:


		- Move a function to a new file
			- Move a property between classes
			- Move method to base class
			- ...

		@since 3.18.0
	*/
	CodeActionRefactorMove CodeActionKind = "refactor.move"
	/*
		Base kind for refactoring rewrite actions: 'refactor.rewrite'

		Example rewrite actions:


		- Convert JavaScript function to class
			- Add or remove parameter
			- Encapsulate field
			- Make method static
			- Move method to base class
			- ...
	*/
	CodeActionRefactorRewrite CodeActionKind = "refactor.rewrite"
	/*
		Base kind for source actions: `source`

		Source code actions apply to the entire file.
	*/
	CodeActionSource CodeActionKind = "source"
	// Base kind for an organize imports source action: `source.organizeImports`
	CodeActionSourceOrganizeImports CodeActionKind = "source.organizeImports"
	/*
		Base kind for auto-fix source actions: `source.fixAll`.

		Fix all actions automatically fix errors that have a clear fix that do not require user input.
		They should not suppress errors or perform unsafe fixes such as generating new types or classes.

		@since 3.15.0
	*/
	CodeActionSourceFixAll CodeActionKind = "source.fixAll"
	/*
		Base kind for all code actions applying to the entire notebook's scope. CodeActionKinds using
		this should always begin with `notebook.`

		@since 3.18.0
	*/
	CodeActionNotebook CodeActionKind = "notebook"
)
