// Code generated by lsp/generate; DO NOT EDIT.
package lsp

/*
A code action represents a change that can be performed in code, e.g. to fix a problem or
to refactor code.

A CodeAction must set either `edit` and/or a `command`. If both are supplied, the `edit` is applied first, then the `command` is executed.
*/
type CodeAction struct {
	// A short, human-readable, title for this code action.
	Title string `json:"title"`
	/*
		The kind of the code action.

		Used to filter code actions.
	*/
	Kind *CodeActionKind `json:"kind,omitempty"`
	// The diagnostics that this code action resolves.
	Diagnostics []*Diagnostic `json:"diagnostics,omitempty"`
	/*
		Marks this as a preferred action. Preferred actions are used by the `auto fix` command and can be targeted
		by keybindings.

		A quick fix should be marked preferred if it properly addresses the underlying error.
		A refactoring should be marked preferred if it is the most reasonable choice of actions to take.

		@since 3.15.0
	*/
	IsPreferred *bool `json:"isPreferred,omitempty"`
	/*
		Marks that the code action cannot currently be applied.

		Clients should follow the following guidelines regarding disabled code actions:

		  - Disabled code actions are not shown in automatic [lightbulbs](https://code.visualstudio.com/docs/editor/editingevolved#_code-action)
		    code action menus.

		  - Disabled actions are shown as faded out in the code action menu when the user requests a more specific type
		    of code action, such as refactorings.

		  - If the user has a [keybinding](https://code.visualstudio.com/docs/editor/refactoring#_keybindings-for-code-actions)
		    that auto applies a code action and only disabled code actions are returned, the client should show the user an
		    error message with `reason` in the editor.

		@since 3.16.0
	*/
	Disabled *CodeActionDisabled `json:"disabled,omitempty"`
	// The workspace edit this code action performs.
	Edit *WorkspaceEdit `json:"edit,omitempty"`
	/*
		A command this code action executes. If a code action
		provides an edit and a command, first the edit is
		executed and then the command.
	*/
	Command *Command `json:"command,omitempty"`
	/*
		A data entry field that is preserved on a code action between
		a `textDocument/codeAction` and a `codeAction/resolve` request.

		@since 3.16.0
	*/
	Data any `json:"data,omitempty"`
	/*
		Tags for this code action.

		@since 3.18.0
	*/
	Tags []CodeActionTag `json:"tags,omitempty"`
}

// The Client Capabilities of a [CodeActionRequest].
type CodeActionClientCapabilities struct {
	// Whether code action supports dynamic registration.
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
	/*
		The client support code action literals of type `CodeAction` as a valid
		response of the `textDocument/codeAction` request. If the property is not
		set the request can only return `Command` literals.

		@since 3.8.0
	*/
	CodeActionLiteralSupport *ClientCodeActionLiteralOptions `json:"codeActionLiteralSupport,omitempty"`
	/*
		Whether code action supports the `isPreferred` property.

		@since 3.15.0
	*/
	IsPreferredSupport *bool `json:"isPreferredSupport,omitempty"`
	/*
		Whether code action supports the `disabled` property.

		@since 3.16.0
	*/
	DisabledSupport *bool `json:"disabledSupport,omitempty"`
	/*
		Whether code action supports the `data` property which is
		preserved between a `textDocument/codeAction` and a
		`codeAction/resolve` request.

		@since 3.16.0
	*/
	DataSupport *bool `json:"dataSupport,omitempty"`
	/*
		Whether the client supports resolving additional code action
		properties via a separate `codeAction/resolve` request.

		@since 3.16.0
	*/
	ResolveSupport *ClientCodeActionResolveOptions `json:"resolveSupport,omitempty"`
	/*
		Whether the client honors the change annotations in
		text edits and resource operations returned via the
		`CodeAction#edit` property by for example presenting
		the workspace edit in the user interface and asking
		for confirmation.

		@since 3.16.0
	*/
	HonorsChangeAnnotations *bool `json:"honorsChangeAnnotations,omitempty"`
	/*
		Whether the client supports documentation for a class of
		code actions.

		@since 3.18.0
	*/
	DocumentationSupport *bool `json:"documentationSupport,omitempty"`
	/*
		Client supports the tag property on a code action. Clients
		supporting tags have to handle unknown tags gracefully.

		@since 3.18.0
	*/
	TagSupport *CodeActionTagOptions `json:"tagSupport,omitempty"`
}

// A set of predefined code action kinds
type CodeActionKind string

const (
	// Empty kind.
	CodeActionEmpty CodeActionKind = ""
	// Base kind for quickfix actions: 'quickfix'
	CodeActionQuickFix CodeActionKind = "quickfix"
	// Base kind for refactoring actions: 'refactor'
	CodeActionRefactor CodeActionKind = "refactor"
	/*
		Base kind for refactoring extraction actions: 'refactor.extract'

		Example extract actions:


		- Extract method
			- Extract function
			- Extract variable
			- Extract interface from class
			- ...
	*/
	CodeActionRefactorExtract CodeActionKind = "refactor.extract"
	/*
		Base kind for refactoring inline actions: 'refactor.inline'

		Example inline actions:


		- Inline function
			- Inline variable
			- Inline constant
			- ...
	*/
	CodeActionRefactorInline CodeActionKind = "refactor.inline"
	/*
		Base kind for refactoring move actions: `refactor.move`

		Example move actions:


		- Move a function to a new file
			- Move a property between classes
			- Move method to base class
			- ...

		@since 3.18.0
	*/
	CodeActionRefactorMove CodeActionKind = "refactor.move"
	/*
		Base kind for refactoring rewrite actions: 'refactor.rewrite'

		Example rewrite actions:


		- Convert JavaScript function to class
			- Add or remove parameter
			- Encapsulate field
			- Make method static
			- Move method to base class
			- ...
	*/
	CodeActionRefactorRewrite CodeActionKind = "refactor.rewrite"
	/*
		Base kind for source actions: `source`

		Source code actions apply to the entire file.
	*/
	CodeActionSource CodeActionKind = "source"
	// Base kind for an organize imports source action: `source.organizeImports`
	CodeActionSourceOrganizeImports CodeActionKind = "source.organizeImports"
	/*
		Base kind for auto-fix source actions: `source.fixAll`.

		Fix all actions automatically fix errors that have a clear fix that do not require user input.
		They should not suppress errors or perform unsafe fixes such as generating new types or classes.

		@since 3.15.0
	*/
	CodeActionSourceFixAll CodeActionKind = "source.fixAll"
	/*
		Base kind for all code actions applying to the entire notebook's scope. CodeActionKinds using
		this should always begin with `notebook.`

		@since 3.18.0
	*/
	CodeActionNotebook CodeActionKind = "notebook"
)
