// Code generated by lsp/generate; DO NOT EDIT.
package lsp

/*
A code lens represents a  command [Command] that should be shown along with
source text, like the number of references, a way to run tests, etc.

A code lens is _unresolved_ when no command is associated to it. For performance
reasons the creation of a code lens and resolving should be done in two stages.
*/
type CodeLens struct {
	/*
		A code lens represents a  command [Command] that should be shown along with
		source text, like the number of references, a way to run tests, etc.

		A code lens is _unresolved_ when no command is associated to it. For performance
		reasons the creation of a code lens and resolving should be done in two stages.
	*/
	Range Range `json:"range"`
	/*
		A code lens represents a  command [Command] that should be shown along with
		source text, like the number of references, a way to run tests, etc.

		A code lens is _unresolved_ when no command is associated to it. For performance
		reasons the creation of a code lens and resolving should be done in two stages.
	*/
	Command *Command `json:"command,omitempty"`
	/*
		A code lens represents a  command [Command] that should be shown along with
		source text, like the number of references, a way to run tests, etc.

		A code lens is _unresolved_ when no command is associated to it. For performance
		reasons the creation of a code lens and resolving should be done in two stages.
	*/
	Data any `json:"data,omitempty"`
}

// The client capabilities  of a [CodeLensRequest].
type CodeLensClientCapabilities struct {
	// The client capabilities  of a [CodeLensRequest].
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
	// The client capabilities  of a [CodeLensRequest].
	ResolveSupport *ClientCodeLensResolveOptions `json:"resolveSupport,omitempty"`
}
