// Code generated by lsp/generate; DO NOT EDIT.
package lsp

import "github.com/ProCode-Software/klar/pkg/lsp/rpc"

/*
A completion item represents a text snippet that is
proposed to complete text that is being typed.
*/
type CompletionItem struct {
	/*
		A completion item represents a text snippet that is
		proposed to complete text that is being typed.
	*/
	Label string `json:"label"`
	/*
		A completion item represents a text snippet that is
		proposed to complete text that is being typed.
	*/
	LabelDetails *CompletionItemLabelDetails `json:"labelDetails,omitempty"`
	/*
		A completion item represents a text snippet that is
		proposed to complete text that is being typed.
	*/
	Kind *CompletionItemKind `json:"kind,omitempty"`
	/*
		A completion item represents a text snippet that is
		proposed to complete text that is being typed.
	*/
	Tags []CompletionItemTag `json:"tags,omitempty"`
	/*
		A completion item represents a text snippet that is
		proposed to complete text that is being typed.
	*/
	Detail string `json:"detail,omitempty"`
	/*
		A completion item represents a text snippet that is
		proposed to complete text that is being typed.
	*/
	Documentation *rpc.Union2[string, MarkupContent] `json:"documentation,omitempty"`
	/*
		A completion item represents a text snippet that is
		proposed to complete text that is being typed.
	*/
	Deprecated *bool `json:"deprecated,omitempty"`
	/*
		A completion item represents a text snippet that is
		proposed to complete text that is being typed.
	*/
	Preselect *bool `json:"preselect,omitempty"`
	/*
		A completion item represents a text snippet that is
		proposed to complete text that is being typed.
	*/
	SortText string `json:"sortText,omitempty"`
	/*
		A completion item represents a text snippet that is
		proposed to complete text that is being typed.
	*/
	FilterText string `json:"filterText,omitempty"`
	/*
		A completion item represents a text snippet that is
		proposed to complete text that is being typed.
	*/
	InsertText string `json:"insertText,omitempty"`
	/*
		A completion item represents a text snippet that is
		proposed to complete text that is being typed.
	*/
	InsertTextFormat *InsertTextFormat `json:"insertTextFormat,omitempty"`
	/*
		A completion item represents a text snippet that is
		proposed to complete text that is being typed.
	*/
	InsertTextMode *InsertTextMode `json:"insertTextMode,omitempty"`
	/*
		A completion item represents a text snippet that is
		proposed to complete text that is being typed.
	*/
	TextEdit *rpc.Union2[TextEdit, InsertReplaceEdit] `json:"textEdit,omitempty"`
	/*
		A completion item represents a text snippet that is
		proposed to complete text that is being typed.
	*/
	TextEditText string `json:"textEditText,omitempty"`
	/*
		A completion item represents a text snippet that is
		proposed to complete text that is being typed.
	*/
	AdditionalTextEdits []TextEdit `json:"additionalTextEdits,omitempty"`
	/*
		A completion item represents a text snippet that is
		proposed to complete text that is being typed.
	*/
	CommitCharacters []string `json:"commitCharacters,omitempty"`
	/*
		A completion item represents a text snippet that is
		proposed to complete text that is being typed.
	*/
	Command *Command `json:"command,omitempty"`
	/*
		A completion item represents a text snippet that is
		proposed to complete text that is being typed.
	*/
	Data any `json:"data,omitempty"`
}

/*
Specifies how fields from a completion item should be combined with those
from `completionList.itemDefaults`.

If unspecified, all fields will be treated as ApplyKind.Replace.

If a field's value is ApplyKind.Replace, the value from a completion item (if
provided and not `null`) will always be used instead of the value from
`completionItem.itemDefaults`.

If a field's value is ApplyKind.Merge, the values will be merged using the rules
defined against each field below.

Servers are only allowed to return `applyKind` if the client
signals support for this via the `completionList.applyKindSupport`
capability.

@since 3.18.0
*/
type CompletionItemApplyKinds struct {
	/*
		Specifies how fields from a completion item should be combined with those
		from `completionList.itemDefaults`.

		If unspecified, all fields will be treated as ApplyKind.Replace.

		If a field's value is ApplyKind.Replace, the value from a completion item (if
		provided and not `null`) will always be used instead of the value from
		`completionItem.itemDefaults`.

		If a field's value is ApplyKind.Merge, the values will be merged using the rules
		defined against each field below.

		Servers are only allowed to return `applyKind` if the client
		signals support for this via the `completionList.applyKindSupport`
		capability.

		@since 3.18.0
	*/
	CommitCharacters *ApplyKind `json:"commitCharacters,omitempty"`
	/*
		Specifies how fields from a completion item should be combined with those
		from `completionList.itemDefaults`.

		If unspecified, all fields will be treated as ApplyKind.Replace.

		If a field's value is ApplyKind.Replace, the value from a completion item (if
		provided and not `null`) will always be used instead of the value from
		`completionItem.itemDefaults`.

		If a field's value is ApplyKind.Merge, the values will be merged using the rules
		defined against each field below.

		Servers are only allowed to return `applyKind` if the client
		signals support for this via the `completionList.applyKindSupport`
		capability.

		@since 3.18.0
	*/
	Data *ApplyKind `json:"data,omitempty"`
}

// The kind of a completion entry.
type CompletionItemKind uint32

const (
	CompletionItemText          CompletionItemKind = 1
	CompletionItemMethod        CompletionItemKind = 2
	CompletionItemFunction      CompletionItemKind = 3
	CompletionItemConstructor   CompletionItemKind = 4
	CompletionItemField         CompletionItemKind = 5
	CompletionItemVariable      CompletionItemKind = 6
	CompletionItemClass         CompletionItemKind = 7
	CompletionItemInterface     CompletionItemKind = 8
	CompletionItemModule        CompletionItemKind = 9
	CompletionItemProperty      CompletionItemKind = 10
	CompletionItemUnit          CompletionItemKind = 11
	CompletionItemValue         CompletionItemKind = 12
	CompletionItemEnum          CompletionItemKind = 13
	CompletionItemKeyword       CompletionItemKind = 14
	CompletionItemSnippet       CompletionItemKind = 15
	CompletionItemColor         CompletionItemKind = 16
	CompletionItemFile          CompletionItemKind = 17
	CompletionItemReference     CompletionItemKind = 18
	CompletionItemFolder        CompletionItemKind = 19
	CompletionItemEnumMember    CompletionItemKind = 20
	CompletionItemConstant      CompletionItemKind = 21
	CompletionItemStruct        CompletionItemKind = 22
	CompletionItemEvent         CompletionItemKind = 23
	CompletionItemOperator      CompletionItemKind = 24
	CompletionItemTypeParameter CompletionItemKind = 25
)

/*
Completion item tags are extra annotations that tweak the rendering of a completion
item.

@since 3.15.0
*/
type CompletionItemTag uint32

const (
	// Render a completion as obsolete, usually using a strike-out.
	CompletionItemTagDeprecated CompletionItemTag = 1
)
