// Code generated by lsp/generate; DO NOT EDIT.
package lsp

/*
A document link is a range in a text document that links to an internal or external resource, like another
text document or a web site.
*/
type DocumentLink struct {
	// The range this link applies to.
	Range Range `json:"range"`
	// The uri this link points to. If missing a resolve request is sent later.
	Target *URI `json:"target,omitempty"`
	/*
		The tooltip text when you hover over this link.

		If a tooltip is provided, is will be displayed in a string that includes instructions on how to
		trigger the link, such as `{0} (ctrl + click)`. The specific instructions vary depending on OS,
		user settings, and localization.

		@since 3.15.0
	*/
	Tooltip string `json:"tooltip,omitempty"`
	/*
		A data entry field that is preserved on a document link between a
		DocumentLinkRequest and a DocumentLinkResolveRequest.
	*/
	Data any `json:"data,omitempty"`
}

// The client capabilities of a [DocumentLinkRequest].
type DocumentLinkClientCapabilities struct {
	// Whether document link supports dynamic registration.
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
	/*
		Whether the client supports the `tooltip` property on `DocumentLink`.

		@since 3.15.0
	*/
	TooltipSupport *bool `json:"tooltipSupport,omitempty"`
}
