// Code generated by lsp/generate; DO NOT EDIT.
package lsp

/*
A document link is a range in a text document that links to an internal or external resource, like another
text document or a web site.
*/
type DocumentLink struct {
	/*
		A document link is a range in a text document that links to an internal or external resource, like another
		text document or a web site.
	*/
	Range Range `json:"range"`
	/*
		A document link is a range in a text document that links to an internal or external resource, like another
		text document or a web site.
	*/
	Target *URI `json:"target,omitempty"`
	/*
		A document link is a range in a text document that links to an internal or external resource, like another
		text document or a web site.
	*/
	Tooltip string `json:"tooltip,omitempty"`
	/*
		A document link is a range in a text document that links to an internal or external resource, like another
		text document or a web site.
	*/
	Data any `json:"data,omitempty"`
}

// The client capabilities of a [DocumentLinkRequest].
type DocumentLinkClientCapabilities struct {
	// The client capabilities of a [DocumentLinkRequest].
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
	// The client capabilities of a [DocumentLinkRequest].
	TooltipSupport *bool `json:"tooltipSupport,omitempty"`
}
