// Code generated by lsp/generate; DO NOT EDIT.
package lsp

import "github.com/ProCode-Software/klar/pkg/lsp/rpc"

type CancelParams struct {
	Id rpc.Union2[int, string] `json:"id"`
}

/*
Additional information that describes document changes.

@since 3.16.0
*/
type ChangeAnnotation struct {
	/*
		Additional information that describes document changes.

		@since 3.16.0
	*/
	Label string `json:"label"`
	/*
		Additional information that describes document changes.

		@since 3.16.0
	*/
	NeedsConfirmation *bool `json:"needsConfirmation,omitempty"`
	/*
		Additional information that describes document changes.

		@since 3.16.0
	*/
	Description string `json:"description,omitempty"`
}

type LogTraceParams struct {
	Message string `json:"message"`
	Verbose string `json:"verbose,omitempty"`
}

/*
Client capabilities specific to the used markdown parser.

@since 3.16.0
*/
type MarkdownClientCapabilities struct {
	/*
		Client capabilities specific to the used markdown parser.

		@since 3.16.0
	*/
	Parser string `json:"parser"`
	/*
		Client capabilities specific to the used markdown parser.

		@since 3.16.0
	*/
	Version string `json:"version,omitempty"`
	/*
		Client capabilities specific to the used markdown parser.

		@since 3.16.0
	*/
	AllowedTags []string `json:"allowedTags,omitempty"`
}

type ProgressParams struct {
	Token ProgressToken `json:"token"`
	Value any           `json:"value"`
}

// The publish diagnostic client capabilities.
type PublishDiagnosticsClientCapabilities struct {
	DiagnosticsCapabilities
	// The publish diagnostic client capabilities.
	VersionSupport *bool `json:"versionSupport,omitempty"`
}

type SetTraceParams struct {
	Value TraceValue `json:"value"`
}

/*
Client capabilities for the showDocument request.

@since 3.16.0
*/
type ShowDocumentClientCapabilities struct {
	/*
		Client capabilities for the showDocument request.

		@since 3.16.0
	*/
	Support bool `json:"support"`
}

// An identifier to refer to a change annotation stored with a workspace edit.
type ChangeAnnotationIdentifier = string

/*
MarkedString can be used to render human readable text. It is either a markdown string
or a code-block that provides a language and a code snippet. The language identifier
is semantically equal to the optional language identifier in fenced code blocks in GitHub
issues. See https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting

The pair of a language and a value is an equivalent to markdown:
```${language}
${value}
```

Note that markdown strings will be sanitized - that means html will be escaped.
@deprecated use MarkupContent instead.

* Deprecated: use MarkupContent instead.
*/
type MarkedString = rpc.Union2[string, MarkedStringWithLanguage]

/*
Describes the content type that a client supports in various
result literals like `Hover`, `ParameterInfo` or `CompletionItem`.

Please note that `MarkupKinds` must not start with a `$`. This kinds
are reserved for internal usage.
*/
type MarkupKind string

const (
	// Plain text is supported as a content format
	MarkupPlainText MarkupKind = "plaintext"
	// Markdown is supported as a content format
	MarkupMarkdown MarkupKind = "markdown"
)

// The message type
type MessageType uint32

const (
	// An error message.
	MessageTypeError MessageType = 1
	// A warning message.
	MessageTypeWarning MessageType = 2
	// An information message.
	MessageTypeInfo MessageType = 3
	// A log message.
	MessageTypeLog MessageType = 4
	/*
		A debug message.

		@since 3.18.0
	*/
	MessageTypeDebug MessageType = 5
)

/*
The moniker kind.

@since 3.16.0
*/
type MonikerKind string

const (
	// The moniker represent a symbol that is imported into a project
	MonikerImport MonikerKind = "import"
	// The moniker represents a symbol that is exported from a project
	MonikerExport MonikerKind = "export"
	/*
		The moniker represents a symbol that is local to a project (e.g. a local
		variable of a function, a class not visible outside the project, ...)
	*/
	MonikerLocal MonikerKind = "local"
)

type ProgressToken = rpc.Union2[int, string]
