// Code generated by lsp/generate; DO NOT EDIT.
package lsp

import "github.com/ProCode-Software/klar/pkg/lsp/rpc"

/*
Inlay hint information.

@since 3.17.0
*/
type InlayHint struct {
	/*
		Inlay hint information.

		@since 3.17.0
	*/
	Position Position `json:"position"`
	/*
		Inlay hint information.

		@since 3.17.0
	*/
	Label rpc.Union2[string, []InlayHintLabelPart] `json:"label"`
	/*
		Inlay hint information.

		@since 3.17.0
	*/
	Kind *InlayHintKind `json:"kind,omitempty"`
	/*
		Inlay hint information.

		@since 3.17.0
	*/
	TextEdits []TextEdit `json:"textEdits,omitempty"`
	/*
		Inlay hint information.

		@since 3.17.0
	*/
	Tooltip *rpc.Union2[string, MarkupContent] `json:"tooltip,omitempty"`
	/*
		Inlay hint information.

		@since 3.17.0
	*/
	PaddingLeft *bool `json:"paddingLeft,omitempty"`
	/*
		Inlay hint information.

		@since 3.17.0
	*/
	PaddingRight *bool `json:"paddingRight,omitempty"`
	/*
		Inlay hint information.

		@since 3.17.0
	*/
	Data any `json:"data,omitempty"`
}

/*
Inlay hint client capabilities.

@since 3.17.0
*/
type InlayHintClientCapabilities struct {
	/*
		Inlay hint client capabilities.

		@since 3.17.0
	*/
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
	/*
		Inlay hint client capabilities.

		@since 3.17.0
	*/
	ResolveSupport *ClientInlayHintResolveOptions `json:"resolveSupport,omitempty"`
}

/*
Inlay hint kinds.

@since 3.17.0
*/
type InlayHintKind uint32

const (
	// An inlay hint that for a type annotation.
	InlayHintType InlayHintKind = 1
	// An inlay hint that is for a parameter.
	InlayHintParameter InlayHintKind = 2
)
