// Code generated by lsp/generate; DO NOT EDIT.
package lsp

/*
The data type of the ResponseError if the
initialize request fails.
*/
type InitializeError struct {
	/*
		The data type of the ResponseError if the
		initialize request fails.
	*/
	Retry bool `json:"retry"`
}

type InitializeParams struct {
	_InitializeParams
	WorkspaceFoldersInitializeParams
}

// The result returned from an initialize request.
type InitializeResult struct {
	// The result returned from an initialize request.
	Capabilities *ServerCapabilities `json:"capabilities"`
	// The result returned from an initialize request.
	ServerInfo *ServerInfo `json:"serverInfo,omitempty"`
}

type InitializedParams struct {
}
