// Code generated by lsp/generate; DO NOT EDIT.
package lsp

/*
The params sent in a change notebook document notification.

@since 3.17.0
*/
type DidChangeNotebookDocumentParams struct {
	/*
		The params sent in a change notebook document notification.

		@since 3.17.0
	*/
	NotebookDocument VersionedNotebookDocumentIdentifier `json:"notebookDocument"`
	/*
		The params sent in a change notebook document notification.

		@since 3.17.0
	*/
	Change NotebookDocumentChangeEvent `json:"change"`
}

/*
The params sent in a close notebook document notification.

@since 3.17.0
*/
type DidCloseNotebookDocumentParams struct {
	/*
		The params sent in a close notebook document notification.

		@since 3.17.0
	*/
	NotebookDocument NotebookDocumentIdentifier `json:"notebookDocument"`
	/*
		The params sent in a close notebook document notification.

		@since 3.17.0
	*/
	CellTextDocuments []TextDocumentIdentifier `json:"cellTextDocuments"`
}

/*
The params sent in an open notebook document notification.

@since 3.17.0
*/
type DidOpenNotebookDocumentParams struct {
	/*
		The params sent in an open notebook document notification.

		@since 3.17.0
	*/
	NotebookDocument NotebookDocument `json:"notebookDocument"`
	/*
		The params sent in an open notebook document notification.

		@since 3.17.0
	*/
	CellTextDocuments []TextDocumentItem `json:"cellTextDocuments"`
}

/*
The params sent in a save notebook document notification.

@since 3.17.0
*/
type DidSaveNotebookDocumentParams struct {
	/*
		The params sent in a save notebook document notification.

		@since 3.17.0
	*/
	NotebookDocument NotebookDocumentIdentifier `json:"notebookDocument"`
}

/*
Registration options specific to a notebook.

@since 3.17.0
*/
type NotebookDocumentSyncRegistrationOptions struct {
	NotebookDocumentSyncOptions
	StaticRegistrationOptions
}

// A text document identifier to optionally denote a specific version of a text document.
type OptionalVersionedTextDocumentIdentifier struct {
	TextDocumentIdentifier
	// A text document identifier to optionally denote a specific version of a text document.
	Version int `json:"version,omitempty"` // integer | null
}

/*
The glob pattern to watch relative to the base path. Glob patterns can have the following syntax:

  - `*` to match zero or more characters in a path segment
  - `?` to match on one character in a path segment
  - `**` to match any number of path segments, including none
  - `{}` to group conditions (e.g. `**​/*.{ts,js}` matches all TypeScript and JavaScript files)
  - `[]` to declare a range of characters to match in a path segment (e.g., `example.[0-9]` to match on `example.0`, `example.1`, …)
  - `[!...]` to negate a range of characters to match in a path segment (e.g., `example.[!0-9]` to match on `example.a`, `example.b`, but not `example.0`)

@since 3.17.0
*/
type Pattern = string

/*
A set of predefined position encoding kinds.

@since 3.17.0
*/
type PositionEncodingKind string

const (
	// Character offsets count UTF-8 code units (e.g. bytes).
	PositionEncodingUTF8 PositionEncodingKind = "utf-8"
	/*
		Character offsets count UTF-16 code units.

		This is the default and must always be supported
		by servers
	*/
	PositionEncodingUTF16 PositionEncodingKind = "utf-16"
	/*
		Character offsets count UTF-32 code units.

		Implementation note: these are the same as Unicode codepoints,
		so this `PositionEncodingKind` may also be used for an
		encoding-agnostic representation of character offsets.
	*/
	PositionEncodingUTF32 PositionEncodingKind = "utf-32"
)
