// Code generated by lsp/generate; DO NOT EDIT.
package lsp

// @since 3.16.0
type SemanticTokensDeltaParams struct {
	WorkDoneProgressParams
	PartialResultParams
	// The text document.
	TextDocument TextDocumentIdentifier `json:"textDocument"`
	/*
		The result id of a previous response. The result Id can either point to a full response
		or a delta response depending on what was received last.
	*/
	PreviousResultId string `json:"previousResultId"`
}

// @since 3.16.0
type SemanticTokensDeltaPartialResult struct {
	Edits []SemanticTokensEdit `json:"edits"`
}

// @since 3.16.0
type SemanticTokensParams struct {
	WorkDoneProgressParams
	PartialResultParams
	// The text document.
	TextDocument TextDocumentIdentifier `json:"textDocument"`
}

// @since 3.16.0
type SemanticTokensPartialResult struct {
	Data []uint32 `json:"data"`
}

// @since 3.16.0
type SemanticTokensRangeParams struct {
	WorkDoneProgressParams
	PartialResultParams
	// The text document.
	TextDocument TextDocumentIdentifier `json:"textDocument"`
	// The range the semantic tokens are requested for.
	Range Range `json:"range"`
}

// @since 3.16.0
type SemanticTokensRegistrationOptions struct {
	TextDocumentRegistrationOptions
	SemanticTokensOptions
	StaticRegistrationOptions
}

// @since 3.16.0
type SemanticTokensWorkspaceClientCapabilities struct {
	/*
		Whether the client implementation supports a refresh request sent from
		the server to the client.

		Note that this event is global and will force the client to refresh all
		semantic tokens currently shown. It should be used with absolute care
		and is useful for situation where a server for example detects a project
		wide change that requires such a calculation.
	*/
	RefreshSupport *bool `json:"refreshSupport,omitempty"`
}
