// Code generated by lsp/generate; DO NOT EDIT.
package lsp

// @since 3.16.0
type SemanticTokensDeltaParams struct {
	WorkDoneProgressParams
	PartialResultParams
	// @since 3.16.0
	TextDocument TextDocumentIdentifier `json:"textDocument"`
	// @since 3.16.0
	PreviousResultId string `json:"previousResultId"`
}

// @since 3.16.0
type SemanticTokensDeltaPartialResult struct {
	// @since 3.16.0
	Edits []SemanticTokensEdit `json:"edits"`
}

// @since 3.16.0
type SemanticTokensParams struct {
	WorkDoneProgressParams
	PartialResultParams
	// @since 3.16.0
	TextDocument TextDocumentIdentifier `json:"textDocument"`
}

// @since 3.16.0
type SemanticTokensPartialResult struct {
	// @since 3.16.0
	Data []uint32 `json:"data"`
}

// @since 3.16.0
type SemanticTokensRangeParams struct {
	WorkDoneProgressParams
	PartialResultParams
	// @since 3.16.0
	TextDocument TextDocumentIdentifier `json:"textDocument"`
	// @since 3.16.0
	Range Range `json:"range"`
}

// @since 3.16.0
type SemanticTokensRegistrationOptions struct {
	TextDocumentRegistrationOptions
	SemanticTokensOptions
	StaticRegistrationOptions
}

// @since 3.16.0
type SemanticTokensWorkspaceClientCapabilities struct {
	// @since 3.16.0
	RefreshSupport *bool `json:"refreshSupport,omitempty"`
}
