// Code generated by lsp/generate; DO NOT EDIT.
package lsp

type LSPErrorCodes int

const (
	/*
		A request failed but it was syntactically correct, e.g the
		method name was known and the parameters were valid. The error
		message should contain human readable information about why
		the request failed.

		@since 3.17.0
	*/
	LSPErrorCodesRequestFailed LSPErrorCodes = -32803
	/*
		The server cancelled the request. This error code should
		only be used for requests that explicitly support being
		server cancellable.

		@since 3.17.0
	*/
	LSPErrorCodesServerCancelled LSPErrorCodes = -32802
	/*
		The server detected that the content of a document got
		modified outside normal conditions. A server should
		NOT send this error code if it detects a content change
		in it unprocessed messages. The result even computed
		on an older state might still be useful for the client.

		If a client decides that a result is not of any use anymore
		the client should cancel the request.
	*/
	LSPErrorCodesContentModified LSPErrorCodes = -32801
	/*
		The client has canceled a request and a server has detected
		the cancel.
	*/
	LSPErrorCodesRequestCancelled LSPErrorCodes = -32800
)

/*
Predefined Language kinds
@since 3.18.0
*/
type LanguageKind string

const (
	LanguageABAP         LanguageKind = "abap"
	LanguageWindowsBat   LanguageKind = "bat"
	LanguageBibTeX       LanguageKind = "bibtex"
	LanguageClojure      LanguageKind = "clojure"
	LanguageCoffeescript LanguageKind = "coffeescript"
	LanguageC            LanguageKind = "c"
	LanguageCPP          LanguageKind = "cpp"
	LanguageCSharp       LanguageKind = "csharp"
	LanguageCSS          LanguageKind = "css"
	// @since 3.18.0
	LanguageD LanguageKind = "d"
	// @since 3.18.0
	LanguageDelphi          LanguageKind = "pascal"
	LanguageDiff            LanguageKind = "diff"
	LanguageDart            LanguageKind = "dart"
	LanguageDockerfile      LanguageKind = "dockerfile"
	LanguageElixir          LanguageKind = "elixir"
	LanguageErlang          LanguageKind = "erlang"
	LanguageFSharp          LanguageKind = "fsharp"
	LanguageGitCommit       LanguageKind = "git-commit"
	LanguageGitRebase       LanguageKind = "git-rebase"
	LanguageGo              LanguageKind = "go"
	LanguageGroovy          LanguageKind = "groovy"
	LanguageHandlebars      LanguageKind = "handlebars"
	LanguageHaskell         LanguageKind = "haskell"
	LanguageHTML            LanguageKind = "html"
	LanguageIni             LanguageKind = "ini"
	LanguageJava            LanguageKind = "java"
	LanguageJavaScript      LanguageKind = "javascript"
	LanguageJavaScriptReact LanguageKind = "javascriptreact"
	LanguageJSON            LanguageKind = "json"
	LanguageLaTeX           LanguageKind = "latex"
	LanguageLess            LanguageKind = "less"
	LanguageLua             LanguageKind = "lua"
	LanguageMakefile        LanguageKind = "makefile"
	LanguageMarkdown        LanguageKind = "markdown"
	LanguageObjectiveC      LanguageKind = "objective-c"
	LanguageObjectiveCPP    LanguageKind = "objective-cpp"
	// @since 3.18.0
	LanguagePascal          LanguageKind = "pascal"
	LanguagePerl            LanguageKind = "perl"
	LanguagePerl6           LanguageKind = "perl6"
	LanguagePHP             LanguageKind = "php"
	LanguagePlaintext       LanguageKind = "plaintext"
	LanguagePowershell      LanguageKind = "powershell"
	LanguagePug             LanguageKind = "jade"
	LanguagePython          LanguageKind = "python"
	LanguageR               LanguageKind = "r"
	LanguageRazor           LanguageKind = "razor"
	LanguageRuby            LanguageKind = "ruby"
	LanguageRust            LanguageKind = "rust"
	LanguageSCSS            LanguageKind = "scss"
	LanguageSASS            LanguageKind = "sass"
	LanguageScala           LanguageKind = "scala"
	LanguageShaderLab       LanguageKind = "shaderlab"
	LanguageShellScript     LanguageKind = "shellscript"
	LanguageSQL             LanguageKind = "sql"
	LanguageSwift           LanguageKind = "swift"
	LanguageTypeScript      LanguageKind = "typescript"
	LanguageTypeScriptReact LanguageKind = "typescriptreact"
	LanguageTeX             LanguageKind = "tex"
	LanguageVisualBasic     LanguageKind = "vb"
	LanguageXML             LanguageKind = "xml"
	LanguageXSL             LanguageKind = "xsl"
	LanguageYAML            LanguageKind = "yaml"
)
