// Code generated by lsp/generate; DO NOT EDIT.
package lsp

/*
Parameters for the `workspace/textDocumentContent/refresh` request.

@since 3.18.0
*/
type TextDocumentContentRefreshParams struct {
	// The uri of the text document to refresh.
	Uri DocumentURI `json:"uri"`
}
