// Code generated by lsp/generate; DO NOT EDIT.
package lsp

/*
Parameters for the `workspace/textDocumentContent/refresh` request.

@since 3.18.0
*/
type TextDocumentContentRefreshParams struct {
	/*
		Parameters for the `workspace/textDocumentContent/refresh` request.

		@since 3.18.0
	*/
	Uri DocumentURI `json:"uri"`
}
