// Code generated by lsp/generate; DO NOT EDIT.
package lsp

import "github.com/ProCode-Software/klar/pkg/lsp/rpc"

/*
The parameter of a `textDocument/prepareCallHierarchy` request.

@since 3.16.0
*/
type CallHierarchyPrepareParams struct {
	TextDocumentPositionParams
	WorkDoneProgressParams
}

/*
Call hierarchy options used during static or dynamic registration.

@since 3.16.0
*/
type CallHierarchyRegistrationOptions struct {
	TextDocumentRegistrationOptions
	CallHierarchyOptions
	StaticRegistrationOptions
}

// The parameters of a [CodeActionRequest].
type CodeActionParams struct {
	WorkDoneProgressParams
	PartialResultParams
	// The parameters of a [CodeActionRequest].
	TextDocument TextDocumentIdentifier `json:"textDocument"`
	// The parameters of a [CodeActionRequest].
	Range Range `json:"range"`
	// The parameters of a [CodeActionRequest].
	Context CodeActionContext `json:"context"`
}

// Registration options for a [CodeActionRequest].
type CodeActionRegistrationOptions struct {
	TextDocumentRegistrationOptions
	CodeActionOptions
}

// @since 3.18.0
type CodeActionTagOptions struct {
	// @since 3.18.0
	ValueSet []CodeActionTag `json:"valueSet"`
}

// The parameters of a [CodeLensRequest].
type CodeLensParams struct {
	WorkDoneProgressParams
	PartialResultParams
	// The parameters of a [CodeLensRequest].
	TextDocument TextDocumentIdentifier `json:"textDocument"`
}

// Registration options for a [CodeLensRequest].
type CodeLensRegistrationOptions struct {
	TextDocumentRegistrationOptions
	CodeLensOptions
}

// @since 3.16.0
type CodeLensWorkspaceClientCapabilities struct {
	// @since 3.16.0
	RefreshSupport *bool `json:"refreshSupport,omitempty"`
}

// Parameters for a [ColorPresentationRequest].
type ColorPresentationParams struct {
	WorkDoneProgressParams
	PartialResultParams
	// Parameters for a [ColorPresentationRequest].
	TextDocument TextDocumentIdentifier `json:"textDocument"`
	// Parameters for a [ColorPresentationRequest].
	Color Color `json:"color"`
	// Parameters for a [ColorPresentationRequest].
	Range Range `json:"range"`
}

/*
Represents a reference to a command. Provides a title which
will be used to represent a command in the UI and, optionally,
an array of arguments which will be passed to the command handler
function when invoked.
*/
type Command struct {
	/*
		Represents a reference to a command. Provides a title which
		will be used to represent a command in the UI and, optionally,
		an array of arguments which will be passed to the command handler
		function when invoked.
	*/
	Title string `json:"title"`
	/*
		Represents a reference to a command. Provides a title which
		will be used to represent a command in the UI and, optionally,
		an array of arguments which will be passed to the command handler
		function when invoked.
	*/
	Tooltip string `json:"tooltip,omitempty"`
	/*
		Represents a reference to a command. Provides a title which
		will be used to represent a command in the UI and, optionally,
		an array of arguments which will be passed to the command handler
		function when invoked.
	*/
	Command string `json:"command"`
	/*
		Represents a reference to a command. Provides a title which
		will be used to represent a command in the UI and, optionally,
		an array of arguments which will be passed to the command handler
		function when invoked.
	*/
	Arguments []any `json:"arguments,omitempty"`
}

// Completion parameters
type CompletionParams struct {
	TextDocumentPositionParams
	WorkDoneProgressParams
	PartialResultParams
	// Completion parameters
	Context *CompletionContext `json:"context,omitempty"`
}

// Registration options for a [CompletionRequest].
type CompletionRegistrationOptions struct {
	TextDocumentRegistrationOptions
	CompletionOptions
}

type ConfigurationItem struct {
	ScopeUri *URI   `json:"scopeUri,omitempty"`
	Section  string `json:"section,omitempty"`
}

type DeclarationParams struct {
	TextDocumentPositionParams
	WorkDoneProgressParams
	PartialResultParams
}

type DeclarationRegistrationOptions struct {
	DeclarationOptions
	TextDocumentRegistrationOptions
	StaticRegistrationOptions
}

// Client Capabilities for a [DefinitionRequest].
type DefinitionClientCapabilities struct {
	// Client Capabilities for a [DefinitionRequest].
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
	// Client Capabilities for a [DefinitionRequest].
	LinkSupport *bool `json:"linkSupport,omitempty"`
}

// Parameters for a [DefinitionRequest].
type DefinitionParams struct {
	TextDocumentPositionParams
	WorkDoneProgressParams
	PartialResultParams
}

// Registration options for a [DefinitionRequest].
type DefinitionRegistrationOptions struct {
	TextDocumentRegistrationOptions
	DefinitionOptions
}

// Delete file operation
type DeleteFile struct {
	ResourceOperation
	// Delete file operation
	Kind string `json:"kind"` // delete
	// Delete file operation
	Uri DocumentURI `json:"uri"`
	// Delete file operation
	Options *DeleteFileOptions `json:"options,omitempty"`
}

/*
Diagnostic registration options.

@since 3.17.0
*/
type DiagnosticRegistrationOptions struct {
	TextDocumentRegistrationOptions
	DiagnosticOptions
	StaticRegistrationOptions
}

/*
Represents a related message and source code location for a diagnostic. This should be
used to point to code locations that cause or related to a diagnostics, e.g when duplicating
a symbol in a scope.
*/
type DiagnosticRelatedInformation struct {
	/*
		Represents a related message and source code location for a diagnostic. This should be
		used to point to code locations that cause or related to a diagnostics, e.g when duplicating
		a symbol in a scope.
	*/
	Location Location `json:"location"`
	/*
		Represents a related message and source code location for a diagnostic. This should be
		used to point to code locations that cause or related to a diagnostics, e.g when duplicating
		a symbol in a scope.
	*/
	Message string `json:"message"`
}

/*
Cancellation data returned from a diagnostic request.

@since 3.17.0
*/
type DiagnosticServerCancellationData struct {
	/*
		Cancellation data returned from a diagnostic request.

		@since 3.17.0
	*/
	RetriggerRequest bool `json:"retriggerRequest"`
}

/*
Workspace client capabilities specific to diagnostic pull requests.

@since 3.17.0
*/
type DiagnosticWorkspaceClientCapabilities struct {
	/*
		Workspace client capabilities specific to diagnostic pull requests.

		@since 3.17.0
	*/
	RefreshSupport *bool `json:"refreshSupport,omitempty"`
}

// The change text document notification's parameters.
type DidChangeTextDocumentParams struct {
	// The change text document notification's parameters.
	TextDocument VersionedTextDocumentIdentifier `json:"textDocument"`
	// The change text document notification's parameters.
	ContentChanges []TextDocumentContentChangeEvent `json:"contentChanges"`
}

type DidChangeWatchedFilesClientCapabilities struct {
	DynamicRegistration    *bool `json:"dynamicRegistration,omitempty"`
	RelativePatternSupport *bool `json:"relativePatternSupport,omitempty"`
}

// The parameters sent in a close text document notification
type DidCloseTextDocumentParams struct {
	// The parameters sent in a close text document notification
	TextDocument TextDocumentIdentifier `json:"textDocument"`
}

// The parameters sent in an open text document notification
type DidOpenTextDocumentParams struct {
	// The parameters sent in an open text document notification
	TextDocument TextDocumentItem `json:"textDocument"`
}

// The parameters sent in a save text document notification
type DidSaveTextDocumentParams struct {
	// The parameters sent in a save text document notification
	TextDocument TextDocumentIdentifier `json:"textDocument"`
	// The parameters sent in a save text document notification
	Text string `json:"text,omitempty"`
}

type DocumentColorClientCapabilities struct {
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
}

// Parameters for a [DocumentColorRequest].
type DocumentColorParams struct {
	WorkDoneProgressParams
	PartialResultParams
	// Parameters for a [DocumentColorRequest].
	TextDocument TextDocumentIdentifier `json:"textDocument"`
}

type DocumentColorRegistrationOptions struct {
	TextDocumentRegistrationOptions
	DocumentColorOptions
	StaticRegistrationOptions
}

/*
Parameters of the document diagnostic request.

@since 3.17.0
*/
type DocumentDiagnosticParams struct {
	WorkDoneProgressParams
	PartialResultParams
	/*
		Parameters of the document diagnostic request.

		@since 3.17.0
	*/
	TextDocument TextDocumentIdentifier `json:"textDocument"`
	/*
		Parameters of the document diagnostic request.

		@since 3.17.0
	*/
	Identifier string `json:"identifier,omitempty"`
	/*
		Parameters of the document diagnostic request.

		@since 3.17.0
	*/
	PreviousResultId string `json:"previousResultId,omitempty"`
}

/*
A partial result for a document diagnostic report.

@since 3.17.0
*/
type DocumentDiagnosticReportPartialResult struct {
	/*
		A partial result for a document diagnostic report.

		@since 3.17.0
	*/
	RelatedDocuments map[DocumentURI]struct{} `json:"relatedDocuments"`
}

// The parameters of a [DocumentFormattingRequest].
type DocumentFormattingParams struct {
	WorkDoneProgressParams
	// The parameters of a [DocumentFormattingRequest].
	TextDocument TextDocumentIdentifier `json:"textDocument"`
	// The parameters of a [DocumentFormattingRequest].
	Options FormattingOptions `json:"options"`
}

// Registration options for a [DocumentFormattingRequest].
type DocumentFormattingRegistrationOptions struct {
	TextDocumentRegistrationOptions
	DocumentFormattingOptions
}

/*
A document highlight is a range inside a text document which deserves
special attention. Usually a document highlight is visualized by changing
the background color of its range.
*/
type DocumentHighlight struct {
	/*
		A document highlight is a range inside a text document which deserves
		special attention. Usually a document highlight is visualized by changing
		the background color of its range.
	*/
	Range Range `json:"range"`
	/*
		A document highlight is a range inside a text document which deserves
		special attention. Usually a document highlight is visualized by changing
		the background color of its range.
	*/
	Kind *DocumentHighlightKind `json:"kind,omitempty"`
}

// Parameters for a [DocumentHighlightRequest].
type DocumentHighlightParams struct {
	TextDocumentPositionParams
	WorkDoneProgressParams
	PartialResultParams
}

// Registration options for a [DocumentHighlightRequest].
type DocumentHighlightRegistrationOptions struct {
	TextDocumentRegistrationOptions
	DocumentHighlightOptions
}

// The parameters of a [DocumentLinkRequest].
type DocumentLinkParams struct {
	WorkDoneProgressParams
	PartialResultParams
	// The parameters of a [DocumentLinkRequest].
	TextDocument TextDocumentIdentifier `json:"textDocument"`
}

// Registration options for a [DocumentLinkRequest].
type DocumentLinkRegistrationOptions struct {
	TextDocumentRegistrationOptions
	DocumentLinkOptions
}

// Client capabilities of a [DocumentOnTypeFormattingRequest].
type DocumentOnTypeFormattingClientCapabilities struct {
	// Client capabilities of a [DocumentOnTypeFormattingRequest].
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
}

// The parameters of a [DocumentOnTypeFormattingRequest].
type DocumentOnTypeFormattingParams struct {
	// The parameters of a [DocumentOnTypeFormattingRequest].
	TextDocument TextDocumentIdentifier `json:"textDocument"`
	// The parameters of a [DocumentOnTypeFormattingRequest].
	Position Position `json:"position"`
	// The parameters of a [DocumentOnTypeFormattingRequest].
	Ch string `json:"ch"`
	// The parameters of a [DocumentOnTypeFormattingRequest].
	Options FormattingOptions `json:"options"`
}

// Registration options for a [DocumentOnTypeFormattingRequest].
type DocumentOnTypeFormattingRegistrationOptions struct {
	TextDocumentRegistrationOptions
	DocumentOnTypeFormattingOptions
}

// Client capabilities of a [DocumentRangeFormattingRequest].
type DocumentRangeFormattingClientCapabilities struct {
	// Client capabilities of a [DocumentRangeFormattingRequest].
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
	// Client capabilities of a [DocumentRangeFormattingRequest].
	RangesSupport *bool `json:"rangesSupport,omitempty"`
}

// The parameters of a [DocumentRangeFormattingRequest].
type DocumentRangeFormattingParams struct {
	WorkDoneProgressParams
	// The parameters of a [DocumentRangeFormattingRequest].
	TextDocument TextDocumentIdentifier `json:"textDocument"`
	// The parameters of a [DocumentRangeFormattingRequest].
	Range Range `json:"range"`
	// The parameters of a [DocumentRangeFormattingRequest].
	Options FormattingOptions `json:"options"`
}

// Registration options for a [DocumentRangeFormattingRequest].
type DocumentRangeFormattingRegistrationOptions struct {
	TextDocumentRegistrationOptions
	DocumentRangeFormattingOptions
}

/*
The parameters of a [DocumentRangesFormattingRequest].

@since 3.18.0
*/
type DocumentRangesFormattingParams struct {
	WorkDoneProgressParams
	/*
		The parameters of a [DocumentRangesFormattingRequest].

		@since 3.18.0
	*/
	TextDocument TextDocumentIdentifier `json:"textDocument"`
	/*
		The parameters of a [DocumentRangesFormattingRequest].

		@since 3.18.0
	*/
	Ranges []Range `json:"ranges"`
	/*
		The parameters of a [DocumentRangesFormattingRequest].

		@since 3.18.0
	*/
	Options FormattingOptions `json:"options"`
}

/*
Represents programming constructs like variables, classes, interfaces etc.
that appear in a document. Document symbols can be hierarchical and they
have two ranges: one that encloses its definition and one that points to
its most interesting range, e.g. the range of an identifier.
*/
type DocumentSymbol struct {
	/*
		Represents programming constructs like variables, classes, interfaces etc.
		that appear in a document. Document symbols can be hierarchical and they
		have two ranges: one that encloses its definition and one that points to
		its most interesting range, e.g. the range of an identifier.
	*/
	Name string `json:"name"`
	/*
		Represents programming constructs like variables, classes, interfaces etc.
		that appear in a document. Document symbols can be hierarchical and they
		have two ranges: one that encloses its definition and one that points to
		its most interesting range, e.g. the range of an identifier.
	*/
	Detail string `json:"detail,omitempty"`
	/*
		Represents programming constructs like variables, classes, interfaces etc.
		that appear in a document. Document symbols can be hierarchical and they
		have two ranges: one that encloses its definition and one that points to
		its most interesting range, e.g. the range of an identifier.
	*/
	Kind SymbolKind `json:"kind"`
	/*
		Represents programming constructs like variables, classes, interfaces etc.
		that appear in a document. Document symbols can be hierarchical and they
		have two ranges: one that encloses its definition and one that points to
		its most interesting range, e.g. the range of an identifier.
	*/
	Tags []SymbolTag `json:"tags,omitempty"`
	/*
		Represents programming constructs like variables, classes, interfaces etc.
		that appear in a document. Document symbols can be hierarchical and they
		have two ranges: one that encloses its definition and one that points to
		its most interesting range, e.g. the range of an identifier.
	*/
	Deprecated *bool `json:"deprecated,omitempty"`
	/*
		Represents programming constructs like variables, classes, interfaces etc.
		that appear in a document. Document symbols can be hierarchical and they
		have two ranges: one that encloses its definition and one that points to
		its most interesting range, e.g. the range of an identifier.
	*/
	Range Range `json:"range"`
	/*
		Represents programming constructs like variables, classes, interfaces etc.
		that appear in a document. Document symbols can be hierarchical and they
		have two ranges: one that encloses its definition and one that points to
		its most interesting range, e.g. the range of an identifier.
	*/
	SelectionRange Range `json:"selectionRange"`
	/*
		Represents programming constructs like variables, classes, interfaces etc.
		that appear in a document. Document symbols can be hierarchical and they
		have two ranges: one that encloses its definition and one that points to
		its most interesting range, e.g. the range of an identifier.
	*/
	Children []*DocumentSymbol `json:"children,omitempty"`
}

// Parameters for a [DocumentSymbolRequest].
type DocumentSymbolParams struct {
	WorkDoneProgressParams
	PartialResultParams
	// Parameters for a [DocumentSymbolRequest].
	TextDocument TextDocumentIdentifier `json:"textDocument"`
}

// Registration options for a [DocumentSymbolRequest].
type DocumentSymbolRegistrationOptions struct {
	TextDocumentRegistrationOptions
	DocumentSymbolOptions
}

/*
Edit range variant that includes ranges for insert and replace operations.

@since 3.18.0
*/
type EditRangeWithInsertReplace struct {
	/*
		Edit range variant that includes ranges for insert and replace operations.

		@since 3.18.0
	*/
	Insert Range `json:"insert"`
	/*
		Edit range variant that includes ranges for insert and replace operations.

		@since 3.18.0
	*/
	Replace Range `json:"replace"`
}

// Parameters for a [FoldingRangeRequest].
type FoldingRangeParams struct {
	WorkDoneProgressParams
	PartialResultParams
	// Parameters for a [FoldingRangeRequest].
	TextDocument TextDocumentIdentifier `json:"textDocument"`
}

type FoldingRangeRegistrationOptions struct {
	TextDocumentRegistrationOptions
	FoldingRangeOptions
	StaticRegistrationOptions
}

/*
Client workspace capabilities specific to folding ranges

@since 3.18.0
*/
type FoldingRangeWorkspaceClientCapabilities struct {
	/*
		Client workspace capabilities specific to folding ranges

		@since 3.18.0
	*/
	RefreshSupport *bool `json:"refreshSupport,omitempty"`
}

// Parameters for a [HoverRequest].
type HoverParams struct {
	TextDocumentPositionParams
	WorkDoneProgressParams
}

// Registration options for a [HoverRequest].
type HoverRegistrationOptions struct {
	TextDocumentRegistrationOptions
	HoverOptions
}

// @since 3.6.0
type ImplementationClientCapabilities struct {
	// @since 3.6.0
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
	// @since 3.6.0
	LinkSupport *bool `json:"linkSupport,omitempty"`
}

type ImplementationParams struct {
	TextDocumentPositionParams
	WorkDoneProgressParams
	PartialResultParams
}

type ImplementationRegistrationOptions struct {
	TextDocumentRegistrationOptions
	ImplementationOptions
	StaticRegistrationOptions
}

/*
A parameter literal used in inlay hint requests.

@since 3.17.0
*/
type InlayHintParams struct {
	WorkDoneProgressParams
	/*
		A parameter literal used in inlay hint requests.

		@since 3.17.0
	*/
	TextDocument TextDocumentIdentifier `json:"textDocument"`
	/*
		A parameter literal used in inlay hint requests.

		@since 3.17.0
	*/
	Range Range `json:"range"`
}

/*
Inlay hint options used during static or dynamic registration.

@since 3.17.0
*/
type InlayHintRegistrationOptions struct {
	InlayHintOptions
	TextDocumentRegistrationOptions
	StaticRegistrationOptions
}

/*
Client workspace capabilities specific to inlay hints.

@since 3.17.0
*/
type InlayHintWorkspaceClientCapabilities struct {
	/*
		Client workspace capabilities specific to inlay hints.

		@since 3.17.0
	*/
	RefreshSupport *bool `json:"refreshSupport,omitempty"`
}

/*
A parameter literal used in inline completion requests.

@since 3.18.0
*/
type InlineCompletionParams struct {
	TextDocumentPositionParams
	WorkDoneProgressParams
	/*
		A parameter literal used in inline completion requests.

		@since 3.18.0
	*/
	Context InlineCompletionContext `json:"context"`
}

/*
Inline completion options used during static or dynamic registration.

@since 3.18.0
*/
type InlineCompletionRegistrationOptions struct {
	InlineCompletionOptions
	TextDocumentRegistrationOptions
	StaticRegistrationOptions
}

/*
Client capabilities specific to inline values.

@since 3.17.0
*/
type InlineValueClientCapabilities struct {
	/*
		Client capabilities specific to inline values.

		@since 3.17.0
	*/
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
}

/*
A parameter literal used in inline value requests.

@since 3.17.0
*/
type InlineValueParams struct {
	WorkDoneProgressParams
	/*
		A parameter literal used in inline value requests.

		@since 3.17.0
	*/
	TextDocument TextDocumentIdentifier `json:"textDocument"`
	/*
		A parameter literal used in inline value requests.

		@since 3.17.0
	*/
	Range Range `json:"range"`
	/*
		A parameter literal used in inline value requests.

		@since 3.17.0
	*/
	Context InlineValueContext `json:"context"`
}

/*
Inline value options used during static or dynamic registration.

@since 3.17.0
*/
type InlineValueRegistrationOptions struct {
	InlineValueOptions
	TextDocumentRegistrationOptions
	StaticRegistrationOptions
}

/*
Returns inline value information as the complete text to be shown.

@since 3.17.0
*/
type InlineValueText struct {
	/*
		Returns inline value information as the complete text to be shown.

		@since 3.17.0
	*/
	Range Range `json:"range"`
	/*
		Returns inline value information as the complete text to be shown.

		@since 3.17.0
	*/
	Text string `json:"text"`
}

type LinkedEditingRangeParams struct {
	TextDocumentPositionParams
	WorkDoneProgressParams
}

type LinkedEditingRangeRegistrationOptions struct {
	TextDocumentRegistrationOptions
	LinkedEditingRangeOptions
	StaticRegistrationOptions
}

/*
The result of a linked editing range request.

@since 3.16.0
*/
type LinkedEditingRanges struct {
	/*
		The result of a linked editing range request.

		@since 3.16.0
	*/
	Ranges []Range `json:"ranges"`
	/*
		The result of a linked editing range request.

		@since 3.16.0
	*/
	WordPattern string `json:"wordPattern,omitempty"`
}

type MonikerParams struct {
	TextDocumentPositionParams
	WorkDoneProgressParams
	PartialResultParams
}

type MonikerRegistrationOptions struct {
	TextDocumentRegistrationOptions
	MonikerOptions
}

/*
A notebook cell.

A cell's document URI must be unique across ALL notebook
cells and can therefore be used to uniquely identify a
notebook cell or the cell's text document.

@since 3.17.0
*/
type NotebookCell struct {
	/*
		A notebook cell.

		A cell's document URI must be unique across ALL notebook
		cells and can therefore be used to uniquely identify a
		notebook cell or the cell's text document.

		@since 3.17.0
	*/
	Kind NotebookCellKind `json:"kind"`
	/*
		A notebook cell.

		A cell's document URI must be unique across ALL notebook
		cells and can therefore be used to uniquely identify a
		notebook cell or the cell's text document.

		@since 3.17.0
	*/
	Document DocumentURI `json:"document"`
	/*
		A notebook cell.

		A cell's document URI must be unique across ALL notebook
		cells and can therefore be used to uniquely identify a
		notebook cell or the cell's text document.

		@since 3.17.0
	*/
	Metadata *map[string]any `json:"metadata,omitempty"`
	/*
		A notebook cell.

		A cell's document URI must be unique across ALL notebook
		cells and can therefore be used to uniquely identify a
		notebook cell or the cell's text document.

		@since 3.17.0
	*/
	ExecutionSummary *ExecutionSummary `json:"executionSummary,omitempty"`
}

type PrepareRenameParams struct {
	TextDocumentPositionParams
	WorkDoneProgressParams
}

// @since 3.18.0
type PrepareRenamePlaceholder struct {
	// @since 3.18.0
	Range Range `json:"range"`
	// @since 3.18.0
	Placeholder string `json:"placeholder"`
}

// The publish diagnostic notification's parameters.
type PublishDiagnosticsParams struct {
	// The publish diagnostic notification's parameters.
	Uri DocumentURI `json:"uri"`
	// The publish diagnostic notification's parameters.
	Version int `json:"version,omitempty"`
	// The publish diagnostic notification's parameters.
	Diagnostics []*Diagnostic `json:"diagnostics"`
}

/*
A range in a text document expressed as (zero-based) start and end positions.

If you want to specify a range that contains a line including the line ending
character(s) then use an end position denoting the start of the next line.
For example:
```ts

	{
	    start: { line: 5, character: 23 }
	    end : { line 6, character : 0 }
	}

```
*/
type Range struct {
	/*
		A range in a text document expressed as (zero-based) start and end positions.

		If you want to specify a range that contains a line including the line ending
		character(s) then use an end position denoting the start of the next line.
		For example:
		```ts
		{
		    start: { line: 5, character: 23 }
		    end : { line 6, character : 0 }
		}
		```
	*/
	Start Position `json:"start"`
	/*
		A range in a text document expressed as (zero-based) start and end positions.

		If you want to specify a range that contains a line including the line ending
		character(s) then use an end position denoting the start of the next line.
		For example:
		```ts
		{
		    start: { line: 5, character: 23 }
		    end : { line 6, character : 0 }
		}
		```
	*/
	End Position `json:"end"`
}

// Parameters for a [ReferencesRequest].
type ReferenceParams struct {
	TextDocumentPositionParams
	WorkDoneProgressParams
	PartialResultParams
	// Parameters for a [ReferencesRequest].
	Context ReferenceContext `json:"context"`
}

// Registration options for a [ReferencesRequest].
type ReferenceRegistrationOptions struct {
	TextDocumentRegistrationOptions
	ReferenceOptions
}

// General parameters to register for a notification or to register a provider.
type Registration struct {
	// General parameters to register for a notification or to register a provider.
	Id string `json:"id"`
	// General parameters to register for a notification or to register a provider.
	Method string `json:"method"`
	// General parameters to register for a notification or to register a provider.
	RegisterOptions any `json:"registerOptions,omitempty"`
}

// The parameters of a [RenameRequest].
type RenameParams struct {
	TextDocumentPositionParams
	WorkDoneProgressParams
	// The parameters of a [RenameRequest].
	NewName string `json:"newName"`
}

// Registration options for a [RenameRequest].
type RenameRegistrationOptions struct {
	TextDocumentRegistrationOptions
	RenameOptions
}

// A generic resource operation.
type ResourceOperation struct {
	// A generic resource operation.
	Kind string `json:"kind"`
	// A generic resource operation.
	AnnotationId *ChangeAnnotationIdentifier `json:"annotationId,omitempty"`
}

// A parameter literal used in selection range requests.
type SelectionRangeParams struct {
	WorkDoneProgressParams
	PartialResultParams
	// A parameter literal used in selection range requests.
	TextDocument TextDocumentIdentifier `json:"textDocument"`
	// A parameter literal used in selection range requests.
	Positions []Position `json:"positions"`
}

type SelectionRangeRegistrationOptions struct {
	SelectionRangeOptions
	TextDocumentRegistrationOptions
	StaticRegistrationOptions
}

// @since 3.16.0
type SemanticTokens struct {
	// @since 3.16.0
	ResultId string `json:"resultId,omitempty"`
	// @since 3.16.0
	Data []uint32 `json:"data"`
}

// Parameters for a [SignatureHelpRequest].
type SignatureHelpParams struct {
	TextDocumentPositionParams
	WorkDoneProgressParams
	// Parameters for a [SignatureHelpRequest].
	Context *SignatureHelpContext `json:"context,omitempty"`
}

// Registration options for a [SignatureHelpRequest].
type SignatureHelpRegistrationOptions struct {
	TextDocumentRegistrationOptions
	SignatureHelpOptions
}

/*
Represents the signature of something callable. A signature
can have a label, like a function-name, a doc-comment, and
a set of parameters.
*/
type SignatureInformation struct {
	/*
		Represents the signature of something callable. A signature
		can have a label, like a function-name, a doc-comment, and
		a set of parameters.
	*/
	Label string `json:"label"`
	/*
		Represents the signature of something callable. A signature
		can have a label, like a function-name, a doc-comment, and
		a set of parameters.
	*/
	Documentation *rpc.Union2[string, MarkupContent] `json:"documentation,omitempty"`
	/*
		Represents the signature of something callable. A signature
		can have a label, like a function-name, a doc-comment, and
		a set of parameters.
	*/
	Parameters []ParameterInformation `json:"parameters,omitempty"`
	/*
		Represents the signature of something callable. A signature
		can have a label, like a function-name, a doc-comment, and
		a set of parameters.
	*/
	ActiveParameter uint32 `json:"activeParameter,omitempty"` // uinteger | null
}

// Describe options to be used when registered for text document change events.
type TextDocumentChangeRegistrationOptions struct {
	TextDocumentRegistrationOptions
	// Describe options to be used when registered for text document change events.
	SyncKind TextDocumentSyncKind `json:"syncKind"`
}

// Text document specific client capabilities.
type TextDocumentClientCapabilities struct {
	// Text document specific client capabilities.
	Synchronization *TextDocumentSyncClientCapabilities `json:"synchronization,omitempty"`
	// Text document specific client capabilities.
	Filters *TextDocumentFilterClientCapabilities `json:"filters,omitempty"`
	// Text document specific client capabilities.
	Completion *CompletionClientCapabilities `json:"completion,omitempty"`
	// Text document specific client capabilities.
	Hover *HoverClientCapabilities `json:"hover,omitempty"`
	// Text document specific client capabilities.
	SignatureHelp *SignatureHelpClientCapabilities `json:"signatureHelp,omitempty"`
	// Text document specific client capabilities.
	Declaration *DeclarationClientCapabilities `json:"declaration,omitempty"`
	// Text document specific client capabilities.
	Definition *DefinitionClientCapabilities `json:"definition,omitempty"`
	// Text document specific client capabilities.
	TypeDefinition *TypeDefinitionClientCapabilities `json:"typeDefinition,omitempty"`
	// Text document specific client capabilities.
	Implementation *ImplementationClientCapabilities `json:"implementation,omitempty"`
	// Text document specific client capabilities.
	References *ReferenceClientCapabilities `json:"references,omitempty"`
	// Text document specific client capabilities.
	DocumentHighlight *DocumentHighlightClientCapabilities `json:"documentHighlight,omitempty"`
	// Text document specific client capabilities.
	DocumentSymbol *DocumentSymbolClientCapabilities `json:"documentSymbol,omitempty"`
	// Text document specific client capabilities.
	CodeAction *CodeActionClientCapabilities `json:"codeAction,omitempty"`
	// Text document specific client capabilities.
	CodeLens *CodeLensClientCapabilities `json:"codeLens,omitempty"`
	// Text document specific client capabilities.
	DocumentLink *DocumentLinkClientCapabilities `json:"documentLink,omitempty"`
	// Text document specific client capabilities.
	ColorProvider *DocumentColorClientCapabilities `json:"colorProvider,omitempty"`
	// Text document specific client capabilities.
	Formatting *DocumentFormattingClientCapabilities `json:"formatting,omitempty"`
	// Text document specific client capabilities.
	RangeFormatting *DocumentRangeFormattingClientCapabilities `json:"rangeFormatting,omitempty"`
	// Text document specific client capabilities.
	OnTypeFormatting *DocumentOnTypeFormattingClientCapabilities `json:"onTypeFormatting,omitempty"`
	// Text document specific client capabilities.
	Rename *RenameClientCapabilities `json:"rename,omitempty"`
	// Text document specific client capabilities.
	FoldingRange *FoldingRangeClientCapabilities `json:"foldingRange,omitempty"`
	// Text document specific client capabilities.
	SelectionRange *SelectionRangeClientCapabilities `json:"selectionRange,omitempty"`
	// Text document specific client capabilities.
	PublishDiagnostics *PublishDiagnosticsClientCapabilities `json:"publishDiagnostics,omitempty"`
	// Text document specific client capabilities.
	CallHierarchy *CallHierarchyClientCapabilities `json:"callHierarchy,omitempty"`
	// Text document specific client capabilities.
	SemanticTokens *SemanticTokensClientCapabilities `json:"semanticTokens,omitempty"`
	// Text document specific client capabilities.
	LinkedEditingRange *LinkedEditingRangeClientCapabilities `json:"linkedEditingRange,omitempty"`
	// Text document specific client capabilities.
	Moniker *MonikerClientCapabilities `json:"moniker,omitempty"`
	// Text document specific client capabilities.
	TypeHierarchy *TypeHierarchyClientCapabilities `json:"typeHierarchy,omitempty"`
	// Text document specific client capabilities.
	InlineValue *InlineValueClientCapabilities `json:"inlineValue,omitempty"`
	// Text document specific client capabilities.
	InlayHint *InlayHintClientCapabilities `json:"inlayHint,omitempty"`
	// Text document specific client capabilities.
	Diagnostic *DiagnosticClientCapabilities `json:"diagnostic,omitempty"`
	// Text document specific client capabilities.
	InlineCompletion *InlineCompletionClientCapabilities `json:"inlineCompletion,omitempty"`
}

// General text document registration options.
type TextDocumentRegistrationOptions struct {
	// General text document registration options.
	DocumentSelector *DocumentSelector `json:"documentSelector,omitempty"` // DocumentSelector | null
}

// Save registration options.
type TextDocumentSaveRegistrationOptions struct {
	TextDocumentRegistrationOptions
	SaveOptions
}

type TextDocumentSyncClientCapabilities struct {
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
	WillSave            *bool `json:"willSave,omitempty"`
	WillSaveWaitUntil   *bool `json:"willSaveWaitUntil,omitempty"`
	DidSave             *bool `json:"didSave,omitempty"`
}

type TypeDefinitionParams struct {
	TextDocumentPositionParams
	WorkDoneProgressParams
	PartialResultParams
}

type TypeDefinitionRegistrationOptions struct {
	TextDocumentRegistrationOptions
	TypeDefinitionOptions
	StaticRegistrationOptions
}

// @since 3.17.0
type TypeHierarchyClientCapabilities struct {
	// @since 3.17.0
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
}

/*
The parameter of a `textDocument/prepareTypeHierarchy` request.

@since 3.17.0
*/
type TypeHierarchyPrepareParams struct {
	TextDocumentPositionParams
	WorkDoneProgressParams
}

/*
Type hierarchy options used during static or dynamic registration.

@since 3.17.0
*/
type TypeHierarchyRegistrationOptions struct {
	TextDocumentRegistrationOptions
	TypeHierarchyOptions
	StaticRegistrationOptions
}

// The parameters sent in a will save text document notification.
type WillSaveTextDocumentParams struct {
	// The parameters sent in a will save text document notification.
	TextDocument TextDocumentIdentifier `json:"textDocument"`
	// The parameters sent in a will save text document notification.
	Reason TextDocumentSaveReason `json:"reason"`
}

type WindowClientCapabilities struct {
	WorkDoneProgress *bool                                 `json:"workDoneProgress,omitempty"`
	ShowMessage      *ShowMessageRequestClientCapabilities `json:"showMessage,omitempty"`
	ShowDocument     *ShowDocumentClientCapabilities       `json:"showDocument,omitempty"`
}

/*
Code action tags are extra annotations that tweak the behavior of a code action.

@since 3.18.0
*/
type CodeActionTag uint32

const (
	// Marks the code action as LLM-generated.
	CodeActionTagLLMGenerated CodeActionTag = 1
)

/*
The reason why code actions were requested.

@since 3.17.0
*/
type CodeActionTriggerKind uint32

const (
	// Code actions were explicitly requested by the user or by an extension.
	CodeActionTriggerInvoked CodeActionTriggerKind = 1
	/*
		Code actions were requested automatically.

		This typically happens when current selection in a file changes, but can
		also be triggered when file content changes.
	*/
	CodeActionTriggerAutomatic CodeActionTriggerKind = 2
)

// How a completion was triggered
type CompletionTriggerKind uint32

const (
	/*
		Completion was triggered by typing an identifier (24x7 code
		complete), manual invocation (e.g Ctrl+Space) or via API.
	*/
	CompletionTriggerInvoked CompletionTriggerKind = 1
	/*
		Completion was triggered by a trigger character specified by
		the `triggerCharacters` properties of the `CompletionRegistrationOptions`.
	*/
	CompletionTriggerTriggerCharacter CompletionTriggerKind = 2
	// Completion was re-triggered as current completion list is incomplete
	CompletionTriggerTriggerForIncompleteCompletions CompletionTriggerKind = 3
)

/*
The definition of a symbol represented as one or many  locations [Location].
For most programming languages there is only one location at which a symbol is
defined.

Servers should prefer returning `DefinitionLink` over `Definition` if supported
by the client.
*/
type Definition = rpc.Union2[Location, []Location]

/*
Information about where a symbol is defined.

Provides additional metadata over normal  location [Location] definitions, including the range of
the defining symbol
*/
type DefinitionLink = LocationLink

// The diagnostic's severity.
type DiagnosticSeverity uint32

const (
	// Reports an error.
	DiagnosticSeverityError DiagnosticSeverity = 1
	// Reports a warning.
	DiagnosticSeverityWarning DiagnosticSeverity = 2
	// Reports an information.
	DiagnosticSeverityInformation DiagnosticSeverity = 3
	// Reports a hint.
	DiagnosticSeverityHint DiagnosticSeverity = 4
)

/*
The diagnostic tags.

@since 3.15.0
*/
type DiagnosticTag uint32

const (
	/*
		Unused or unnecessary code.

		Clients are allowed to render diagnostics with this tag faded out instead of having
		an error squiggle.
	*/
	DiagnosticTagUnnecessary DiagnosticTag = 1
	/*
		Deprecated or obsolete code.

		Clients are allowed to rendered diagnostics with this tag strike through.
	*/
	DiagnosticTagDeprecated DiagnosticTag = 2
)

/*
The result of a document diagnostic pull request. A report can
either be a full report containing all diagnostics for the
requested document or an unchanged report indicating that nothing
has changed in terms of diagnostics in comparison to the last
pull request.

@since 3.17.0
*/
type DocumentDiagnosticReport = rpc.Union2[RelatedFullDocumentDiagnosticReport, RelatedUnchangedDocumentDiagnosticReport]

/*
The document diagnostic report kinds.

@since 3.17.0
*/
type DocumentDiagnosticReportKind string

const (
	/*
		A diagnostic report with a full
		set of problems.
	*/
	DocumentDiagnosticReportFull DocumentDiagnosticReportKind = "full"
	/*
		A report indicating that the last
		returned report is still accurate.
	*/
	DocumentDiagnosticReportUnchanged DocumentDiagnosticReportKind = "unchanged"
)

/*
The document diagnostic report used when reporting partial result.

When using partial results, the first literal sent needs to be a
DocumentDiagnosticReport providing the diagnostics on the document
followed by n DocumentDiagnosticReportPartialResult literals providing
the diagnostics for related documents.

```
DocumentDiagnosticReport
DocumentDiagnosticReportPartialResult
DocumentDiagnosticReportPartialResult
...
```

@since 3.18.1
*/
type DocumentDiagnosticReportProgress = rpc.Union2[DocumentDiagnosticReport, DocumentDiagnosticReportPartialResult]

/*
A document filter describes a top level text document or
a notebook cell document.

@since 3.17.0 - support for NotebookCellTextDocumentFilter.
*/
type DocumentFilter = rpc.Union2[TextDocumentFilter, NotebookCellTextDocumentFilter]

// A document highlight kind.
type DocumentHighlightKind uint32

const (
	// A textual occurrence.
	DocumentHighlightText DocumentHighlightKind = 1
	// Read-access of a symbol, like reading a variable.
	DocumentHighlightRead DocumentHighlightKind = 2
	// Write-access of a symbol, like writing to a variable.
	DocumentHighlightWrite DocumentHighlightKind = 3
)

/*
A document selector is the combination of one or many document filters.

@sample `let sel:DocumentSelector = [{ language: 'typescript' }, { language: 'json', pattern: '**∕tsconfig.json' }]`;

The use of a string as a document filter is deprecated @since 3.16.0.
*/
type DocumentSelector = []DocumentFilter

// Predefined error codes.
type ErrorCodes int

const (
	ErrorCodesParseError     ErrorCodes = -32700
	ErrorCodesInvalidRequest ErrorCodes = -32600
	ErrorCodesMethodNotFound ErrorCodes = -32601
	ErrorCodesInvalidParams  ErrorCodes = -32602
	ErrorCodesInternalError  ErrorCodes = -32603
	/*
		Error code indicating that a server received a notification or
		request before the server has received the `initialize` request.
	*/
	ErrorCodesServerNotInitialized ErrorCodes = -32002
	ErrorCodesUnknownErrorCode     ErrorCodes = -32001
)

/*
The glob pattern. Either a string pattern or a relative pattern.

@since 3.17.0
*/
type GlobPattern = rpc.Union2[Pattern, RelativePattern]

/*
Describes how an  inline completion provider [InlineCompletionItemProvider] was triggered.

@since 3.18.0
*/
type InlineCompletionTriggerKind uint32

const (
	// Completion was triggered explicitly by a user gesture.
	InlineCompletionTriggerInvoked InlineCompletionTriggerKind = 1
	// Completion was triggered automatically while editing.
	InlineCompletionTriggerAutomatic InlineCompletionTriggerKind = 2
)

/*
Inline value information can be provided by different means:

  - directly as a text value (class InlineValueText).
  - as a name to use for a variable lookup (class InlineValueVariableLookup)
  - as an evaluatable expression (class InlineValueEvaluatableExpression)

The InlineValue types combines all inline value types into one type.

@since 3.17.0
*/
type InlineValue = rpc.Union3[InlineValueText, InlineValueVariableLookup, InlineValueEvaluatableExpression] // InlineValueText | InlineValueVariableLookup | InlineValueEvaluatableExpression

/*
Defines whether the insert text in a completion item should be interpreted as
plain text or a snippet.
*/
type InsertTextFormat uint32

const (
	// The primary text to be inserted is treated as a plain string.
	InsertTextFormatPlainText InsertTextFormat = 1
	/*
		The primary text to be inserted is treated as a snippet.

		A snippet can define tab stops and placeholders with `$1`, `$2`
		and `${3:foo}`. `$0` defines the final tab stop, it defaults to
		the end of the snippet. Placeholders with equal identifiers are linked,
		that is typing in one will update others too.

		See also: https://microsoft.github.io/language-server-protocol/specifications/specification-current/#snippet_syntax
	*/
	InsertTextFormatSnippet InsertTextFormat = 2
)

/*
How whitespace and indentation is handled during completion
item insertion.

@since 3.16.0
*/
type InsertTextMode uint32

const (
	/*
		The insertion or replace strings is taken as it is. If the
		value is multi line the lines below the cursor will be
		inserted using the indentation defined in the string value.
		The client will not apply any kind of adjustments to the
		string.
	*/
	InsertTextAsIs InsertTextMode = 1
	/*
		The editor adjusts leading whitespace of new lines so that
		they match the indentation up to the cursor of the line for
		which the item is accepted.

		Consider a line like this: <2tabs><cursor><3tabs>foo. Accepting a
		multi line completion item is indented using 2 tabs and all
		following lines inserted will be indented using 2 tabs as well.
	*/
	InsertTextAdjustIndentation InsertTextMode = 2
)

/*
A notebook cell kind.

@since 3.17.0
*/
type NotebookCellKind uint32

const (
	// A markup-cell is formatted source that is used for display.
	NotebookCellMarkup NotebookCellKind = 1
	// A code-cell is source code.
	NotebookCellCode NotebookCellKind = 2
)

/*
A notebook document filter denotes a notebook document by
different properties. The properties will be match
against the notebook's URI (same as with documents)

@since 3.17.0
*/
type NotebookDocumentFilter = rpc.Union3[NotebookDocumentFilterNotebookType, NotebookDocumentFilterScheme, NotebookDocumentFilterPattern] // NotebookDocumentFilterNotebookType | NotebookDocumentFilterScheme | NotebookDocumentFilterPattern

type PrepareRenameResult = rpc.Union3[Range, PrepareRenamePlaceholder, PrepareRenameDefaultBehavior] // Range | PrepareRenamePlaceholder | PrepareRenameDefaultBehavior

type PrepareSupportDefaultBehavior uint32

const (
	/*
		The client's default behavior is to select the identifier
		according the to language's syntax rule.
	*/
	PrepareSupportDefaultBehaviorIdentifier PrepareSupportDefaultBehavior = 1
)

type ResourceOperationKind string

const (
	// Supports creating new files and folders.
	ResourceOperationCreate ResourceOperationKind = "create"
	// Supports renaming existing files and folders.
	ResourceOperationRename ResourceOperationKind = "rename"
	// Supports deleting existing files and folders.
	ResourceOperationDelete ResourceOperationKind = "delete"
)

/*
A set of predefined token modifiers. This set is not fixed
an clients can specify additional token types via the
corresponding client capabilities.

@since 3.16.0
*/
type SemanticTokenModifiers string

const (
	SemanticTokenModifiersDeclaration    SemanticTokenModifiers = "declaration"
	SemanticTokenModifiersDefinition     SemanticTokenModifiers = "definition"
	SemanticTokenModifiersReadonly       SemanticTokenModifiers = "readonly"
	SemanticTokenModifiersStatic         SemanticTokenModifiers = "static"
	SemanticTokenModifiersDeprecated     SemanticTokenModifiers = "deprecated"
	SemanticTokenModifiersAbstract       SemanticTokenModifiers = "abstract"
	SemanticTokenModifiersAsync          SemanticTokenModifiers = "async"
	SemanticTokenModifiersModification   SemanticTokenModifiers = "modification"
	SemanticTokenModifiersDocumentation  SemanticTokenModifiers = "documentation"
	SemanticTokenModifiersDefaultLibrary SemanticTokenModifiers = "defaultLibrary"
)

/*
A set of predefined token types. This set is not fixed
an clients can specify additional token types via the
corresponding client capabilities.

@since 3.16.0
*/
type SemanticTokenTypes string

const (
	SemanticTokenTypesNamespace SemanticTokenTypes = "namespace"
	/*
		Represents a generic type. Acts as a fallback for types which can't be mapped to
		a specific type like class or enum.
	*/
	SemanticTokenTypesType          SemanticTokenTypes = "type"
	SemanticTokenTypesClass         SemanticTokenTypes = "class"
	SemanticTokenTypesEnum          SemanticTokenTypes = "enum"
	SemanticTokenTypesInterface     SemanticTokenTypes = "interface"
	SemanticTokenTypesStruct        SemanticTokenTypes = "struct"
	SemanticTokenTypesTypeParameter SemanticTokenTypes = "typeParameter"
	SemanticTokenTypesParameter     SemanticTokenTypes = "parameter"
	SemanticTokenTypesVariable      SemanticTokenTypes = "variable"
	SemanticTokenTypesProperty      SemanticTokenTypes = "property"
	SemanticTokenTypesEnumMember    SemanticTokenTypes = "enumMember"
	SemanticTokenTypesEvent         SemanticTokenTypes = "event"
	SemanticTokenTypesFunction      SemanticTokenTypes = "function"
	SemanticTokenTypesMethod        SemanticTokenTypes = "method"
	SemanticTokenTypesMacro         SemanticTokenTypes = "macro"
	SemanticTokenTypesKeyword       SemanticTokenTypes = "keyword"
	SemanticTokenTypesModifier      SemanticTokenTypes = "modifier"
	SemanticTokenTypesComment       SemanticTokenTypes = "comment"
	SemanticTokenTypesString        SemanticTokenTypes = "string"
	SemanticTokenTypesNumber        SemanticTokenTypes = "number"
	SemanticTokenTypesRegexp        SemanticTokenTypes = "regexp"
	SemanticTokenTypesOperator      SemanticTokenTypes = "operator"
	// @since 3.17.0
	SemanticTokenTypesDecorator SemanticTokenTypes = "decorator"
	// @since 3.18.0
	SemanticTokenTypesLabel SemanticTokenTypes = "label"
)

/*
How a signature help was triggered.

@since 3.15.0
*/
type SignatureHelpTriggerKind uint32

const (
	// Signature help was invoked manually by the user or by a command.
	SignatureHelpTriggerInvoked SignatureHelpTriggerKind = 1
	// Signature help was triggered by a trigger character.
	SignatureHelpTriggerTriggerCharacter SignatureHelpTriggerKind = 2
	// Signature help was triggered by the cursor moving or by the document content changing.
	SignatureHelpTriggerContentChange SignatureHelpTriggerKind = 3
)

// A symbol kind.
type SymbolKind uint32

const (
	SymbolFile          SymbolKind = 1
	SymbolModule        SymbolKind = 2
	SymbolNamespace     SymbolKind = 3
	SymbolPackage       SymbolKind = 4
	SymbolClass         SymbolKind = 5
	SymbolMethod        SymbolKind = 6
	SymbolProperty      SymbolKind = 7
	SymbolField         SymbolKind = 8
	SymbolConstructor   SymbolKind = 9
	SymbolEnum          SymbolKind = 10
	SymbolInterface     SymbolKind = 11
	SymbolFunction      SymbolKind = 12
	SymbolVariable      SymbolKind = 13
	SymbolConstant      SymbolKind = 14
	SymbolString        SymbolKind = 15
	SymbolNumber        SymbolKind = 16
	SymbolBoolean       SymbolKind = 17
	SymbolArray         SymbolKind = 18
	SymbolObject        SymbolKind = 19
	SymbolKey           SymbolKind = 20
	SymbolNull          SymbolKind = 21
	SymbolEnumMember    SymbolKind = 22
	SymbolStruct        SymbolKind = 23
	SymbolEvent         SymbolKind = 24
	SymbolOperator      SymbolKind = 25
	SymbolTypeParameter SymbolKind = 26
)

/*
Symbol tags are extra annotations that tweak the rendering of a symbol.

@since 3.16
*/
type SymbolTag uint32

const (
	// Render a symbol as obsolete, usually using a strike-out.
	SymbolTagDeprecated SymbolTag = 1
)

/*
An event describing a change to a text document. If only a text is provided
it is considered to be the full content of the document.
*/
type TextDocumentContentChangeEvent = rpc.Union2[TextDocumentContentChangePartial, TextDocumentContentChangeWholeDocument]

// Represents reasons why a text document is saved.
type TextDocumentSaveReason uint32

const (
	/*
		Manually triggered, e.g. by the user pressing save, by starting debugging,
		or by an API call.
	*/
	TextDocumentSaveReasonManual TextDocumentSaveReason = 1
	// Automatic after a delay.
	TextDocumentSaveReasonAfterDelay TextDocumentSaveReason = 2
	// When the editor lost focus.
	TextDocumentSaveReasonFocusOut TextDocumentSaveReason = 3
)

/*
Defines how the host (editor) should sync
document changes to the language server.
*/
type TextDocumentSyncKind uint32

const (
	// Documents should not be synced at all.
	TextDocumentSyncNone TextDocumentSyncKind = 0
	/*
		Documents are synced by always sending the full content
		of the document.
	*/
	TextDocumentSyncFull TextDocumentSyncKind = 1
	/*
		Documents are synced by sending the full content on open.
		After that only incremental updates to the document are
		send.
	*/
	TextDocumentSyncIncremental TextDocumentSyncKind = 2
)

type TokenFormat string

const (
	TokenFormatRelative TokenFormat = "relative"
)

type TraceValue string

const (
	// Turn tracing off.
	TraceValueOff TraceValue = "off"
	// Trace messages only.
	TraceValueMessages TraceValue = "messages"
	// Verbose message tracing.
	TraceValueVerbose TraceValue = "verbose"
)
