// Code generated by lsp/generate; DO NOT EDIT.
package lsp

/*
The parameter of a `typeHierarchy/subtypes` request.

@since 3.17.0
*/
type TypeHierarchySubtypesParams struct {
	WorkDoneProgressParams
	PartialResultParams
	Item *TypeHierarchyItem `json:"item"`
}

/*
The parameter of a `typeHierarchy/supertypes` request.

@since 3.17.0
*/
type TypeHierarchySupertypesParams struct {
	WorkDoneProgressParams
	PartialResultParams
	Item *TypeHierarchyItem `json:"item"`
}

/*
A diagnostic report indicating that the last returned
report is still accurate.

@since 3.17.0
*/
type UnchangedDocumentDiagnosticReport struct {
	/*
		A document diagnostic report indicating
		no changes to the last result. A server can
		only return `unchanged` if result ids are
		provided.
	*/
	Kind string `json:"kind"` // unchanged
	/*
		A result id which will be sent on the next
		diagnostic request for the same document.
	*/
	ResultId string `json:"resultId"`
}

/*
Moniker uniqueness level to define scope of the moniker.

@since 3.16.0
*/
type UniquenessLevel string

const (
	// The moniker is only unique inside a document
	UniquenessLevelDocument UniquenessLevel = "document"
	// The moniker is unique inside a project for which a dump got created
	UniquenessLevelProject UniquenessLevel = "project"
	// The moniker is unique inside the group to which a project belongs
	UniquenessLevelGroup UniquenessLevel = "group"
	// The moniker is unique inside the moniker scheme.
	UniquenessLevelScheme UniquenessLevel = "scheme"
	// The moniker is globally unique
	UniquenessLevelGlobal UniquenessLevel = "global"
)
