// Code generated by lsp/generate; DO NOT EDIT.
package lsp

// The log message parameters.
type LogMessageParams struct {
	// The log message parameters.
	Type MessageType `json:"type"`
	// The log message parameters.
	Message string `json:"message"`
}

/*
Params to show a resource in the UI.

@since 3.16.0
*/
type ShowDocumentParams struct {
	/*
		Params to show a resource in the UI.

		@since 3.16.0
	*/
	Uri URI `json:"uri"`
	/*
		Params to show a resource in the UI.

		@since 3.16.0
	*/
	External *bool `json:"external,omitempty"`
	/*
		Params to show a resource in the UI.

		@since 3.16.0
	*/
	TakeFocus *bool `json:"takeFocus,omitempty"`
	/*
		Params to show a resource in the UI.

		@since 3.16.0
	*/
	Selection *Range `json:"selection,omitempty"`
}

/*
The result of a showDocument request.

@since 3.16.0
*/
type ShowDocumentResult struct {
	/*
		The result of a showDocument request.

		@since 3.16.0
	*/
	Success bool `json:"success"`
}

// The parameters of a notification message.
type ShowMessageParams struct {
	// The parameters of a notification message.
	Type MessageType `json:"type"`
	// The parameters of a notification message.
	Message string `json:"message"`
}

// Show message request client capabilities
type ShowMessageRequestClientCapabilities struct {
	// Show message request client capabilities
	MessageActionItem *ClientShowMessageActionItemOptions `json:"messageActionItem,omitempty"`
}

type ShowMessageRequestParams struct {
	Type    MessageType          `json:"type"`
	Message string               `json:"message"`
	Actions *[]MessageActionItem `json:"actions,omitempty"`
}

/*
Signature help represents the signature of something
callable. There can be multiple signature but only one
active and only one active parameter.
*/
type SignatureHelp struct {
	/*
		Signature help represents the signature of something
		callable. There can be multiple signature but only one
		active and only one active parameter.
	*/
	Signatures []SignatureInformation `json:"signatures"`
	/*
		Signature help represents the signature of something
		callable. There can be multiple signature but only one
		active and only one active parameter.
	*/
	ActiveSignature uint32 `json:"activeSignature,omitempty"`
	/*
		Signature help represents the signature of something
		callable. There can be multiple signature but only one
		active and only one active parameter.
	*/
	ActiveParameter uint32 `json:"activeParameter,omitempty"` // uinteger | null
}
