// Code generated by lsp/generate; DO NOT EDIT.
package lsp

type WorkDoneProgressCancelParams struct {
	Token ProgressToken `json:"token"`
}

type WorkDoneProgressCreateParams struct {
	Token ProgressToken `json:"token"`
}

type WorkDoneProgressEnd struct {
	Kind    string `json:"kind"` // end
	Message string `json:"message,omitempty"`
}
