// Code generated by lsp/generate; DO NOT EDIT.
package lsp

import "github.com/ProCode-Software/klar/pkg/lsp/rpc"

/*
A special workspace symbol that supports locations without a range.

See also SymbolInformation.

@since 3.17.0
*/
type WorkspaceSymbol struct {
	BaseSymbolInformation
	/*
		A special workspace symbol that supports locations without a range.

		See also SymbolInformation.

		@since 3.17.0
	*/
	Location rpc.Union2[Location, LocationUriOnly] `json:"location"`
	/*
		A special workspace symbol that supports locations without a range.

		See also SymbolInformation.

		@since 3.17.0
	*/
	Data any `json:"data,omitempty"`
}

// Client capabilities for a [WorkspaceSymbolRequest].
type WorkspaceSymbolClientCapabilities struct {
	// Client capabilities for a [WorkspaceSymbolRequest].
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
	// Client capabilities for a [WorkspaceSymbolRequest].
	SymbolKind *ClientSymbolKindOptions `json:"symbolKind,omitempty"`
	// Client capabilities for a [WorkspaceSymbolRequest].
	TagSupport *ClientSymbolTagOptions `json:"tagSupport,omitempty"`
	// Client capabilities for a [WorkspaceSymbolRequest].
	ResolveSupport *ClientSymbolResolveOptions `json:"resolveSupport,omitempty"`
}
